trpc/trpc

- examples/next-ssg-chat/pages/api/trpc/[...trpc].ts
- examples/playground/src/client.ts
- examples/playground/src/server.ts
- packages/client/src/createTRPCClient.ts
- packages/react/src/createReactQueryHooks.ts
- packages/server/src/router.ts
- packages/server/src/subscription.ts
mostly to keep the example clean - might remove later
> Move subscription pull factory to core

- packages/server/src/router.ts
joi's typescript support is too poor
> remove joi traces

- README.md
- examples/next-hello-world/package.json
- examples/next-ssg-chat/package.json
- examples/next-ssg-chat/pages/_app.tsx
- examples/next-ssg-chat/pages/index.tsx
- examples/next-ssg-chat/utils/trpc.ts
- examples/playground/package.json
- lerna.json
- packages/client/package.json
- packages/client/src/createTRPCClient.ts
- packages/react/package.json
- packages/react/src/createReactQueryHooks.ts
- packages/server/package.json
- packages/server/src/http.ts
- packages/server/src/transformer.ts
- move data transformers to http client
- use transformer in de-/rehydration
> Simplify hydration

- examples/next-ssg-chat/package.json
- package.json
makes sure you can run chat example
> add prisma to nohoist

- examples/playground/src/client.ts
- examples/playground/src/server.ts
- packages/client/src/createTRPCClient.ts
- packages/react/src/createReactQueryHooks.ts
- packages/server/src/http.ts
- client subscription support
- fix backpressure logic
- fix `example:playground`
> client subscription support

- packages/client/src/createTRPCClient.ts
- packages/react/src/createReactQueryHooks.ts
- packages/server/src/http.ts
- packages/server/src/router.ts
- packages/server/src/subscription.ts
- packages/server/test/_testHelpers.ts
- packages/server/test/express.test.tsx
- packages/server/test/react.test.tsx
- packages/server/test/subscriptions.test.tsx
- packages/server/test/validators.test.ts
- get test cov up to almost 90%
- fix some type inference on subscriptions
- separate express + react tests
- fix `subscription()` retry function
> subscriptions testing 

- packages/react/src/createReactQueryHooks.ts
- packages/server/test/react.test.tsx
> `prefetchQuery()`

- packages/server/src/procedure.ts
- packages/server/src/router.ts
> move middleware calls to procedures

- packages/server/src/router.ts
refactor `middleware()` to return a new instance of Router
> refactor `middleware()` to return new instance

- packages/server/src/errors.ts
- packages/server/src/procedure.ts
- packages/server/test/index.test.tsx
> error response when passing input to ProcedureWithoutInput

- README.md
- examples/next-hello-world/pages/api/trpc/[...trpc].ts
- examples/playground/src/client.ts
- examples/playground/src/server.ts
> document auth

- examples/next-hello-world/package.json
- examples/next-ssg-chat/package.json
- examples/playground/package.json
- examples/standalone-server/package.json
- package.json
- packages/client/package.json
- packages/react/package.json
- yarn.lock
> add @manypkg/cli linter

- examples/next-hello-world/pages/api/trpc/[trpc].ts
- examples/next-hello-world/pages/index.tsx
- examples/next-prisma-todomvc/pages/api/trpc/[trpc].ts
- examples/next-ssg-chat/pages/api/trpc/[trpc].ts
- www/docs/main/contributing.md
- www/docs/react/nextjs.md
- www/docs/server/error-formatting.md
- www/docs/server/error-handling.md
- www/docs/server/merging-routers.md
try https://hello-world-git-feature-improve-example.tmp.trpc.io/ - propagating server-side zod validation back to client
> improve docs & examples

- packages/client/package.json
- packages/react/package.json
- @trpc/client has hard dependency on @trpc/server
- @trpc/react has hard dependency on @trpc/client
- @trpc/react has hard dependency on @trpc/server
> turn internal devDeps into actual deps

- .codesandbox/ci.json
> API rate limit exceeded for app ID c07a89833b557afc7be2.
> rm codesandbox ci

- examples/next-prisma-todomvc/package.json
- examples/next-prisma-todomvc/pages/[filter].tsx
> improve race condition on todomvc

- examples/next-hello-world/package.json
- examples/next-hello-world/pages/api/trpc/[trpc].ts
- examples/next-hello-world/pages/index.tsx
- examples/next-prisma-todomvc/package.json
- examples/next-ssg-chat/package.json
- examples/playground/package.json
- examples/standalone-server/package.json
- lerna.json
- packages/client/package.json
- packages/next/package.json
- packages/react/package.json
- packages/server/package.json
- packages/server/src/errors.ts
> fix http status code return

- www/docs/main/introduction.md
- www/docs/react/nextjs.md
- www/docusaurus.config.js
- www/src/css/custom.css
- www/src/pages/index.js
- www/src/pages/styles.module.css
I'm about to post my blog post about tRPC and just wanted to tweak the design of the homepage so it's a little more readable.
> Design tweaks to homepage

- packages/react/src/ssg.ts
> expose `createSSGHelpers().queryClient`

- packages/server/src/types.ts
fix `Dict` export - should be `T | undefined`
> fix `Dict` export

- www/docs/react/queries-and-mutations.md
- www/sidebars.js
See https://www-git-feature-mutation-doc.tmp.trpc.io/docs/react-queries-and-mutations
Feel free to make tweaks and push straight to this branch if you want, @kripod / @simonedelmann!
> add docs for queries & mutations

- www/docs/react/queries-and-mutations.md
See https://github.com/trpc/trpc/pull/405
> Docs: add mutation example

- www/docs/main/express.md
- www/sidebars.js
> add express docs

- .eslintrc
- babel.config.js
- examples/next-hello-world/jest-playwright.config.js
- examples/next-hello-world/jest.config.js
- examples/next-prisma-todomvc/jest-playwright.config.js
- examples/next-prisma-todomvc/jest.config.js
- examples/next-prisma-todomvc/next.config.js
- examples/next-prisma-todomvc/utils/trpc.ts
- examples/next-ssg-chat/jest-playwright.config.js
- examples/next-ssg-chat/jest.config.js
- examples/next-ssg-chat/pages/api/trpc/[trpc].ts
- examples/next-ssg-chat/pages/index.tsx
- examples/next-ssg-chat/utils/trpc.ts
- package.json
- packages/next/src/withTRPC.tsx
- packages/react/src/createReactQueryHooks.tsx
- packages/react/src/internals/context.tsx
- packages/server/jest.config.js
- packages/server/src/procedure.ts
- packages/server/src/router.ts
- packages/server/test/next.test.ts
- packages/server/test/react.test.tsx
- www/sidebars.js
- yarn.lock
thought this was already there. annoying diff 🤦
> add prettier to eslint config

- examples/express-server/package.json
- examples/next-chat/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/standalone-server/package.json
- lerna.json
- packages/client/package.json
- packages/next/package.json
- packages/react/package.json
- packages/server/package.json
- change from peer deps to deps
> fix peer dependencies between packages

- packages/server/src/router.ts
- packages/server/test/errors.test.ts
did this as a separate pr because i can't figure out the type errors in the ci
> prevent double formatters

- packages/server/src/router.ts
- packages/server/test/errors.test.ts
- refactor router initialization in order to simplify work with #545
(sorry for all the force pushes to the branch, was fighting with CI)
> refactor router initialization

- packages/client/src/createTRPCClient.ts
- packages/client/src/internals/TRPCAbortError.ts
- packages/client/src/internals/TRPCAbortErrorSignal.ts
- packages/client/src/internals/executeChain.ts
- packages/client/src/links/httpBatchLink.ts
- packages/client/src/links/httpLink.ts
- packages/server/test/httpSubscriptions.test.tsx
- packages/server/test/index.test.tsx
- packages/server/test/links.test.ts
- packages/server/test/validators.test.ts
> fix request cancelling

- packages/client/src/internals/httpRequest.ts
- packages/client/src/links/httpBatchLink.ts
- packages/client/src/links/httpLink.ts
- packages/client/src/links/wsLink.ts
- packages/server/src/http/requestHandler.ts
- packages/server/src/rpc/codes.ts
- packages/server/src/rpc/envelopes.ts
- packages/server/src/ws/wssHandler.ts
- packages/server/test/next.test.ts
- packages/server/test/websockets.test.ts
- www/docs/further/rpc.md
realised this is a bit overly-complex
- no req id on http
- refactor client a bit
> no req id on http

- examples/.wip/next-chat/package.json
- examples/.wip/next-prisma-starter-websockets/package.json
- examples/express-server/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/standalone-server/package.json
- lerna.json
- packages/client/package.json
- packages/next/package.json
- packages/next/src/withTRPC.tsx
- packages/react/package.json
- packages/server/package.json
- refactor `withTRPC()` to be a bit more sensible
> refactor/cleanup `withTRPC()`

- examples/.wip/next-chat/package.json
- examples/.wip/next-prisma-starter-websockets/package.json
- examples/express-server/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/standalone-server/package.json
- lerna.json
- packages/client/package.json
- packages/next/package.json
- packages/react/package.json
- packages/server/package.json
- packages/server/src/TRPCError.ts
- packages/server/src/adapters/next.ts
- packages/server/src/http/errors.ts
- packages/server/src/http/internals/getPostBody.ts
- packages/server/src/http/internals/getQueryInput.ts
- packages/server/src/http/requestHandler.ts
- packages/server/src/index.ts
- packages/server/src/internals/BaseHandlerOptions.ts
- packages/server/src/internals/errors.ts
- packages/server/src/procedure.ts
- packages/server/src/router.ts
- packages/server/src/ws/wssHandler.ts
- packages/server/test/errors.test.ts
> fix - export `TRPCError`

- packages/server/src/procedure.ts
fail invalid input parser function on boot instead of on parse
> refactor: get parse function on init

- README.md
- www/docs/main/love.md
- www/docs/main/sponsors.md
- www/sidebars.js
💰 
Thanks for all your hard work. We appreciate all of the work you've put into this library.
> Added Newfront as a company sponsor

- packages/server/src/http/internals/HTTPHandlerOptions.ts
- packages/server/src/router.ts
- packages/server/src/ws/wssHandler.ts
- packages/server/test/_testHelpers.ts
- packages/server/test/links.test.ts
- packages/server/test/websockets.test.ts
Continuation of https://github.com/trpc/trpc/pull/871
Closes #218
> Allow createContext to be optional if there's no context

- packages/client/src/internals/TRPCClient.ts
- packages/client/src/internals/httpRequest.ts
- packages/client/src/links/core.ts
- packages/server/test/headers.test.tsx
> Add support for async client headers

- packages/server/test/inference.test.ts
Related to #956 / cc @mmkal  - I would prefer not to lose this.
> add type inference tests

- examples/next-prisma-todomvc/src/pages/[filter].tsx
- packages/server/test/react.test.tsx
> fix mutation type — tweaks

- README.md
- www/docs/main/sponsors.md
add @hidrb! ❤️ 
@mmkal please tweak and merge :)
> add new sponsor

- .github/workflows/examples-node12.yml
- .github/workflows/examples.yml
- package.json
- packages/next/src/withTRPC.tsx
- packages/react/src/createReactQueryHooks.tsx
- packages/react/src/internals/context.tsx
ability to access the `NextPageContext` on pages when doing server-side rendering
> add `ssrContext` to `TRPCProvider`

- .github/workflows/main.yml
- package.json
- packages/next/package.json
- packages/react/package.json
- packages/server/jest.config.js
- packages/server/jest.setup.js
- yarn.lock
> add tests for `react-query` `4`

- www/docs/further/awesome-trpc.mdx
- www/sidebars.js
cc @sachinraja @mmkal
https://www-git-katt-awesome-trpc-trpc.vercel.app/docs/awesome-trpc
> Add "Awesome tRPC"-section on website

- www/docs/further/awesome-trpc.mdx
😎  https://github.com/trpc/trpc/issues/1375#issuecomment-1009463928
> Add Cloudflare Example link

- packages/next/package.json
- yarn.lock
Fixes https://github.com/trpc/trpc/issues/1343
Third time's the charm 🤞
> bump react-ssr-prepass to 1.5.0

- examples/.wip/next-prisma-starter--big/package.json
- examples/next-prisma-starter-websockets/package.json
- examples/next-prisma-starter/package.json
- package.json
- yarn.lock
upgrade prettier because of https://github.com/facebook/jest/issues/12112
> bump prettier

- packages/react/src/internals/context.tsx
- packages/server/test/react.test.tsx
> Make `invalidateQueries()` to align with `react-query`

- www/docs/further/awesome-trpc.mdx
https://github.com/sachinraja/trpc-playground
https://twitter.com/s4chinraja/status/1485048590741360642?t=l5sFgH6sqJayIJB47kH07Q&s=19
> add tRPC Playground to awesome-trpc

- www/docs/main/introduction.md
- renamed "Introducing tRPC​" into "Features". You already introduced tRPC in the first paragraph.
- synced the features section with README
> docs: update introduction

- packages/server/src/adapters/ws.ts
- packages/server/test/websockets.test.ts
> fix WebSockets request parsing

- www/docs/further/further-reading.md
Hello 👋! I love the Further Reading doc on the comparisons between Blitz and GraphQL. It's fantastically written but I noticed just a couple typos that could be corrected and some language that could be streamlined.
I also added a section on the end that I think is helpful context on the current state of Blitz and tRPC, but feel free to cut that if you don't think it's relevant to the rest of the doc.
> Further Reading edits and additions

- README.md
cc @sachinraja @timcole
https://github.com/trpc/trpc/tree/katt/core-team#core-team
> Add extra recognition for contributors

- examples/next-prisma-starter-websockets/package.json
- examples/next-prisma-starter-websockets/postcss.config.js
- examples/next-prisma-starter-websockets/src/pages/_app.tsx
- examples/next-prisma-starter-websockets/src/pages/index.tsx
- examples/next-prisma-starter-websockets/src/styles/global.css
- examples/next-prisma-starter-websockets/tailwind.config.js
- examples/next-prisma-starter-websockets/test/playwright.test.ts
- yarn.lock
I tried to make the WebSocket demo looks like the Discord appearance.
PC|Mobile
---|-------
PC|Mobile
---|-------
https://user-images.githubusercontent.com/535254/159174245-b4c485c6-f2fd-4d44-8997-95e86dcb6b67.mp4
> Improve WebSocket example design

- packages/server/tsconfig.json
https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping#node-14
> update to node 14 build target

- www/docs/further/awesome-trpc.mdx
https://github.com/sachinraja/trpc-rakkas
> add tRPC + Rakkas to list of examples

- packages/server/src/internals/middlewares.ts
- packages/server/src/internals/procedure.ts
- packages/server/src/router.ts
- packages/server/test/router-meta.test.ts
- packages/server/test/router.test.ts
- www/docs/server/metadata.md
- www/sidebars.js
Implementation of route metadata #1731
> feat(server): route metadata

- examples/next-prisma-starter/src/server/context.ts
- examples/next-prisma-starter/src/server/routers/post.test.ts
https://github.com/trpc/trpc/discussions/1740#discussioncomment-2522190
> next-prisma-starter: show-case inner context creation

- examples/next-prisma-starter-websockets/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-starter/playwright/smoke.test.ts
- examples/next-prisma-todomvc/package.json
- packages/next/package.json
- packages/react/package.json
- packages/server/package.json
- yarn.lock
https://github.com/vercel/next.js/issues/36115
> lock `next` to `12.1.4`

- .github/workflows/examples-node12.yml
- .github/workflows/examples.yml
> use playwright container

- www/docusaurus.config.js
> fix algolia api key

- www/docs/nextjs/introduction.md
Minor change (fix) in the api router file title of the nextjs example that is less confusing for newbs (like me).
> Update introduction.md (for nextjs)

- www/docs/main/awesome-trpc.mdx
Added to awesome tRPC collection:
- Create tRPC App
- Prisma tRPC Generator
> add awesome trpc

- packages/client/src/internals/dataLoader.ts
- packages/client/src/links/httpBatchLink.ts
- packages/server/test/dataloader.test.ts
- packages/server/test/transformer.test.ts
Fork off #1858. Will comment inline
> `maxURLLength`

- www/docs/main/awesome-trpc.mdx
This adds Nuxt 3 module for TRPC. Thank you!
> docs: add trpc-nuxt to extensions & community add-ons list

- www/docs/main/awesome-trpc.mdx
https://github.com/sachinraja/trpc-swr
https://github.com/sachinraja/trpc-ultra
> add trpc-swr and trpc-ultra to awesome trpc

- packages/server/test/react.test.tsx
> fix flaky test

- examples/next-prisma-starter-websockets/src/pages/api/auth/[...nextauth].ts
> Fix typo in next-prisma-starter-websockets example

- packages/client/src/links/wsLink.ts
> fix ability to ponyfill `WebSocket`

- www/docs/client/header.md
- www/sidebars.js
Documentation update to customize headers in config based on this [#1408](https://github.com/trpc/trpc/discussions/1408) discussion.
> :memo: Adding custom header

- www/docs/main/awesome-trpc.mdx
- Adds `Build a Blog With tRPC, TypeScript, Next.js, Prisma & Zod` to the awesome-trpc page
> feat: add video to awesome-trpc

- README.md
twitter is a better place to reach out for direct messages
> changed sponsor link

- www/docs/reactjs/useInfiniteQuery.md
Hi, spotted this when reading the docs so thought I'd send a fix :)
> Fixes small typo in useInfiniteQuery docs

- .github/workflows/examples.yml
- examples/.interop/cloudflare-workers/package.json
- examples/cloudflare-workers/.gitignore
- examples/cloudflare-workers/README.md
- examples/cloudflare-workers/package.json
- examples/cloudflare-workers/src/client.ts
- examples/cloudflare-workers/src/index.ts
- examples/cloudflare-workers/src/router.ts
- examples/cloudflare-workers/tsconfig.json
- examples/cloudflare-workers/wrangler.toml
- packages/server/package.json
- yarn.lock
Resubmission of #2155
Resolves(partially) https://github.com/trpc/trpc/issues/2152
> chore: update cloudflare-workers example to v10

- .github/workflows/examples.yml
- examples/fastify-server/.gitignore
- examples/fastify-server/README.md
- examples/fastify-server/package.json
- examples/fastify-server/sandbox.config.json
- examples/fastify-server/src/client/client.ts
- examples/fastify-server/src/client/index.ts
- examples/fastify-server/src/client/polyfill.ts
- examples/fastify-server/src/config.ts
- examples/fastify-server/src/server/index.ts
- examples/fastify-server/src/server/router/context.ts
- examples/fastify-server/src/server/router/index.ts
- examples/fastify-server/src/server/router/routers/api.ts
- examples/fastify-server/src/server/router/routers/posts.ts
- examples/fastify-server/src/server/router/routers/sub.ts
- examples/fastify-server/src/server/router/trpc.ts
- examples/fastify-server/src/server/server.ts
- examples/fastify-server/tsconfig.json
Resubmission of #2156
Resolves(partially) #2152
> chore: update fastify-server example to v10

- www/docs/reactjs/introduction.md
- www/docs/reactjs/invalidateQueries.md
- www/docs/reactjs/ssg-helpers.md
- www/docs/reactjs/useInfiniteQuery.md
- www/docs/reactjs/useMutation.md
- www/docs/reactjs/useQuery.md
theres some unknowns here so will mark places where I'm not very confident what the api looks like
part of #2115
> migrate react docs to v10

- www/docs/server/authorization.md
- www/docs/server/aws-lambda.md
- www/docs/server/caching.md
- www/docs/server/context.md
- www/docs/server/data-transformers.md
- www/docs/server/error-formatting.md
- www/docs/server/error-handling.md
- www/docs/server/express.md
- www/docs/server/fastify.md
- www/docs/server/fetch.md
- www/docs/server/infer-types.md
- www/docs/server/merging-routers.md
- www/docs/server/metadata.md
- www/docs/server/middlewares.md
- www/docs/server/output-validation.md
- www/docs/server/router.md
> migrate server docs to v10

- www/docs/client/header.md
- www/docs/client/links.md
- www/docs/client/vanilla.md
> feat(www): migrates client docs to v10

- www/docs/main/awesome-trpc.mdx
- www/docs/main/introduction.mdx
- www/docusaurus.config.js
- www/src/pages/index.tsx
- hide out-of-date gif & videos
- add caution block on awesome-trpc
> hide out-of-date gif & videos

- www/docs/main/quickstart.mdx
Noticed the QuickStart was overlooked so updated that to v10
Feel free to make changes or let me know if there is anything you want me to change :)
Maybe add pnpm to installation-snippets?
> docs: update quickstart to be v10 compatible

- www/docs/main/awesome-trpc.mdx
Per @KATT 's requests on #2170 , I have pushed my branch to this repository.
> docs: minor spelling and grammar mistakes

- .tmp/v10-docs.md
- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/sidebars.js
> docs: start on migration doc

- www/docusaurus.config.js
- www/package.json
- www/yarn.lock
This was the text color on light mode which is unreadable so I changed the text color of the announcement bar to always be white which is readable on top of the blue background color.
> fix(www): readable announcement bar text color on both light/dark mode

- .github/workflows/main.yml
- package.json
- packages/next/package.json
- packages/react/package.json
- packages/server/jest.config.js
- packages/server/jest.setup.js
- yarn.lock
I don't **think** it's possible to make a mode that supports both 3 and 4 anymore; please prove me wrong.
Ref #2243
> lock `@trpc/react` to`react-query` `^3`

- www/docs/main/awesome-trpc.mdx
Added a Shopify app template with tRPC to awesome tRPC
> Added tRPC + Next.js Shopify app template

- www/docs/main/awesome-trpc.mdx
> Updates Cal.com link

- www/package.json
- www/src/components/Features.tsx
- www/src/components/GithubStarCountButton.tsx
- www/src/components/SectionTitle.tsx
- www/src/css/custom.css
- www/src/pages/index.tsx
- www/yarn.lock
needs https://github.com/trpc/trpc/pull/2285
> feat(www): implements new features section

- .tmp/v10-docs.md
> Spelling nit

- www/package.json
- www/src/components/GithubStarCountButton.tsx
- www/yarn.lock
@ixahmedxi tell me what you think. 
Feel free to take it over and find another library or do something else cool :)
> animate github numbers

- www/src/components/SectionTitle.tsx
- www/src/pages/index.tsx
@KATT whenever you're free just replace the dummy text :)
> feat(www): implements description section

- www/src/components/Features.tsx
- www/src/components/GithubStarCountButton.tsx
- www/src/components/SectionTitle.tsx
- www/src/pages/index.tsx
This pull request achieves the following:
- Better responsive design on smaller screens.
- Optional description prop on the `SectionTitle` component that allows that component to be used for the upcoming section which doesn't have a description.
- Reduce the number of words in the features section title for easier reading and more professional look.
> refactor(www): some small spacing adjustments & more flexible SectionTitle

- packages/react/src/createReactQueryHooksProxy.tsx
> treat `undefined` the same as omitting `input`

- www/docs/main/awesome-trpc.mdx
Add Nx tRPC Prisma example to the awesome trpc table
> Add nx trpc prisma example project to awesome trpc

- www/docusaurus.config.js
- www/src/components/GithubStarCountButton.tsx
- www/src/css/custom.css
- fix number cutoff
- fix default footer colors
> landing page: small css cleanup

- packages/react/src/createReactQueryHooksProxy.tsx
> specify parameter names for React hooks

- www/package.json
- www/src/components/TwitterWall/index.tsx
- www/src/components/TwitterWall/script.ts
- www/src/components/TwitterWall/tweets.ts
- www/src/components/TwitterWall/tweetsOld.ts
- www/src/css/custom.css
Implements tweaks suggested in #2322
Seems like there is some weird link behavior (children of link get underlined) set in some config so just gotta fix that
> feat(www): tweak twitterwall and link stuff

- www/docs/main/awesome-trpc.mdx
> added examples

- packages/server/test/useQuery.test.tsx
- packages/server/test/useSubscription.test.tsx
Delete double declaration of `useSubscription` test
> remove double declarations of `useSubscription` tests

- examples/next-prisma-starter-websockets/src/pages/api/auth/[...nextauth].ts
> fix wss example type error

- www/docs/server/error-formatting.md
It's fixes an mistake made in docs
changes the conditional from `BAD_USER_REQUEST` to `BAD_REQUEST`
> Fix error code conditional

- www/docs/main/awesome-trpc.mdx
> Added Remix adapter to awesome tRPC

- www/.gitignore
- www/package.json
- www/src/components/TwitterWall/script.ts
- www/src/components/TwitterWall/tweets.ts
- www/yarn.lock
> www(tweet wall): update script and pull latest

- www/docs/main/awesome-trpc.mdx
Some minor changes to our branding
> Update SST branding + website

- www/docs/client/cors.md
> fix: typo in code

- www/docs/main/awesome-trpc.mdx
> add trpc + fresh example to awesome list

- examples/.interop/express-server/package.json
- examples/express-minimal/package.json
- examples/express-server/package.json
Closes #2319
This fixes the nodemon scripts for windows. Tested on my Windows computer and it works.
> fix nodemon wait-on scripts

- www/docs/main/awesome-trpc.mdx
Added useTRPC Due 3 composables entry to awesome-trpc.mdx.
> docs: Added useTRPC() Vue 3 composable entry to awesome-trpc.mdx.

- packages/server/test/websockets.test.ts
> add retries to flaky test

- .github/labeler.yml
- .github/pull_request_template.md
- examples/.interop/next-prisma-starter-websockets/src/pages/api/auth/[...nextauth].ts
- package.json
- www/docs/client/cors.md
- www/docs/main/awesome-trpc.mdx
- www/docs/reactjs/ssg-helpers.md
- www/docs/server/error-formatting.md
- yarn.lock
> Next merge 2022 08 14

- www/docs/server/server-side-calls.md
- www/sidebars.js
Closes #2362 
Add documentations
> add Create caller docs

- .all-contributorsrc
- README.md
- www/docs/reactjs/useInfiniteQuery.md
- yarn.lock
> Next merge 2022 08 16

- packages/client/src/internals/dataLoader.ts
- packages/server/test/dataloader.test.ts
Repo test for https://github.com/trpc/trpc/issues/2008
Replacing #2484 
Closes #2008
> repo case for batch copy edge case

- www/src/css/custom.css
> fix markdown lists

- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/versioned_docs/version-9.x/server/error-formatting.md
> tweak migration page

- www/docs/main/awesome-trpc.mdx
Add a link to a simple example of tRPC v10-alpha (w/ Fetch Adapter) + SvelteKit + Tailwind CSS to the Awesome tRPC Collection doc.
> Add tRPC (w/ Fetch Adapter) + SvelteKit example

- packages/client/src/links/httpLink.ts
> Fix headers() throwing not rejecting httpLink request

- packages/client/src/links/httpLink.ts
- packages/server/test/httpLink.test.ts
- packages/server/test/regression/2506-headers-throwing.test.ts
> Fix `headers()` throwing not rejecting httpLink request 

- .all-contributorsrc
- README.md
- examples/.interop/next-minimal-starter/package.json
- examples/.interop/next-prisma-starter-websockets/package.json
- examples/.interop/next-prisma-starter/package.json
- examples/.interop/next-prisma-todomvc/package.json
- examples/.interop/standalone-server/package.json
- examples/next-minimal-starter/package.json
- examples/next-prisma-starter-sqlite/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/standalone-server/package.json
- packages/server/src/adapters/ws.ts
- packages/server/src/error/utils.ts
- www/docs/main/sponsors.md
- www/docs/nextjs/introduction.md
- www/src/components/sponsors/script.output.ts
- yarn.lock
> Next merge 2022 08 24

- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/docusaurus.config.js
- www/min-light-with-diff.json
- www/src/css/custom.css
#2112
- Adds missing parts of the migration guide as well as some general improvements.
> docs: migration guide

- www/docs/migration/migrate-from-v9-to-v10.mdx
Continues on updating the migration guide.
> migration guide

- www/src/css/custom.css
I've added a little bit of margin below the version badge to that it has some room to breathe!
> Style: margin below version badge.

- www/docs/main/awesome-trpc.mdx
- www/src/components/sponsors/script.push.ts
- www/versioned_docs/version-9.x/client/cors.md
- www/versioned_docs/version-9.x/further/rpc.md
- www/versioned_docs/version-9.x/main/awesome-trpc.mdx
- www/versioned_docs/version-9.x/main/quickstart.mdx
- www/versioned_docs/version-9.x/main/sponsors.md
- www/versioned_docs/version-9.x/nextjs/introduction.md
- www/versioned_docs/version-9.x/reactjs/ssg-helpers.md
- www/versioned_docs/version-9.x/reactjs/useInfiniteQuery.md
- www/versioned_docs/version-9.x/reactjs/useMutation.md
- www/versioned_docs/version-9.x/server/caching.md
Closes #
- Update v9 docs folder according to main
> update v9 docs according to `main`

- www/docs/migration/migrate-from-v9-to-v10.mdx
> Fix bad syntax in migration documentation

- packages/client/src/getFetch.ts
- packages/client/src/internals/fetchHelpers.ts
For more information about `globalThis`, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
Closes #2493
Expands on #2529
> fix: @trpc/client has undefined global #2529 (globalThis only)

- packages/server/src/core/router.ts
typo fixed.
```
availble -> available
```
> Fix typo in core/router.ts

- README.md
- www/src/pages/index.tsx
Closes #
Uses https://github.com/trpc/trpc-assets
> use assets cdn

- README.md
- packages/client/README.md
- packages/next/README.md
- packages/react/README.md
- packages/server/README.md
- www/docs/main/awesome-trpc.mdx
- www/src/pages/index.tsx
Closes #
Use https://github.com/trpc/trpc-assets
> Next merge 2022 08 28

- README.md
> fix readme gif

- packages/server/test/regression/issue-2540-undefined-mutation.test.ts
- add test for #2540
- Closes #2540
> add test for #2540

- packages/client/src/createTRPCClientProxy.ts
- packages/server/test/react/useSubscription.test.tsx
- packages/server/test/smoke.test.ts
Closes https://github.com/trpc/trpc/issues/2576.
Fix typing for `onData` function on the tRPC raw client.
> fix: v10 subscription `onData` typing (raw client)

- www/vercel.json
Closes #
- fix so we can link to `trpc.io/docs/v10`
> fix so we can link to `trpc.io/docs/v10`

- packages/client/src/links/internals/httpUtils.ts
- packages/server/src/http/resolveHTTPResponse.ts
Closes #2575 
> Delete remains of PATCH in project ✅
There was only two(2) references of patch in project
> In http links, make sure to return an error straight-away with information that you need to setup a wsLink in case it's called with a subscription
Was I just adding another statement with an error for validation right ?
Not sure if my implementation was right. Also I need to update some tests I think. Waiting on feedback to know if I'm on the right track
> Remove patch relics

- packages/client/README.md
- packages/next/README.md
- packages/react/README.md
- packages/server/README.md
- www/docs/main/quickstart.mdx
- www/docs/nextjs/introduction.md
- www/docs/reactjs/introduction.md
- www/docs/server/aws-lambda.md
- www/docs/server/express.md
- www/docs/server/fastify.md
- www/docs/server/fetch.md
- www/versioned_docs/version-9.x/nextjs/introduction.md
- www/versioned_docs/version-9.x/reactjs/introduction.md
Closes #
add `@next` on all v10 install docs
> add `@next` on all v10 install docs

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/procedure.ts
- packages/server/src/core/router.ts
- packages/server/test/initTRPC.test.ts
Progresses https://github.com/jlalmes/trpc-openapi/issues/73.
**Bugfix**
Procedures now infer correct `meta` typing. (see test)
> fix: procedure meta typing

- www/docs/server/express.md
Closes #
fix typo in the express adapter docs.
> fix typo in express adapter

- www/docs/server/authorization.md
- www/docs/server/caching.md
- www/docs/server/express.md
- www/docs/server/middlewares.md
Closes #
Fix typos in server docs
> Fix typos in server docs

- packages/client/src/internals/TRPCClient.ts
Closes #
- remove some weird typecasts
> remove some typecasts in client

- www/docs/server/fastify.md
- www/versioned_docs/version-9.x/server/fastify.md
Updating fastify documentation to remove deprecated listen argument.
> docs: update fastify docs to remove deprecated listen

- www/src/components/Features.tsx
> "prepare for trouble, make it double " (+1 if you know the reference) 
So a week ago I noticed that the features section was consisting of 3 features. I am convinced that tRPC has more that 3 features (advantages). What I really noticed was that the mentioned features contained multiple features in it self. For example auto type safety also contained auto completion. Light & snappy are two features. Batteries included was also merged with Framework agnostic. 
So this pull requests consist of 6 features spreading them out to go deeper in on the features of tRPC.  
Note: Please change it to your liking, as you guys are far more aware of the features of tRPC and which features you as tRPC want to highlight  
Note: Please check grammar ect. 
I no I did not make a  pre announcement that I …
> [www] features expanded

- www/package.json
- www/src/components/TwitterWall/index.tsx
- www/src/components/TwitterWall/script.output.ts
- www/src/components/TwitterWall/script.ts
- www/tailwind.config.js
- yarn.lock
- Refactors the twitter wall script to not do columns anymore.
- Fixes the inconsistent spacing between tweets we had previously.
- Pulls new tweets (fixes some bugs with not found avatars).
> feat(www): revamps twitter wall spacing to be more consistent

- www/src/pages/index.tsx
Unsure if this might fix the issues with local storage, or not, I don't know. Guessing here.
> fix: set local storage after mount 

- www/src/pages/index.tsx
> fix: localstorage version

- examples/express-trpc-shield/README.md
- examples/next-prisma-starter/src/utils/trpc.ts
- packages/client/src/internals/TRPCClient.ts
- www/docs/client/header.md
- www/docs/nextjs/ssr.md
- www/versioned_docs/version-9.x/nextjs/ssr.md
Closes #1811 
- Added client's headers forwarding example
- Removed "Caveats" in favor of "FAQ"
> docs: updating ssr docs

- README.md
Closes #
Added more info about how to start contributing to tRPC in README
> chore: added info about contributing in readme

- www/src/components/QuickIntro.tsx
- www/src/pages/index.tsx
Closes #
Seems to solve the ui bugs, at least when building and serving locally which wasn't the case before?
> separate section and section content?

- www/src/pages/index.tsx
Closes #
Use version from context instead of hacky localstorage
> fix(www): use version from context

- www/src/pages/index.tsx
I want to send some friends to:
- https://www-git-version-query-trpc.vercel.app/?v=10#try-it-out
- https://www-git-version-query-trpc.vercel.app/?v=9#try-it-out
> feat(www): query param to specify version

- www/package.json
- www/src/pages/index.tsx
- yarn.lock
- Update docusarus
- Don't think I need to reload anymore
> feat(www): update docusaurus deps, skip reload

- www/docs/server/metadata.md
Adds the missing opening bracket in metadata code example
> [docs] Add missing opening bracket

- www/docs/reactjs/introduction.md
- www/docs/reactjs/useMutation.md
- www/docs/reactjs/useQuery.md
- www/src/css/custom.css
Closes #
- Updated some react docs
> update some react docs

- www/versioned_docs/version-9.x/reactjs/introduction.md
Closes #
fixed a typo, where it was `'@tanstack/react-query'` instead of `'react-query'`
> Fix import typo introduction.md

- packages/client/src/createTRPCClient.ts
- packages/client/src/createTRPCClientProxy.ts
- packages/client/src/internals/TRPCClient.ts
- packages/server/test/interop/adapters/fetch.test.ts
- packages/server/test/interop/dataloader.test.ts
- packages/server/test/interop/headers.test.tsx
- packages/server/test/interop/inference.test.ts
- packages/server/test/interop/links.test.ts
- packages/server/test/react/interopBigCompiled.test.tsx
> refactor: remove client stuff

- www/docs/client/cors.md
- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/docs/nextjs/introduction.md
- www/docs/nextjs/ssr.md
- www/docs/reactjs/introduction.md
- www/docs/server/caching.md
Closes #2730
Update various documentation to use current API for client initialization.
Thanks for this great library! Please make any changes to this PR as desired. Thank you
> fix(www): update docs regarding client initialization

- examples/next-prisma-starter/package.json
- examples/next-prisma-starter/src/components/DefaultLayout.tsx
Devtools in the way for clicking
> fix `next-prisma-starter` e2e test

- www/docs/landing-intro/Step3.md
- www/src/components/Features.tsx
- www/src/components/Preview.tsx
- www/src/components/QuickIntro.tsx
- www/src/components/SectionTitle.tsx
- www/src/components/TwitterWall/index.tsx
- www/src/components/TwitterWall/script.output.ts
- www/src/css/custom.css
- www/src/pages/index.tsx
This commit brings the following changes:
- Updates preview to new v10 landscape
- Remove light mode preview
- Updates features descriptions to all fit 2 lines max.
- Updates section title to not have # as that in most cases it results in the title text looking not centered.
- Updates the styling of the alex quote.
- Updates the twitter feed.
- More minimalistic twitter wall design with no scrolling.
> refactor(www): more consistent and minimal design

- www/src/components/QuickIntro.tsx
Closes #
typo fix in QuickIntro.tsx
> chore: fix typo in QuickIntro

- packages/client/src/createTRPCClientProxy.ts
- packages/server/src/core/router.ts
- packages/server/src/shared/createProxy/index.ts
- packages/server/test/react/interopBasic.test.tsx
- packages/server/test/reservedWords.test.ts
Closes #2521
Add `ProxyPromiseGuard` type and defensive handling in TRPC Proxy Client.
> Fix subtle PromiseLike errors with `ProxyPromiseGuard`

- examples/.interop/next-minimal-starter-migration/package.json
- examples/.interop/next-minimal-starter-migration/src/pages/_app.tsx
- examples/.interop/next-minimal-starter/package.json
- examples/.interop/next-minimal-starter/src/pages/_app.tsx
- examples/.interop/next-prisma-starter-websockets/src/pages/_app.tsx
- examples/.interop/next-prisma-starter/src/pages/_app.tsx
- examples/.interop/next-prisma-todomvc/src/pages/_app.tsx
- examples/next-big-router/package.json
- examples/next-big-router/src/pages/_app.tsx
- examples/next-minimal-starter/package.json
- examples/next-minimal-starter/src/pages/_app.tsx
- examples/next-prisma-starter-sqlite/src/pages/_app.tsx
- examples/next-prisma-starter-websockets/src/pages/_app.tsx
- examples/next-prisma-starter/src/pages/_app.tsx
- examples/next-prisma-todomvc/src/pages/_app.tsx
- yarn.lock
> fix: use public AppType import and leverage generic

- .github/workflows/examples.yml
- .github/workflows/main.yml
- .github/workflows/subtree-next.yml
- .github/workflows/subtree.yml
Closes #
always checkout with fetch-depth 0
> adjust fetch-depth

- www/src/theme/DocVersionBanner/index.tsx
Closes #
Minor phrasing suggestion. :)
> More professional banner phrasing.

- packages/server/src/core/router.ts
- packages/server/test/react/interopBasic.test.tsx
- packages/server/test/regression/issue-2824-createCaller.test.ts
- Adds failing test
- Fixes issue
Closes #2824
> fix `createCaller` inference for interop

- www/docs/main/awesome-trpc.mdx
Closes #
Added `create-jd-app` github repo to the awesome-trpc collection markdown file.
> added create-jd-app to awesome-trpc

- packages/next/src/createTRPCNext.tsx
- packages/react/src/createTRPCReact.tsx
- packages/react/src/shared/proxy/utilsProxy.ts
- packages/react/src/ssg/ssgProxy.ts
- packages/server/src/shared/createProxy/index.ts
- packages/server/test/regression/issue-2842-createSSGHelpers-promise.test.ts
Fixes #2842
Better fix upcoming in #2845
> fix: proxies & promises

- www/docs/main/awesome-trpc.mdx
Add [astro-trpc](https://github.com/MoustaphaDev/astro-trpc) plugin and demo app
> docs(awesome-trpc): add `astro-trpc` package

- packages/server/src/core/middleware.ts
- packages/server/test/regression/issue-2856-middleware-infer.test.ts
> fix `next()` error inference

- packages/client/src/TRPCClientError.ts
> fix type `TRPCClientError` with `cause`

- packages/react/src/createTRPCReact.tsx
- packages/react/src/shared/hooks/createHooksInternal.tsx
- packages/react/src/shared/types.ts
- packages/server/test/react/overrides.test.tsx
> Custom overrides

- packages/server/src/core/index.ts
- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/procedure.ts
- packages/server/src/core/router.ts
- packages/server/src/deprecated/interop.ts
- packages/server/src/internals.ts
> reduce declaration size

- www/docs/migration/migrate-from-v9-to-v10.mdx
> Add codemod to migration doc.

- www/docs/server/infer-types.md
The types were inverted, this PR fixes it by inverting their names, same as later - first is input, then output
> fix(www): fix inversely named types

- packages/server/src/core/middleware.ts
- packages/server/test/meta.test.ts
- packages/server/test/middlewares.test.ts
Closes #
- Fix types of `meta` in middleware
> fix: meta is not necessarily defined

- packages/server/src/types.ts
- packages/server/test/___testHelpers.ts
- packages/server/test/input.test.ts
- packages/server/test/regression/issue-2824-createCaller.test.ts
> fix: multiple input parser with optional params

- www/docs/main/quickstart.mdx
- Move the description of the NPM command above the command itself.
- Added the word "For" to the @trpc/next installation description
Closes #2936 
Updates QuickStart documentation to make descriptions a bit clearer.
> Update quick start NPM command descriptions

- www/docusaurus.config.js
- www/src/css/custom.css
Closes #
- Updated footer links to v10 docs
- Fixed style conflict on mobile where navbar appeared behind the announcement bar
> www: minor homepage fixes

- www/docs/server/procedures.md
- www/vercel.json
> www: fix bad path

- .github/workflows/examples.yml
- examples/.test/ssg/.eslintrc
- examples/.test/ssg/README.md
- examples/.test/ssg/next-env.d.ts
- examples/.test/ssg/package.json
- examples/.test/ssg/playwright.config.ts
- examples/.test/ssg/src/pages/_app.tsx
- examples/.test/ssg/src/pages/api/trpc/[trpc].ts
- examples/.test/ssg/src/pages/index.tsx
- examples/.test/ssg/src/server/routers/_app.ts
- examples/.test/ssg/src/server/trpc.ts
- examples/.test/ssg/src/utils/trpc.ts
- examples/.test/ssg/test/smoke.test.ts
- examples/.test/ssg/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- www/docs/nextjs/ssg-helpers.md
> chore(examples): add ssg e2e example

- examples/trpc-chrome/README.md
- www/docs/main/awesome-trpc.mdx
Closes #
Added [`trpc-chrome`](https://github.com/jlalmes/trpc-chrome) to Awesome tRPC.
> Added `trpc-chrome` to Awesome tRPC.

- www/docs/server/caching.md
> fix: bad link

- examples/next-prisma-starter/src/pages/post/[id].tsx
- examples/next-prisma-starter/src/utils/trpc.ts
> use inference helpers in example project

- www/docs/reactjs/useInfiniteQuery.md
Closes #
- removed invalid `,` in `useInfiniteQuery.md` docs example
> docs: Update useInfiniteQuery.md

- www/docs/nextjs/introduction.md
> Fix _app import path

- www/docs/main/awesome-trpc.mdx
> add my solid projects to awesome-trpc collection

- www/docs/server/authorization.md
> fix: params are not defined

- www/docs/nextjs/ssg.md
> fix import in ssg docs

- packages/next/src/createTRPCNext.tsx
- packages/next/src/withTRPC.tsx
- packages/react-query/src/interop.ts
- packages/react-query/src/shared/index.ts
- www/docs/nextjs/introduction.md
let these options be defined in `createTRPCNext` too
ref: https://discord.com/channels/867764511159091230/1032031459852156938
> feat: add unstable_overrides to next

- packages/next/src/createTRPCNext.tsx
- packages/next/src/withTRPC.tsx
- www/docs/nextjs/introduction.md
> chrore: tweak `unstable_overrides` implementation

- packages/next/src/withTRPC.tsx
- packages/server/package.json
- packages/server/src/adapters/aws-lambda/index.ts
- packages/server/src/core/router.ts
- packages/server/src/deprecated/router.ts
- packages/server/src/http/getHTTPStatusCode.ts
- packages/server/src/http/index.ts
- packages/server/src/http/resolveHTTPResponse.ts
- packages/server/src/index.ts
- rollup.config.ts
- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/docs/server/error-handling.md
Closes https://discord.com/channels/867764511159091230/1032301198990135347
> feat: expose http status code helpers

- www/docs/client/header.md
- www/docs/further/further-reading.md
- www/docs/further/rpc.md
- www/docs/further/subscriptions.md
- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/docs/nextjs/introduction.md
- www/docs/nextjs/ssg.md
- www/docs/nextjs/ssr.md
- www/docs/reactjs/introduction.md
- www/docs/server/authorization.md
- www/docs/server/caching.md
- www/docs/server/server-side-calls.md
Closes #
This PR focuses on fixing multiple minor things that are in the v10 docs. Some of those were:
- General typos
- Updating/adding links to other parts of the docs
- Updating sentences that were not updated from v9 to v10
- Added explanation to why custom links don't work when using `.interop()` on v10
- Updated some code examples that were not updated from v9 to v10
> docs: general corrections

- www/docs/nextjs/introduction.md
> docs: nextjs fixed url.

- packages/client/README.md
> update client readme

- www/src/theme/DocVersionBanner/index.tsx
- mention v10 "RC" instead of "beta"
- only one line of text instead of two
> docs: Doc version banner for Release Candidate

- examples/next-prisma-todomvc/src/pages/[filter].tsx
- packages/react-query/src/shared/proxy/utilsProxy.ts
- packages/tests/server/___testHelpers.ts
- packages/tests/server/react/invalidateRouters.test.tsx
- packages/tests/server/react/useContext.test.tsx
- packages/tests/server/regression/issue-2942-useInfiniteQuery-setData.test.tsx
- www/docs/reactjs/useContext.mdx
- www/docs/reactjs/useInfiniteQuery.md
- closes #3122
- closes #3123 
Bug fixes
> fix types for invalidating routers

- www/docs/server/middlewares.md
> improve context swapping docs

- packages/tests/server/react/useContext.test.tsx
> fix: rm lint warning

- www/docs/reactjs/suspense.md
- www/docs/server/procedures.md
> improve some docs

- www/src/components/Features.tsx
- www/src/components/QuickIntro.tsx
- www/src/pages/index.tsx
Small cleanups and nitpicks for the home page!
> Touchups for home page.

- www/docs/main/introduction.mdx
Minor nitpicks and cleanup on the docs intro.
> Docs intro: Minor nitpicks and cleanup.

- packages/client/README.md
- packages/next/README.md
- packages/react-query/README.md
- packages/server/README.md
- www/docs/main/quickstart.mdx
- www/docs/nextjs/introduction.md
- www/docs/reactjs/introduction.md
- www/docs/server/adapter/aws-lambda.md
- www/docs/server/adapter/express.md
- www/docs/server/adapter/fastify.md
- www/docs/server/adapter/fetch.md
- www/src/css/custom.css
The quickstart had some good opportunities to bring more clarity for first time users of tRPC. Trying to make sure first time users feel good right from the start!
I did do a little bit of slimy hacking here to create styling for shiki in <Tabs />.
I also added a table to give some visual acuity to the commands that were initially listed out as plain text in the original version.
> More clarity for quickstart.

- www/docs/nextjs/ssr.md
Found an unused const in the nextjs ssr docs
> docs: remove unused const from example

- www/docs/nextjs/introduction.mdx
Title!
One major change that I will call out is that I've removed all of the authenticated procedure from the "hello world" procedure example.
The motivation for doing this is that folks are most likely reading this page as newcomers to tRPC (and maybe the combination of tRPC and Next.js). Because of this, we want to meet folks where they are and introduce one concept at a time. This page is introductory material so throwing in more things to figure out makes it harder to make the initial leap to fall in love with tRPC.
Once they see the simplicity and ease of use that tRPC brings, we can add more layers of complexity and features after that.
> Simplify and clean up Next.js usage page.

- www/docs/nextjs/introduction.mdx
- www/docs/reactjs/introduction.mdx
> Clarity for Usage with React page.

- packages/tests/server/react/useContext.test.tsx
Closes #
Not sure if this one is actually a problem as the test was working in the old format by virtue of it testing for the value added by the mutation that is called after render, but the `stableProxySpy` didn't seem to be doing anything by just being called passing in the `proxy` in the `useEffect ` with no dependencies. 
This PR changes it to be called on running of the queryFunction but I may be missing the intent where the `stableProxySpy` was just checking that the whole component hadn't some how been thrown away and recreated and so that's why the text from the mutation appeared?.... Just close if that's the case but I wouldn't mind a schooling on why this may occur in a test! 🙂 (Think this was you @sachinraja if you can give me the insight!)
> change invalidate test to call proxy spy

- www/docs/main/awesome-trpc.mdx
- www/src/components/ContentSlider.tsx
[Content Rules Everything Around Me](https://www.google.com/search?q=content+rules+everything+around+me&oq=content+rules+everything+around+me&aqs=chrome..69i57.5343j0j4&sourceid=chrome&ie=UTF-8)
Let's try to showcase efforts by the community a little better! I looked at this on mobile, tablet, and desktop sizes but let me know if I missed something.
> Content sliders.

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/shared/types.ts
- packages/tests/server/react/overrides.test.tsx
- www/docs/client/links/index.md
- www/docs/further/rpc.md
- www/docs/further/subscriptions.md
- www/docs/main/example-apps.mdx
- www/docs/nextjs/ssg-helpers.md
- www/docs/server/adapter/fetch.md
- www/docusaurus.config.js
- Adds `meta` to overrides `onSuccess`-callback
> add `meta` to overrides

- packages/tests/server/adapters/__router.ts
- packages/tests/server/adapters/express.test.tsx
- packages/tests/server/adapters/fastify.test.ts
- packages/tests/server/adapters/fetch.test.ts
- packages/tests/server/adapters/next.test.ts
Closes #3229 
Port of Express and fastify adapter tests with helper __router to v10.
> port: tests v10/adapters fetch express fastify

- packages/tests/server/react/__testHelpers.tsx
- packages/tests/server/react/dehydrate.test.tsx
- packages/tests/server/react/formatError.test.tsx
- packages/tests/server/react/infiniteQuery.test.tsx
- packages/tests/server/react/invalidateQueries.test.tsx
- packages/tests/server/react/prefetchQuery.test.tsx
- packages/tests/server/react/regression/issue-1645-setErrorStatusSSR.test.tsx
- packages/tests/server/react/setInfiniteQueryData.test.tsx
- packages/tests/server/react/setQueryData.test.tsx
#3229
This PR ports the react tests to v10
> port react tests to v10

- packages/tests/server/adapters/fastify.test.ts
- packages/tests/server/adapters/fetch.test.ts
We have some flakey tests that passed at first but sometimes fails.
This is one thing that I found in the original v9 tests that was missed in my v10 port.
Trying solve this step by step so we know the cause.
> test: attemps to fix flakey v10 tests

- packages/tests/server/adapters/awsLambda.test.tsx
Related #3229
Port tests for `adapters/awsLambda.test.tsx` to v10
> test: porting v10 for `adapters/awsLambda`

- www/docs/client/links/index.md
- www/sidebars.js
Closes #3230
this is `www` bug fix.
> fix(www): collapsible sidebar and breadcrumb cant go to new page (#3230)

- packages/tests/server/transformer.test.ts
Related #3229
Adding transformers tests for v10.
> test: port transformer tests for v10

- packages/tests/package.json
- packages/tests/server/websockets.test.ts
- pnpm-lock.yaml
Closes #
This PR ports `websockets.test.ts` to v10
> test: port websockets.test.ts to v10

- .github/workflows/examples-old-nodes.yml
- .github/workflows/examples.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/subtree.yml
> Make CI checks to run on all pull requests

- packages/next/README.md
- Update yarn install from `@tanstack-react-query` to `@tanstack/react-query`
> Update yarn install documentation

- examples/soa/client/index.ts
- examples/soa/package.json
- examples/soa/tsconfig.json
> docs: improve soa example

- examples/soa/package.json
- pnpm-lock.yaml
> fix soa example build

- www/src/pages/index.tsx
> chore: rm v9 iframe from homepage

- README.md
Moving @ixahmedxi to special shout-outs
> mv @ixahmedxi to special shout-outs

- www/docs/main/awesome-trpc.mdx
> Update awesome-trpc.mdx - Added Step CI

- www/docusaurus.config.js
- www/src/css/custom.css
> chore: fix navbar overflow

- www/src/components/sponsors/SponsorBubbles.jsx
Distributes bubbles a bit nicer by making them in up to 100 groups.
This is ugly code and there's prob a much nicer way of doing this
> www: make sponsor bubbles nicer

- www/docs/main/awesome-trpc.mdx
- www/docs/main/example-apps.mdx
> docs: rm v9 examples from awesome-trpc

- www/docs/nextjs/introduction.mdx
> docs: default to `ssr: false` in Next.js docs

- www/docs/main/awesome-trpc.mdx
Do these categories make sense? Feel free to tweak
https://www-git-awezom-trpc.vercel.app/awesome
> chore(www): split up awesome-trpc in sections

- examples/.interop/next-prisma-starter/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/next-prisma-websockets-starter/package.json
- package.json
- pnpm-lock.yaml
Closes(maybe??) #3348
- some examples have gotten removed and we overwrote invalid urls, might have been a cause?
- prisma and @prisma/client versions were mismatching
- updated to latest
idk, maybe it helps maybe it doesnt
> attempt on fixing prisma lint error

- www/src/components/TwitterWall/index.tsx
- www/src/components/TwitterWall/script.output.ts
- www/src/components/TwitterWall/script.ts
- Fetches all tweets and more metadata
- Displays full tweet
- Some hacks to prettify URLs etc
> feat(www): show full tweets

- www/src/components/TwitterWall/index.tsx
- `<blockquote>` etc
- fix some hover
> chore(www): twitter wall tweaks

- packages/tests/server/react/useQueries.test.tsx
Closes #
@sachinraja had concerns the inference might break when mapping so added a test just to confirm it works
> test: add map test for useQueries

- www/docusaurus.config.js
- www/og-image/.gitignore
- www/og-image/next.config.js
- www/og-image/pages/api/landing.tsx
- www/og-image/utils/env.js
> feat(www): adjust sizing, add stats

- www/src/utils/env.js
> fix(www): og-image url gets cached

- www/src/components/TwitterWall/index.tsx
- www/src/components/TwitterWall/script.output.ts
- fix cite being italic
- re-run script
> chore(www): tweak twitter wall

- packages/server/src/core/internals/config.ts
- packages/tests/server/regression/issue-3453-meta-interface.test.ts
Fix #3453 but better than #3459
> fix(server): use `object` instead of `{}`

- packages/client/src/createGenericTRPCClient.ts
- packages/client/src/internals/GenericTRPCClient.ts
- Don't default to `AnyRouter` except on the  (defaults as evil)
- Skip an unnecessary guard
> chore: fix types of `GenericTRPCClient`

- www/docs/main/awesome-trpc.mdx
Added Vite + Svelte + tRPC template repo to awesome collection
> Vite + Svelte + tRPC to awesome

- www/docs/main/awesome-trpc.mdx
I added a vue3 example project to the awesome list
- [ v] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [v ] If necessary, I have added documentation related to the changes made.
- [v ] I have added or updated the tests related to the changes made.
> vue3 example project

- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/shared/hooks/types.ts
- packages/tests/server/react/useQuery.test.tsx
- packages/tests/server/regression/issue-2996-defined-data.test.tsx
> chore: merge main -> next

- www/docs/main/awesome-trpc.mdx
Closes #
Add electron-trpc to awesome-trpc.mdx
> docs: add electron-trpc to awesome-trpc.mdx

- README.md
> docs: center vercel's logo in footer

- examples/lambda-api-gateway/package.json
- examples/lambda-api-gateway/src/client.ts
- examples/lambda-api-gateway/src/payloadFormatVersionClient.ts
- pnpm-lock.yaml
noticed when checking some stuff in #3186 that the lambda example is kinda outdated + missed a zod dependency... not sure how the build has succeeded here cause it had TypeErrors all over the place
> fix lambda example

- www/docs/server/middlewares.md
Closes #
- N/A I have added or updated the tests related to the changes made.
> docs: add missed import

- README.md
Closes #
- use my twitter + real name
> readme: update my info

- www/docs/server/context.md
> docs: fix typo in context section

- www/docs/client/links/index.md
Hi, I struggled for a while when I was trying to add a custom link. I found the solution, but I believe it should be included in the documentation.
Documentation enhancement
> docs: clarify creating custom links

- www/docs/main/quickstart.mdx
Closes #
removed zod import as it was not used in the example
> unused import in docs

- www/docs/main/awesome-trpc.mdx
Hello there :) If possible, I'd like to include my repository under the Awesome tRPC Collection page. It's a starting template inspired by T3, but using Nuxt.
Please let me know if I have included V3 in the correct section; I'll be happy to make any required changes.
> docs(awesome-collection): add V3 template to awesome

- www/docs/further/faq.mdx
- www/docs/server/procedures.md
- www/vercel.json
> docs: FAQ improvements

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/router.ts
- packages/server/src/subscription.ts
- packages/tests/server/callRouter.test.ts
> Next merge 2023 01 15

- www/docs/main/awesome-trpc.mdx
Add https://github.com/nehalist/hilde to open source projects using tRPC
> docs: add hilde to open source projects

- www/docs/main/awesome-trpc.mdx
> modify create-jd-app in awesome-trpc

- www/docs/main/awesome-trpc.mdx
Adds the "How tRPC really works" video to the videos section in Awesome tRPC
This feels like the most obvious place for the video to me, but let me know if you think there's a better place for it :)
- [n/a] If necessary, I have added documentation related to the changes made.
- [n/a] I have added or updated the tests related to the changes made.
> docs: add "How tRPC really works" video

- www/docs/main/awesome-trpc.mdx
Closes #
Added `Answer Overflow` GitHub repo to the awesome-trpc collection markdown file in the `Open-source projects using tRPC` table.
> docs: add answer overflow to awesome-trpc

- www/docs/main/awesome-trpc.mdx
Added https://github.com/maloguertin/msw-trpc to awesome tRPC
> docs: add msw-trpc to Awesome-trpc

- www/blog/2023-01-17-tinyrpc-client.mdx
A minor typo was fixed. 
A typo fix
"achive" -> "achieve"
- [x ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x ] If necessary, I have added documentation related to the changes made.
> A minor typo fix

- www/og-image/pages/api/_ref/dynamic-image.tsx
- www/og-image/pages/api/_ref/emoji.tsx
- www/og-image/pages/api/_ref/image-svg.tsx
- www/og-image/pages/api/_ref/language.tsx
- www/og-image/pages/api/_ref/param.tsx
- www/og-image/pages/api/_ref/static.tsx
- www/og-image/pages/api/_ref/tailwind.tsx
- www/og-image/pages/api/_ref/vercel.tsx
- www/og-image/pages/api/blog.tsx
- www/og-image/pages/api/docs.tsx
- www/og-image/pages/api/font.ts
- www/og-image/pages/api/landing.tsx
> refactor(og-image): replaces experimental-edge with edge

- packages/client/package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/server/package.json
- scripts/entrypoints.ts
Closes #3662
add `"./package.json": "./package.json"` to `"exports"`
> fix: export package.json

- packages/server/src/types.ts
Related #3710
Improve the error message a little bit.
> chore: update copy on error

- examples/.interop/next-prisma-starter/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/next-prisma-websockets-starter/package.json
- package.json
- pnpm-lock.yaml
> update prisma = fix recurring errors

- .vscode/settings.json
tired of all these folders in the file tree - just me?
> chore: hide entrypoint folders from file tree

- .github/workflows/subtree.yml
- examples/next-prisma-starter/.github/workflows/main.yml
- examples/next-prisma-websockets-starter/.github/workflows/main.yml
> Next merge 2023 02 06

- www/vercel.json
- Prio non-explicit redirect last
- Fix query invalidation redirect
> fix(www): fix bad redirect

- www/src/css/custom.css
- www/src/pages/index.tsx
This PR does the following changes:
- Decreases the font size of code blocks on mobile sizes to be more readable as that it would require less horizontal scroll on mobile that way.
> feat(www): makes codeblocks more readable on mobile

- packages/server/src/core/internals/mergeRouters.ts
accidentally merged the router configs too
> fix(mergeRouters): don't merge configs

- www/src/css/custom.css
This PR does the following changes:
Styles the algolia navbar search button to be more modern and fit the theme of the website better.
> feat(www): more modern design for the navbar search button

- www/docs/main/awesome-trpc.mdx
Remove deprecated `astro-trpc` package
> docs(awesome-trpc): remove deprecated `astro-trpc` package

- www/docs/server/router.md
> docs: fix some lower/uppercase stuff

- .github/workflows/subtree.yml
- packages/next/package.json
- pnpm-lock.yaml
Follow up #3800 for @trpc/next
> fix: add missing @types/react for next

- .github/workflows/main.yml
just until we find a fix for this
> chore: timeout hanging tests

- package.json
- pnpm-lock.yaml
> chore: override esbuild version

- examples/fastify-server/src/server/server.ts
- packages/tests/server/adapters/fastify.test.ts
- packages/tests/server/interop/adapters/fastify.test.ts
Closes #
- I don't like warnings in my console 🤣 
Ref: https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V4.md#deprecation-of-variadic-listen-signature
> chore: change to non-deprecated signature for fastify

- www/docs/main/awesome-trpc.mdx
Closes none
Hello tRPC team 👋 
This PR adds [`sidebase`](https://sidebase.io) to the list of projects and developer tools that use tRPC. sidebase is a Nuxt 3 stack with its own CLI to quickly help bootstrap a Nuxt 3 application. We recommend tRPC in our stack and think it would be amazing to offer a Nuxt solution on awsome tRPC!
> docs(awesome-trpc): added `sidebase` to awsome trpc

- README.md
- www/src/components/sponsors/script.output.ts
- www/src/components/sponsors/script.pull.ts
- www/src/components/sponsors/script.push.ts
- www/unversioned/_sponsors.mdx
> docs: add sponsor

- packages/server/src/transformer.ts
- www/docs/server/data-transformers.md
- www/versioned_docs/version-9.x/server/data-transformers.md
https://github.com/trpc/trpc/pull/3863#issuecomment-1445342955
- Clarify difference between "input" and "output" transformers
- Clarify section: https://www-git-katt-patch-2-trpc.vercel.app/docs/data-transformers#2-add-to-utilstrpcts
- Clarify interface https://www-git-katt-patch-2-trpc.vercel.app/docs/data-transformers#datatransformer-interface
> docs: clarify data transformer

- .github/workflows/subtree.yml
- examples/.interop/next-prisma-starter/.github/workflows/main.yml
- examples/next-prisma-starter/.github/workflows/main.yml
- examples/next-prisma-websockets-starter/.github/workflows/main.yml
Closes #3873 
Test run: 
- https://github.com/trpc/examples-next-prisma-websockets-starter/actions/runs/4277859720/jobs/7447039729
- https://github.com/trpc/examples-next-prisma-starter/actions/runs/4277859716/jobs/7447039722
> fix: db connection issues in subtree ci

- pnpm-lock.yaml
- www/package.json
- www/src/animations/popIn.ts
- www/src/components/QuickIntro.tsx
- www/src/components/SectionTitle.tsx
- www/src/components/TwitterWall/index.tsx
- www/src/pages/index.tsx
- www/tsconfig.json
https://share.cleanshot.com/2KdMF1cR
> feat(www): adds animations to landing page

- packages/client/src/getFetch.ts
cc @kamilogorek 
Closes #3906 
> fix(client): skip `.bind()` on `fetch` in order to fix Bun-support

- .eslintrc.js
- examples/cloudflare-workers/src/client.ts
- examples/express-minimal/src/client.ts
- examples/express-minimal/src/server.ts
- examples/express-server/src/client.ts
- examples/express-server/src/server.ts
- examples/fastify-server/src/client/index.ts
- examples/fastify-server/src/server/index.ts
- examples/fastify-server/src/server/server.ts
- examples/lambda-api-gateway/src/client.ts
- examples/lambda-api-gateway/src/payloadFormatVersionClient.ts
- examples/minimal-react/server/index.ts
- examples/minimal/client/index.ts
- examples/next-prisma-todomvc/src/pages/[filter].tsx
- examples/next-prisma-websockets-starter/src/pages/index.tsx
- examples/next-prisma-websockets-starter/src/server/prodServer.ts
- examples/standalone-server/src/client.ts
Enables typescript eslint's `no-floating-promises` rule and fixes the lint errors caused by the change.
> feat: enables no-floating-promises eslint rule

- www/docs/main/awesome-trpc.mdx
Added a new row in the table which is the project I made with trpc.
> docs: add Twitter Clone to awesome collection

- LICENSE
Just realised that the license still contained the placeholder year and owner fields so I updated that
> chore: updates LICENSE

- www/src/pages/index.tsx
> fix(www): laggy animations on mobile

- examples/next-app-router/package.json
- examples/next-app-router/src/app/api/trpc/[trpc]/route.ts
- examples/next-app-router/src/app/page.tsx
- examples/next-app-router/src/components/Greeting.tsx
- examples/next-app-router/src/trpc/client.ts
- pnpm-lock.yaml
> async/await + use in client

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/middleware.ts
> fix(server): createInputMiddleware next call type

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/internals/utils.ts
- packages/server/src/core/middleware.ts
- packages/server/src/core/procedure.ts
> fix: changes ProcedureParams to use one generic

- www/docs/main/awesome-trpc.mdx
This PR adds [ZenStack](https://github.com/zenstackhq/zenstack) to awesome tRPC.
> docs: add ZenStack to awesome-trpc

- www/docs/further/faq.mdx
Closes #
- [✅] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [✅] If necessary, I have added documentation related to the changes made.
- [✅] I have added or updated the tests related to the changes made.
> docs: add a tip in monorepo type safe

- README.md
> docs: add @Nick-Lucas

- www/docs/server/merging-routers.md
> docs: fix merging routers typo

- www/docs/reactjs/useQueries.md
Closes #
Simple fix of example code in useQueries documentation.
- [ &#10004;] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ &#10004;] If necessary, I have added documentation related to the changes made.
- [ &#10004;] I have added or updated the tests related to the changes made.
> docs: fixed useQueries example code

- README.md
​Because I already have enough power to add myself here ❤️
> docs: add @kamilogorek

- examples/next-prisma-starter/src/server/trpc.ts
- examples/next-prisma-starter/src/utils/transformer.ts
- examples/next-prisma-starter/src/utils/trpc.ts
https://twitter.com/michealjroberts/status/1636372240467111936
> docs: add transformer example

- www/docs/server/api-handler.md
> fix(docs): broken links in `api-handler.md`

- README.md
> docs: fix grammar in project leads section 🙃

- www/docs/client/introduction.md
Closes #
Updates the client intro to explicitly point people to the React Query integration
> docs: update client intro

- www/docs/main/example-apps.mdx
Closes https://github.com/trpc/trpc/issues/4083
Fixed one example that used `npx` twice instead of `pnpx`, remove one broke newline and added note regarding running the examples, as it might confuse some.
> docs(examples): Add note regarding pnpm and fix one broken example

- packages/client/package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/react-query/src/ssg/index.tsx
- turbo.json
> fix(react-query): fix path in deprecation comment

- www/docs/main/quickstart.mdx
> docs: fix quickstart stackblitz link

- packages/server/src/shared/internal/serialize.ts
- packages/tests/server/regression/issue-4049-stripped-undefined.test.tsx
> fix: undefined stripped from query result

- www/src/pages/index.tsx
> docs: fix sandboxes

- packages/tests/server/___testHelpers.ts
- packages/tests/showcase/tinyrpc.test.ts
> chore(tests): fix flaky tinyrpc test

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
> fix(react): use ref to ensure opts stay sync'd with subscription

- www/docusaurus.config.js
v10 is hardly new anymore
Closes #
> docs: remove v10 announcement bar

- www/docs/nextjs/setup.mdx
leftover from #4256 that shouldn’t have been merged
Closes #
> docs: rm unnecessary leftover

- www/docs/server/adapters/fastify.md
- www/docs/server/adapters/fetch.mdx
- www/docs/server/authorization.md
- www/docs/server/caching.md
- www/docs/server/error-formatting.md
- www/docs/server/error-handling.md
- www/docs/server/merging-routers.md
- www/docs/server/metadata.md
- www/docs/server/middlewares.md
- www/docs/server/output-validation.md
- www/docs/server/procedures.md
- www/docs/server/server-side-calls.md
links #4250 
I made change to the docs to replace any destructuring with a suitable replacement using the Issue guidelines which are
`Destructuring in function arguments is not ok`
`Destructuring in body is ok`
`Don't destruct a prop if it's only used once`
> docs: stop over-using destructuring (backend usage section)

- www/docs/client/headers.md
- www/docs/client/infer-types.md
- www/docs/further/rpc.md
- www/docs/further/subscriptions.md
- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/docs/nextjs/setup.mdx
- www/docs/nextjs/ssg.md
- www/docs/nextjs/ssr.md
- www/docs/reactjs/infer-types.md
- www/docs/reactjs/useInfiniteQuery.md
- www/docs/reactjs/useMutation.md
- www/docs/reactjs/useQuery.md
Closes #4250 
I made change to the docs to replace any destructuring with a suitable replacement using the Issue guidelines which are
`Destructuring in function arguments is not ok`
`Destructuring in body is ok`
`Don't destruct a prop if it's only used once`
> docs: stop over-using destructuring (remaining)

- .github/renovate.json
https://docs.renovatebot.com/configuration-options/#rollbackprs
> chore: skip rollback PRs

- package.json
> fix: not erroring when pnpm v7 is used in project

- .github/workflows/main.yml
- packages/tests/server/interop/websockets.test.ts
- packages/tests/server/websockets.test.ts
Better safe than sorry, and we don't have a single job that runs on the latest Node currently.
> ci: Add Node v20 to main workflow matrix

- packages/tests/server/errorFormatting.test.ts
closes #4302
cc @ollyde - is this not what you're looking for?
> chore: add custom error sub-class example

- www/docs/client/infer-types.md
Doc changes only. Clarify explanation of RouterInput and RouterOutput when infering types.
https://github.com/trpc/trpc/blob/ef1de2aa20b669f5eb4408e0d7d8da3eb2773e07/www/docs/client/infer-types.md?plain=1#L58
> Docs: Clarify explanation of RouterInput and RouterOutput types

- www/docs/nextjs/ssg.md
Closes #
Fix ssg.md "getStaticPaths" fallback blocking documentation URL
> Update ssg.md "getStaticPaths" fallback blocking docs URL

- www/docs/community/awesome-trpc.mdx
Updates awesome-trpc.mdx - add community repo that uses tRPC
> Add saleor/apps to community projects

- packages/client/src/links/loggerLink.ts
> fix: `loggerLink` backwards compat with es2015

- .github/workflows/subtree.yml
> chore: subtree fix

- www/docs/reactjs/introduction.mdx
A simple typo fix in this documentation snippet.
> docs: fix typo in react query integration snippet

- .github/workflows/pr-naming.yml
> chore: check PR request naming on forks

- packages/next/package.json
whoopsie - did manypkg or renovate prank us 🤔
> fix(next): unlock next peerdep

- www/docs/further/faq.mdx
- www/docusaurus.config.js
- add faq in footer
- tweak copy
> docs: add FAQ in the footer

- www/docs/main/getting-started.mdx
- www/docs/main/videos-and-community-resources.mdx
We could probably pick a favourite and only have 1 or 2
I liked this one very much
> docs: add "tRPC in 5 mins" by Matt Pocock

- packages/react-query/src/createTRPCReact.tsx
- packages/tests/server/react/__reactHelpers.tsx
- packages/tests/server/react/formData.test.tsx
- www/docs/client/react/suspense.md
Docs are wrong right now as I'm a bit blocked on releasing, will revert this revert later
> Revert "feat(`react-query` + `next`): remove suspense feature flag"

- www/docs/server/merging-routers.md
Add a little note on how to access namespaced procedures.
This is not documented anywhere and I had to search all over sample projects just to know how to access namespaced procedures.
Closes #
> docs: update merging-routers.md

- packages/react-query/src/createTRPCReact.tsx
- packages/tests/server/react/__reactHelpers.tsx
- packages/tests/server/react/formData.test.tsx
- www/docs/client/react/suspense.md
> feat(`react-query` + `next`): remove suspense feature flag

- www/docs/community/awesome-trpc.mdx
- www/docs/main/example-apps.mdx
Hi, I just wanted to contribute an example app which has separate backend and frontend repositories.
> docs: Add example app - Separate BE/FE repos

- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/shared/hooks/types.ts
- packages/react-query/src/shared/polymorphism/queryLike.ts
- packages/react-query/src/utils/inferReactQueryProcedure.ts
- packages/tests/server/react/regression/issue-4519-invalid-select-as-transform.test.tsx
- packages/tests/server/regression/issue-2996-defined-data.test.tsx
> fix(`react-query`): fix select as transform

- www/docs/client/react/useInfiniteQuery.md
Adds a missing async keyword to the docs.
> docs: add missing async keyword

- www/docs/client/links/overview.md
Adding a link to "Disable batching for certain requests" as an example in the links context docs
> Add example use case to links context docs

- www/docs/community/awesome-trpc.mdx
I originally made this PR a while ago (#2370), but seems like it has been removed.
Since the example code was using tRPC v10 alpha which is obsolete now, I updated the deps and fixed codes accordingly to use tRPC v10.34.0 and fresh 1.2.0.
Hope you might accept this again.
> docs: add deno fresh example

- CONTRIBUTING.md
Start the contribution bootstrap with **pnpm tests** so you don't have problems with the **codegen**.
@kamilogorek helped me with this **test fixtures**. It was something related to **turbo.json**.
> chore: update contributing.md for test fixtures

- www/docs/community/awesome-trpc.mdx
Added Rao Pics to awesome tRPC project.
Closes #
> docs: Update awesome-trpc.mdx

- package.json
- packages/client/src/createTRPCUntypedClient.ts
- packages/react-query/src/server/ssgProxy.ts
- packages/tests/server/react/ssgExternal.test.ts
- pnpm-lock.yaml
- www/src/components/Preview.tsx
- www/src/css/custom.css
- www/src/utils/handleSmoothScrollToSection.ts
> chore: next merge 2023 07 27

- examples/next-prisma-starter/README.md
- examples/next-prisma-starter/package.json
using node14 led to a weird error, so hopefully this saves somebody else some time 🙌🏻 
- bumps the version in the readme
- adds a node version requirement to the package.json
> chore(example): increase minimum node version to 16.8

- packages/tests/server/errorFormatting.test.ts
Closes #
add test for https://github.com/trpc/trpc/discussions/4705#discussioncomment-6699671 / https://trpc.io/docs/server/error-formatting
> chore: add test of zod errors according to docs

- examples/express-minimal/src/client.ts
Cleaned up the code to make it faultless using try-catch block in the examples folder -> express minimal -> client.ts.
- [ ✅] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ✅] If necessary, I have added documentation related to the changes made.
- [ ✅] I have added or updated the tests related to the changes made.
> Updated the example using try-catch

- README.md
- packages/client/README.md
- packages/next/README.md
- packages/react-query/README.md
- packages/server/README.md
- www/docs/client/nextjs/setup.mdx
- www/docs/client/react/setup.mdx
- www/docs/client/vanilla/setup.mdx
- www/docs/main/example-apps.mdx
- www/docs/main/quickstart.mdx
- www/docs/server/adapters/fetch.mdx
Add instructions for `bun` and `bunx`
> docs: add bun and bunx instructions

- README.md
- packages/client/README.md
- packages/next/README.md
- packages/react-query/README.md
- packages/server/README.md
- www/docs/client/nextjs/setup.mdx
- www/docs/client/react/setup.mdx
- www/docs/client/vanilla/setup.mdx
- www/docs/main/example-apps.mdx
- www/docs/main/quickstart.mdx
- www/docs/server/adapters/fetch.mdx
- www/docusaurus.config.js
- www/vercel.json
> chore: next merge 2023 08 17

- www/docs/client/nextjs/server-side-helpers.md
Fixes typo of `SuperJSON` which is imported as `superjson`
> Fix typo in docs (server side helpers)

- www/docs/community/awesome-trpc.mdx
Adds [trpc-rtk-query](https://github.com/otahontas/trpc-rtk-query) to the list of library adapters.
> Add trpc-rtk-query

- www/docs/community/awesome-trpc.mdx
Updated Prisma editor link in "Open-source projects using tRPC" list
> update prisma editor link

- README.md
It's docs update, I add pnpm command, to help easier to copy paste for pnpm user.
> docs(README.md): add pnpm in quickstart

- .github/workflows/examples.yml
- examples/bun/README.md
- examples/bun/package.json
- examples/bun/src/client.ts
- examples/bun/src/index.ts
- examples/bun/src/router.ts
- examples/bun/tsconfig.json
- pnpm-lock.yaml
Follows up https://github.com/trpc/trpc/pull/4716
> chore: add bun to ci

- www/docs/community/awesome-trpc.mdx
Adds [trpc-token-refresh-link](https://github.com/larskarbo/trpc-token-refresh-link) to the list of library adapters
> Docs: Add trpc-token-refresh-link to Awesome tRPC Collection

- www/src/components/ConceptsChart.tsx
> Add link indicator to "Subscriptions" in "Concepts"

- package.json
- packages/client/package.json
- packages/client/tsconfig.watch.json
- packages/react-query/package.json
- packages/react-query/tsconfig.watch.json
- packages/server/package.json
- packages/server/tsconfig.watch.json
- turbo.json
> chore: fix `ts-watch` script

- package.json
- packages/client/package.json
- packages/client/tsconfig.watch.json
- packages/react-query/package.json
- packages/react-query/tsconfig.watch.json
- packages/server/package.json
- packages/server/tsconfig.watch.json
- turbo.json
> Next merge 2023 09 21

- README.md
- packages/tests/package.json
- pnpm-lock.yaml
- www/docs/client/links/httpBatchStreamLink.md
- www/package.json
- www/src/components/TwitterWall/script.output.ts
- www/src/components/sponsors/script.output.ts
- www/src/components/sponsors/script.pull.ts
- www/src/components/sponsors/script.push.ts
- www/unversioned/_sponsors.mdx
> Next merge 2023 09 26

- examples/.test/big-router-declaration/scripts/codegen-base.ts
- examples/.test/big-router-declaration/scripts/codegen.ts
- examples/.test/big-router-declaration/src/server/context.ts
- examples/.test/big-router-declaration/src/server/trpc.ts
Make the big router more complex
> chore: make big router more complex

- www/docs/server/adapters/standalone.md
> docs: Typo fix in standalone.md

- www/docs/main/concepts.mdx
- www/docs/server/adapters/standalone.md
> Correct some deviations from the meaning of docs

- examples/.experimental/next-app-dir/package.json
- examples/.experimental/next-formdata/package.json
- examples/.test/big-router-declaration/package.json
- examples/.test/diagnostics-big-router/package.json
- examples/.test/ssg-infinite-serialization/package.json
- examples/.test/ssg/package.json
- examples/minimal-react/client/package.json
- examples/next-big-router/package.json
- examples/next-edge-runtime/package.json
- examples/next-minimal-starter/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/next-prisma-websockets-starter/package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/server/package.json
- packages/tests/package.json
- pnpm-lock.yaml
https://twitter.com/TkDodo/status/1714262102305632643
> chore: bump to `@tanstack/react-query@5.0.0`

- .github/workflows/release.yml
probably don't wanna release on every commit in PRs
> fix: don't run release on every commit

- .wip/changes.md
- packages/client/src/links/wsLink.ts
- packages/tests/server/websockets.test.ts
> feat(client): allow for promises in wss url

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/middleware.ts
- packages/server/src/shared/internal/serialize.ts
- packages/tests/server/regression/issue-4947-merged-middleware-inputs.test.ts
- packages/tests/server/regression/issue-4985-serialize-type.test.ts
> Next merge 2023 11 02  14 55

- packages/next/README.md
- packages/react-query/README.md
v10 is coupled with RQ 4
closes #5014
> docs: fix install docs

- www/docs/server/adapters/standalone.md
> docs: correct example code

- www/docs/client/nextjs/server-side-helpers.md
Remove the line that imports prisma - it is not used anywhere in the example or page.
> docs: remove unnecessary import

- pnpm-lock.yaml
Ref #4752
1. `pnpm up zod -r`
2. revert all `package.json`s
3. `pnpm install`
Idk if there's an easier way to just bump the lockfile
> chore: bump zod

- www/docs/migration/migrate-from-v9-to-v10.mdx
> docs: fix broken twoslash

- packages/server/src/core/initTRPC.ts
- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/internals/utils.ts
- packages/server/src/core/middleware.ts
- packages/server/src/types.ts
- packages/tests/server/adapters/fastify.test.ts
Closes #
cleanup some types and deprecate old things
> fix: cleanup some types and deprecate old things

- README.md
- www/docs/main/introduction.mdx
Closes #
Thought this looked cool.
> docs: add npm download badge

- packages/server/src/types.ts
> chore: rm internal deprecated types

- packages/tests/server/regression/issue-5037-context-inference.test.ts
Adds a new test to the existing #5037 suite to cover a new use case
> chore(server): augment existing test with a new use case

- .github/workflows/lint.yml
Should fix e.g. https://github.com/trpc/trpc/actions/runs/6956656556/job/18927952994?pr=5084
> chore: fix the autofixer on forks

- package.json
- packages/tests/server/adapters/fastify.test.ts
Closes #
Fastify is flaky & I don't have the energy to figure out why.
I don't like retry due to false-positives in some cases, but having 1 retry is usually fine
> chore: add vitest test retry 

- packages/client/src/links/wsLink.ts
- www/docs/client/links/wsLink.md
> docs: update `wsLink` docs

- packages/server/src/adapters/fetch/fetchRequestHandler.ts
- packages/tests/server/adapters/fetch.test.ts
- Closes #5089 (hopefully? I need a reproduction)
- Closes https://github.com/honojs/middleware/issues/274
Add method to trim surrounding slashes to try to squash any issues with ending or staring slashes etc
> fix(server): fix fetch adapter with custom endpoint

- package.json
- pnpm-lock.yaml
> Next merge 2023 11 24  13 46

- pnpm-lock.yaml
Closes #5154
- bumps tsx
- unsure why this fixes anything since I can't repro locally
> chore: bump tsx

- packages/next/src/app-dir/links/nextHttp.ts
> Next merge 2023 12 17  20 11

- packages/react-query/src/shared/polymorphism/mutationLike.ts
- packages/react-query/src/shared/polymorphism/queryLike.ts
- packages/tests/server/react/polymorphism.test.tsx
* fix(react-query): fix polymorphism
* chore(tests): no destructuring, no unnecessary types, nicer export button
> fix(react-query): cleanup polymorphism

- .github/workflows/release.yml
Not fully automatic releases, but at least there's a `@canary` tag people can use now :)
> chore: add automatic release under the `canary` tag

- .github/workflows/release-next.yml
- package.json
- packages/client/src/TRPCClientError.ts
- packages/server/src/adapters/node-http/content-type/form-data/streamSlice.ts
- packages/server/src/error/TRPCError.ts
- packages/server/src/shared/getCauseFromUnknown.ts
- packages/server/src/shared/index.ts
- pnpm-lock.yaml
- tsconfig.build.json
> Next merge 2023 12 23  00 16

- .github/workflows/lock-issues.yml
GitHub notifications are too noisy.
> chore: lock issues and PR discussions straight away

- .github/workflows/release.yml
- packages/next/package.json
- packages/next/src/withTRPC.tsx
- packages/tests/server/react/withTRPC.test.tsx
> Next merge 2023 12 25  00 35

- .github/workflows/release-next.yml
- .github/workflows/release.yml
- .github/workflows/subtree.yml
- README.md
- examples/next-prisma-starter/.github/workflows/main.yml
- examples/next-prisma-starter/README.md
- examples/next-prisma-starter/next.config.js
- examples/next-prisma-starter/package.json
- examples/next-prisma-starter/playwright.config.ts
- pnpm-lock.yaml
- www/src/components/sponsors/script.output.ts
- www/unversioned/_sponsors.mdx
> Next merge 2023 12 25  15 45

- .github/workflows/release-next.yml
- .github/workflows/release.yml
- package.json
> Next merge 2023 12 27  01 22

- package.json
This pr creates a new `clean-dev` script that does all of the scripts that you normally need to run when you switch between branches. instead of doing like `p clean && p i && p build && p dev` manually
> Creates clean-dev script in root package.json file

- packages/client/entrypoints.script.ts
- packages/client/turbo.json
- packages/next/entrypoints.script.ts
- packages/next/turbo.json
- packages/react-query/entrypoints.script.ts
- packages/react-query/turbo.json
- packages/server/entrypoints.script.ts
- packages/server/turbo.json
- scripts/entrypoints.ts
- turbo.json
ensures turbo cache outputs are updated as new entrypoints are added
> fix: cache artifcats in entrypoints generation script

- packages/tests/server/adapters/fastify.test.ts
- www/docs/server/adapters/fastify.md
Closes #5126
Gave it a minute or two to actually fix it but everything looks correct to me. Satisfied for a docs callout.
> docs: add callout about types when using Fastify plugin

- packages/tests/package.json
- packages/tests/server/adapters/fastify.test.ts
- packages/tests/server/validators.test.ts
- pnpm-lock.yaml
- www/docs/community/awesome-trpc.mdx
- www/docs/server/adapters/fastify.md
- www/package.json
> Next merge 2024 01 04  21 55

- packages/next/README.md
- packages/react-query/README.md
- www/docs/client/nextjs/setup.mdx
- www/docs/client/react/setup.mdx
> docs: update install snippets for `@tanstack/react-query`

- README.md
- packages/core/src/error/TRPCError.ts
- packages/next/README.md
- packages/react-query/README.md
- www/docs/client/nextjs/setup.mdx
- www/docs/client/react/setup.mdx
> Next merge 2024 01 08  20 33

- pnpm-lock.yaml
- www/package.json
> chore: next merge 2024 01 10  18 12

- packages/core/src/index.ts
- packages/react-query/src/shared/polymorphism/queryLike.ts
- packages/server/src/index.ts
Changes required to next, to migrate too v11 in my company
> V11 Nick fixes

- packages/server/src/index.ts
Follow-up of  #5300 by @Nick-Lucas
> fix(server): deprecate `AnyMiddlewareFunction`

- examples/.test/internal-types-export/src/server.ts
- packages/core/src/procedureBuilder.ts
- packages/tests/server/regression/issue-5297-description-key-on-input-turns-to-void.test.ts
> fix(server): fix last UnsetMarker and update broken example

- .github/workflows/diagnostics.yml
- .github/workflows/diagnosticsCompare.ts
Fix diagnostics following #5323
> chore: fix diagnostics

- www/versioned_docs/version-10.x/main/quickstart.mdx
> docs: Update quickstart.mdx

- packages/next/package.json
- pnpm-lock.yaml
don't need some of these when using the app-dir stuff only
> chore(next): mark some peerDeps as optional

- .github/workflows/lint.yml
- examples/minimal-react/client/src/main.tsx
Auto fixing lint issues failed in #5356, hopefully this fixes it
> chore: fix the autofixing

- .github/workflows/lint.yml
- .github/workflows/main.yml
- examples/minimal-react/client/src/main.tsx
No need to parallelize lint jobs, might as well just run autofixing
> chore: combine lint jobs

- README.md
> $ mv core/kamilogorek /dev/null

- www/docs/community/awesome-trpc.mdx
update docs, add Tianji link in awesome trpc list which using trpc
> docs: add Tianji link in awesome trpc

- www/docs/migration/migrate-from-v10-to-v11.mdx
Closes #
I didn't open a issue because it's very trivial.
Just a doc typo
> docs: minor typo

- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/next-prisma-websockets-starter/package.json
- package.json
- pnpm-lock.yaml
> chore: bump prisma deps

- www/docs/community/awesome-trpc.mdx
Closes #
Add  my package : tRPC-Remix-Call to awesome-trpc list.
> Add tRPC-Remix-Call to awesome-trpc

- packages/client/package.json
- packages/client/rollup.config.ts
- packages/client/turbo.json
- www/docs/migration/migrate-from-v10-to-v11.mdx
Closes #
Re-adds `@trpc/client/httpLink` etc 
It has no maintenance burden for us but makes migration to v11 easier
> feat(client): re-add `@trpc/client/httpLink` etc

- www/docs/migration/migrate-from-v10-to-v11.mdx
Closes #
Cleans up migration guide a bit
> chore: cleanup migration guide

- packages/react-query/src/internals/getClientArgs.ts
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/tests/server/react/__testHelpers.tsx
- packages/tests/server/react/useInfiniteQuery.test.tsx
Closes #5412
Fix infinite queries invalidation
> fix(react-query): infinite queries invalidation

- www/docs/client/links/httpBatchLink.md
> chore: remove broken link

- examples/deno-deploy/README.md
deno deploy now supports npm: specifiers
Closes #
> chore(docs): remove outdated deno deploy note

- .eslintrc.js
- README.md
- packages/server/src/@trpc/server/http.ts
- packages/server/src/adapters/fetch/fetchRequestHandler.ts
- packages/server/src/adapters/standalone.ts
- packages/server/src/unstable-core-do-not-import/http/index.ts
- packages/server/src/unstable-core-do-not-import/http/toURL.ts
> Next merge 2024 02 03  12 53

- www/docs/community/awesome-trpc.mdx
update docs, add workplacify in awesome trpc list which using trpc
Btw. on top of this: Many thanks for this awesome library! It makes me so much more productive!
> docs: add Workplacify in awesome trpc

- packages/server/src/unstable-core-do-not-import/procedureBuilder.ts
Closes #
Got confused staring at our own code for `ProcedureResolver` so added a comment
> chore(server): rename variable and add comment

- www/docs/main/example-apps.mdx
Closes #
This PR updates example app label and link (separate backend and frontend repositories).
> docs: Update example app label and link

- pnpm-lock.yaml
- www/docusaurus.config.js
- www/package.json
- www/src/components/Button.tsx
- www/src/pages/pricing.tsx
- www/vercel.json
- www/versioned_docs/version-10.x/server/validators.md
Closes #
https://www-git-02-09-pro-trpc.vercel.app/pricing
> chore(www): add pricing

- www/src/pages/pricing.tsx
> chore: add open graph image

- www/docs/community/awesome-trpc.mdx
update docs, add dotfyle in awesome trpc which is using trpc
It's been a great experience using trpc and it's made me very productive!
> docs: add Dotfyle to awesome trpc

- .github/workflows/release-next.yml
- package.json
- pnpm-lock.yaml
> chore: bump lerna

- examples/minimal/src/client/index.ts
- examples/minimal/src/server/index.ts
Tweak the minimal example a bit
> chore: tweak the minimal example a bit

- www/docs/server/procedures.md
Closes #
Updates reusable procedure docs with a bit more of a real-world example
https://www-git-02-18-tweak-docs-trpc.vercel.app/docs/server/procedures#reusable-base-procedures
> docs: update reusable procedure docs

- www/docs/client/react/useInfiniteQuery.md
Fix the wrong zod direction schema in useInfiniteQuery doc, added in https://github.com/trpc/trpc/pull/5516.
> docs: fix wrong zod direction schema example

- www/docs/server/validators.md
Updates `www/docs/server/validators.md` with example of using `@robolex/sure`
Add basic snapshot test in `packages/tests/server/validators.test.ts`
> Add example of validation using @robolex/sure

- www/docs/client/react/disabling-queries.md
> docs: fix wrong import in docs

- packages/server/src/unstable-core-do-not-import/http/resolveHTTPResponse.ts
- packages/server/src/unstable-core-do-not-import/http/types.ts
- packages/tests/server/___testHelpers.ts
- packages/tests/server/batching.test.ts
- packages/tests/server/index.test.ts
- packages/tests/server/links.test.ts
- packages/tests/server/react/__testHelpers.tsx
- packages/tests/server/regression/issue-4217-throw-non-errors.test.ts
- www/docs/client/links/httpBatchLink.md
> docs: update batching toggle docs

- .github/workflows/release-tmp.yml
- packages/client/src/internals/types.ts
- packages/client/src/links/internals/parseJSONStream.ts
- packages/server/src/adapters/node-http/content-type/form-data/fileUploadHandler.ts
- packages/server/src/adapters/ws.ts
- packages/server/src/unstable-core-do-not-import/initTRPC.ts
> fix(server + client): skip referencing `NodeJS.*`

- .github/workflows/release-next.yml
Background: https://twitter.com/alexdotjs/status/1768238915536777705
> chore: make dependabot understand bumps in `next`-tag

- .github/workflows/release-next.yml
Closes #5599
We're not planning any more breaking changes, we got some conflicting issues with semver in #5599 / #5578 & tRPC@next is used in prod by many companies.
> feat: release release candidate

- .github/workflows/release-tmp.yml
- package.json
- packages/server/src/unstable-core-do-not-import/createProxy.ts
- packages/server/src/unstable-core-do-not-import/initTRPC.test.ts
- packages/server/src/unstable-core-do-not-import/initTRPC.ts
- packages/server/src/unstable-core-do-not-import/procedure.ts
- packages/server/src/unstable-core-do-not-import/procedureBuilder.ts
- packages/server/src/unstable-core-do-not-import/utils.ts
Closes https://github.com/t3-oss/create-t3-app/issues/1814
Closes https://github.com/t3-oss/create-t3-app/issues/1813
Probably something downstream in Turbo that causes an issue, unsure what the issue is, but this fixes it.
> patch(server): fix `dev --turbo`

- www/docs/community/awesome-trpc.mdx
- Added Ethereum decentralized application example with end-to-end typesafe APIs for smart contract interaction.
- Example built with tRPC, Next.js, Ethers, Hardhat, Solidity, Zod and Chakra UI.
> docs: Add Ethereum DApp example

- .github/workflows/main.yml
> chore: make sure test job runs on pushes

- vitest.config.ts
> chore: fix codecov

- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/next-prisma-websockets-starter/package.json
- package.json
- pnpm-lock.yaml
- vitest.config.ts
might fix next-prisma-starter failing often
> chore: bump prisma

- packages/server/src/@trpc/server/index.ts
> feat: export procedure types

- packages/server/src/@trpc/server/index.ts
- packages/server/src/adapters/fetch/types.ts
- packages/server/src/adapters/node-http/types.ts
- packages/server/src/unstable-core-do-not-import/http/resolveResponse.ts
- packages/server/src/unstable-core-do-not-import/rootConfig.ts
> 04 26 resolve response and multi happy ts

- README.md
- www/docs/main/introduction.mdx
> chore: fix codecov badge

- .github/workflows/main.yml
https://github.com/codecov/codecov-action/issues/1390
> chore: fix codecov for forks

- packages/client/src/links/internals/httpUtils.ts
- packages/server/src/unstable-core-do-not-import/http/contentType.ts
- packages/server/src/unstable-core-do-not-import/http/resolveResponse.ts
- packages/server/src/unstable-core-do-not-import/http/types.ts
- packages/tests/server/___testHelpers.ts
- packages/tests/server/adapters/awsLambda.test.tsx
- packages/tests/server/adapters/express.test.tsx
- packages/tests/server/adapters/fastify.test.ts
- packages/tests/server/adapters/next.test.ts
- packages/tests/server/errors.test.ts
- packages/tests/server/index.test.ts
- packages/tests/server/methodOverride.test.ts
- packages/tests/server/react/regression/issue-1645-setErrorStatusSSR.test.tsx
- packages/tests/server/smoke.test.ts
- packages/tests/server/streaming.test.ts
> chore: refactor `resolveResponse`

- www/docs/server/adapters/aws-lambda.md
- closes #5739
- closes #5738
Closes #
> docs: update aws-lambda.md

- README.md
- pnpm-lock.yaml
- www/package.json
- www/src/components/sponsors/script.output.ts
- www/src/components/sponsors/script.pull.ts
- www/unversioned/_sponsors.mdx
> docs: update sponsors

- www/docs/client/react/useMutation.md
Closes #
update useMutation docs to use isPending instead of isLoading as indicated [here](https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5#status-loading-has-been-changed-to-status-pending-and-isloading-has-been-changed-to-ispending-and-isinitialloading-has-now-been-renamed-to-isloading)
> Update useMutation.md to comply with latest react query changes

- packages/tests/server/___testHelpers.ts
- packages/tests/server/websockets.test.ts
Ref #5748
Improves websocket reconnect tests
> chore(server): improve websocket reconnect tests

- www/docs/client/react/createTRPCQueryUtils.md
> docs: fix missing curly bracket

- www/docs/client/links/splitLink.mdx
> docs: update splitLink.mdx

- package.json
- packages/client/src/createTRPCClient.ts
- packages/next/src/app-dir/client.ts
- packages/next/src/app-dir/server.ts
- packages/next/src/app-dir/shared.ts
- packages/next/src/createTRPCNext.tsx
- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/rsc.tsx
- packages/react-query/src/server/ssgProxy.ts
- packages/react-query/src/shared/proxy/decorationProxy.ts
- packages/react-query/src/shared/proxy/useQueriesProxy.ts
- packages/react-query/src/shared/proxy/utilsProxy.ts
- packages/server/src/unstable-core-do-not-import/createProxy.ts
- packages/server/src/unstable-core-do-not-import/router.ts
- packages/server/src/unstable-core-do-not-import/utils.ts
- packages/tests/server/react/regression/issue-5808-proxy-in-dep-array.test.tsx
Closes #5808
This is a bit of a mindfuck.
> fix(react-query): return same `Proxy`-object to avoid infinite recursion

- examples/next-sse-chat/railway.json
- examples/next-sse-chat/railway.toml
- examples/next-sse-chat/src/app/channels/[channelId]/chat.tsx
- examples/next-sse-chat/src/server/routers/post.ts
Closes #
- fix infinite scroll
- anchor scroll to bottom using a `flex-col-reverse` CSS hack
- add "load more"-button
- switch from railway JSON to TOML as it gives autocomplete
> chore(sse example): fix infinite scroll + anchor scroll to bottom

- packages/server/src/unstable-core-do-not-import/stream/sse.test.ts
Closes #
Somehow we allow type errors in our tests 😬
> chore: fix errors in `sse.test.ts`

- www/docs/main/getting-started.mdx
Closes # NA
Just fix a small typo in docs
> fix: Typo in getting-started.mdx

- packages/server/src/unstable-core-do-not-import/http/getHTTPStatusCode.ts
Closes #5847
I'm not sure why/how this happens, but made the code more defensive
> fix(server): Cannot read properties of undefined (reading 'httpStatus')

- packages/server/src/unstable-core-do-not-import/createProxy.ts
- packages/tests/server/react/regression/issue-5808-proxy-in-dep-array.test.tsx
- Partially reverts #5810
- Unfixes #5808
> fix(server): uncache proxies

- .github/setup/action.yml
- .github/workflows/release-next.yml
- .github/workflows/release-tmp.yml
- .github/workflows/release.yml
ref https://github.com/pnpm/action-setup/issues/136
> chore: bump pnpm action

- .github/workflows/subtree.yml
> chore: fix subtree

- examples/next-sse-chat/README.md
> chore: update sse chat readme

- packages/client/src/internals/TRPCUntypedClient.ts
- packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts
- packages/server/src/adapters/ws.ts
- packages/server/src/unstable-core-do-not-import/http/contentType.ts
- packages/server/src/unstable-core-do-not-import/http/types.ts
Closes #
https://github.com/trpc/trpc/issues/5851#issuecomment-2211615131
> feat(server): add abort signal to request info

- www/docs/client/links/httpSubscriptionLink.md
As discussed on Discord https://discord.com/channels/867764511159091230/1259151436495847515.
Added a section on the httpSubscriptionLink in relation to React Native.
> docs: added a section on the httpSubscriptionLink compatibility with React Native

- www/docs/client/links/httpSubscriptionLink.md
Closes #
Added instructions on how to install and apply the polyfills
> Code snippet polyfill

- README.md
- www/src/components/sponsors/script.output.ts
- www/src/components/sponsors/script.pull.ts
- www/src/components/sponsors/script.push.ts
- www/unversioned/_sponsors.mdx
> docs: sync sponsors

- packages/server/src/adapters/ws.ts
Closes #
Might fix race condition in some scenarios as specified in https://github.com/trpc/trpc/issues/5889#issuecomment-2224999891
> fix(ws): delcare `ctx` variable before `ctxPromise`

- examples/next-sse-chat/README.md
- examples/next-sse-chat/src/server/routers/post.ts
- www/docs/client/links/httpSubscriptionLink.md
Just docs, added some details from discussion #5897
> Update docs & example relating to `httpSubscriptionLink`

- www/docs/community/awesome-trpc.mdx
Closes #
Added ConvoForm to the list of open-source projects using tRPC.
> doc(awesome-trpc): add ConvoForm in projects list section

- .github/workflows/dependabot-approve.yml
Closes #
make the auto approval safer
> chore: Update dependabot-approve.yml

- packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts
- packages/server/src/unstable-core-do-not-import/stream/jsonl.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/createReadableStream.ts
- packages/tests/server/regression/issue-5945-stream-null.test.ts
> fix(streaming): returning `null` and `undefined` without transformer

- www/docs/server/procedures.md
Closes #
In providing a link to Authorization page.
> docs(procedures): link Authorization

- www/docs/client/nextjs/setup.mdx
- www/docs/client/react/server-components.mdx
- www/docs/client/react/suspense.md
- www/docs/community/awesome-trpc.mdx
- www/sidebars.js
Closes #5936
Closes(?) #5277
https://www-git-rsc-docs-trpc.vercel.app/docs/client/react/server-components
> docs: add `@trpc/react-query/rsc` docs

- www/docs/client/links/httpSubscriptionLink.md
Closes nothing
Just a tiny update to the docs, what I wrote is correct right? I guess this is kinda half way between a question and a PR 😅 At least it's my current understanding after digging through the code in `packages/server/src/unstable-core-do-not-import/stream/sse.ts:149`.
- N/A I have added or updated the tests related to the changes made.
> docs(sse): add a tip about cleanup, change completeness section to tip

- CONTRIBUTING.md
- www/README.md
- www/docs/client/links/httpSubscriptionLink.md
- www/docusaurus.config.js
- www/og-image/next-env.d.ts
Ref #6022
Update http subscription docs
> chore: update docs

- examples/next-prisma-websockets-starter/next-env.d.ts
- examples/next-prisma-websockets-starter/src/utils/trpc.ts
- packages/client/src/links/wsLink.ts
- packages/server/src/adapters/ws.ts
- packages/tests/server/websockets.test.ts
- www/docs/client/links/wsLink.md
Closes #4078
Allow the client to send ping/pong messages
See `keepAlive` in https://trpc.io/docs/client/links/wsLink#wslink--createwsclient-options
> feat(ws): allow client to send ping messages

- packages/client/src/links/wsLink.ts
- packages/server/src/adapters/ws.ts
- packages/tests/server/websockets.test.ts
Closes #
- Tests were flaky which means code might be flaky
- Ping and pong are now explicit **messages** that say PING and PONG since browsers don't really support ping/pong
> chore(ws): a bit more stable ping/pong

- examples/next-sse-chat/src/lib/stream-to-async-iterator.ts
- examples/next-sse-chat/src/server/routers/channel.ts
- examples/next-sse-chat/src/server/routers/post.ts
- pnpm-lock.yaml
- www/docs/further/websockets.md
Closes #
- Fixes so SSE example uses `signal`
- Verify that #6045 isn't a bug in tRPC
> chore: fix SSE chat example

- README.md
- www/src/components/sponsors/script.output.ts
- www/src/components/sponsors/script.pull.ts
- www/src/components/sponsors/script.push.ts
- www/unversioned/_sponsors.mdx
fix typo
keenetics -> keenet**h**ics
> docs: fix typo

- packages/server/src/unstable-core-do-not-import/procedureBuilder.ts
- www/docs/migration/migrate-from-v10-to-v11.mdx
- Deprecate usage of observables in subscriptions
> feat(server): deprecate usage of observables in subscriptions

- www/docs/community/awesome-trpc.mdx
Closes #
Added the `nestjs-trpc` adapter to the "Library adapters" section in the docs.
You can view the changes here:
https://www-git-fork-kevinedry-next-trpc.vercel.app/docs/community/awesome-trpc#library-adapters
> docs: added the nestjs-trpc adapter to the community list

- packages/client/src/links/httpSubscriptionLink.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/tests/server/httpSubscriptionLink.headers.test.ts
- www/docs/client/links/httpSubscriptionLink.md
> feat(sse): ability to reconnect with new headers

- www/docs/server/subscriptions.md
Fixed syntax error in server/subscription docs
> docs: fix example syntax mistake

- www/docs/server/subscriptions.md
> docs(server/subscriptions): fix standalone server type

- packages/server/src/adapters/express.ts
- packages/tests/server/websockets.test.ts
Closes #
rm unnecessary `void`
> chore: formatting fix

- www/docs/client/react/setup.mdx
> fix(docs): remove rogue semicolon

- .eslintrc.js
- .prettierignore
- packages/server/package.json
- packages/server/src/adapters/ws.ts
- packages/server/src/unstable-core-do-not-import/procedureBuilder.ts
- packages/server/src/unstable-core-do-not-import/stream/jsonl.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/asyncIterable.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/withPing.ts
- packages/server/src/vendor/unpromise/ATTRIBUTION.txt
- packages/server/src/vendor/unpromise/LICENSE
- packages/server/src/vendor/unpromise/index.ts
- packages/server/src/vendor/unpromise/types.ts
- packages/server/src/vendor/unpromise/unpromise.ts
- packages/tests/server/TRPCError.test.ts
- packages/tests/server/httpSubscriptionLink.memory.test.ts
- packages/tests/server/websockets.memory.test.ts
- packages/tests/tsconfig.json
- vitest.config.ts
> fix(server): subscription memory leak

- www/docs/client/react/server-components.mdx
Closes #
Some people who are picky about grammar may believe that `utilize` means to use something in a way that differs from its intended use.
https://english.stackexchange.com/a/143945
> docs: Grammar Fix on /server-components

- examples/.railway/next-prisma-websockets-starter/railway.json
- examples/next-prisma-websockets-starter/package.json
- examples/next-prisma-websockets-starter/src/pages/api/auth/[...nextauth].ts
- examples/next-sse-chat/package.json
- packages/tests/server/websockets.test.ts
- pnpm-lock.yaml
> chore: fix websocket example deployment

- packages/client/package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/server/package.json
- pnpm-lock.yaml
- scripts/entrypoints.ts
- www/docs/further/faq.mdx
- www/docs/main/quickstart.mdx
- www/docs/migration/migrate-from-v10-to-v11.mdx
> chore: set required typescript version to `>5.6.2`

- packages/server/package.json
- packages/server/rollup.config.ts
- packages/server/src/adapters/next-app-dir/rethrowNextErrors.ts
- pnpm-lock.yaml
- scripts/getRollupConfig.ts
> fix(server): remove `optionalDependencies`

- examples/.experimental/next-app-dir/package.json
- examples/bun/package.json
- examples/cloudflare-workers/package.json
- examples/express-minimal/package.json
- examples/express-server/package.json
- examples/fastify-server/package.json
- examples/minimal-content-types/client/package.json
- examples/minimal-react/client/package.json
- examples/minimal/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-websockets-starter/package.json
- examples/soa/package.json
- examples/standalone-server/package.json
- examples/tanstack-start/package.json
- package.json
- packages/client/package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/server/package.json
- packages/tests/package.json
- pnpm-lock.yaml
> chore: bump to typescript 5.7

- examples/express-minimal/package.json
- examples/express-server/package.json
- package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/server/package.json
- pnpm-lock.yaml
> chore: bump express

- examples/.experimental/next-app-dir/package.json
- examples/.test/diagnostics-big-router/package.json
- examples/.test/ssg-infinite-serialization/package.json
- examples/.test/ssg/package.json
- examples/minimal-content-types/client/package.json
- examples/minimal-react/client/package.json
- examples/next-big-router/package.json
- examples/next-edge-runtime/package.json
- examples/next-formdata/package.json
- examples/next-minimal-starter/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/next-prisma-websockets-starter/package.json
- examples/next-sse-chat/package.json
- examples/tanstack-start/package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/server/package.json
- packages/tanstack-react-query/package.json
- packages/tanstack-react-query/src/internals/infiniteQueryOptions.ts
- packages/tanstack-react-query/src/internals/queryOptions.ts
- packages/tests/package.json
- pnpm-lock.yaml
Sister PR to https://github.com/TanStack/query/pull/8468
> Standalone queryoptions package portable fix

- www/docs/community/awesome-trpc.mdx
Added two of my packages on the tRPC collection page.
> docs: Add trpc-zustand and trpc-live links

- packages/tests/server/websockets.test.ts
cc @hmatthieu, i'm pretty sure this would fail on #6223
> chore: add ws test

- examples/soa/client/client.ts
- examples/soa/client/index.ts
- examples/soa/server-a/router.ts
- examples/soa/server-b/router.ts
- packages/client/src/links/splitLink.test.ts
- packages/client/src/links/splitLink.ts
> Multi splitlink fork

- README.md
- www/src/components/sponsors/script.output.ts
- www/src/components/sponsors/script.push.ts
- www/unversioned/_sponsors.mdx
> docs: sponsors sync

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
> simplify hook

- packages/upgrade/src/lib/ast/modifiers.ts
- packages/upgrade/src/lib/ast/walkers.ts
- packages/upgrade/src/transforms/hooksToOptions.ts
- www/docs/client/tanstack-react-query/server-components.mdx
both for codeRabbit and the internal node trampoline
Closes #
Tiny refactor to avoid coderabbit and to help the node trampoline wrapper in a very tiny set of edge cases
> refactor: make walkers to follow Tail-call pattern

- pnpm-lock.yaml
- www/blog/2025-02-17-new-tanstack-react-query-integration.mdx
- www/package.json
- www/src/components/BlogComments.tsx
- www/src/theme/BlogPostItem/index.tsx
> docs: blog comments

- README.md
- www/docs/migration/migrate-from-v10-to-v11.mdx
- www/src/components/sponsors/script.output.ts
- www/unversioned/_sponsors.mdx
Closes #
- @hmatthieu as active contributor
- @Nick-Lucas as lead
- sunset @ixahmedxi as active contributor (last commit was > 1 year ago)
> docs: update contributors

- www/docs/client/tanstack-react-query/usage.mdx
> Break up markdown because prettier did crazy things

- packages/tanstack-react-query/src/internals/createOptionsProxy.ts
- packages/tanstack-react-query/src/internals/infiniteQueryOptions.ts
- packages/tanstack-react-query/src/internals/queryOptions.ts
- packages/tanstack-react-query/src/internals/utils.ts
- packages/tanstack-react-query/test/queryOptions.test.tsx
- packages/tanstack-react-query/test/skipToken.test.tsx
> Fix skipToken in new TRQ client
