- examples/next-ssg-chat/pages/index.tsx
- examples/next-ssg-chat/utils/trpc.ts
showcase that you can [quite easily] infer output of the resolvers
> skip importing prisma model on chat example

- README.md
- examples/next-hello-world/package.json
- examples/next-hello-world/utils/trpc.ts
- examples/next-ssg-chat/package.json
- examples/next-ssg-chat/pages/index.tsx
- examples/next-ssg-chat/utils/trpc.ts
- examples/playground/package.json
- examples/standalone-server/package.json
- lerna.json
- packages/client/package.json
- packages/client/src/createTRPCClient.ts
- packages/react/package.json
- packages/react/src/createReactQueryHooks.ts
- packages/server/package.json
- packages/server/src/router.ts
- packages/server/src/subscription.ts
- packages/server/test/react.test.tsx
- Fix types for `useInfiniteQuery`
- Refactor trpc client into a class (reluctantly)
- Prefix cache keys for live query and infinite query so you can query same endpoints without getting unexpected cache cache hits
> refine `useInfiniteQuery()`

- README.md
- packages/server/src/adapters/express.ts
- packages/server/src/adapters/next.ts
- packages/server/src/http.ts
- packages/server/src/router.ts
- packages/server/test/middleware.ts
- packages/server/test/preHook.test.ts
- allows you to create a middleware-esque thing on a router that cascades down on all routes added after
- I don't love the name `preHook` - would love some input.
- (started on a proper "middleware"-thing in #88, but it's a bit complicated as it might require async iterables, so might do that later or never)
- see the tests for usage, here's an example of an admin "sub-router"   https://github.com/trpc/trpc/blob/5f96526432bd8d5454e145e62e3df9eba3f9785c/packages/server/test/preHook.test.ts#L67-L84
> Add middleware support

- README.md
- examples/next-hello-world/package.json
- examples/next-hello-world/pages/api/trpc/[...trpc].ts
- examples/next-hello-world/pages/index.tsx
- examples/next-ssg-chat/package.json
- examples/next-ssg-chat/utils/trpc.ts
- examples/playground/package.json
- examples/playground/src/server.ts
- examples/standalone-server/package.json
- lerna.json
- packages/client/package.json
- packages/client/src/createTRPCClient.ts
- packages/react/package.json
- packages/react/src/createReactQueryHooks.ts
- packages/server/package.json
- packages/server/src/router.ts
- packages/server/test/index.test.tsx
Feedback from @schickling:
> - Given you’re calling things “trpc” I’d drop the “route” term and embrace RPC
- All instances of _route_ has been renamed to _procedure_
- Router is still called Router as that terminology still makes sense
- Will be a major version bump, however, for standard usage it won't be a breaking change. As you can see in the `examples/*`-diff no changes are needed, except when you want to infer the output, e.g. https://github.com/trpc/trpc/pull/98/files#diff-0c1e6158e63285d8d9c7b53591ba5a08b31fd1759bdb478608fb4490c624d4d0.
> rename route to procedure

- README.md
- examples/next-ssg-chat/pages/api/trpc/[trpc].ts
- packages/react/src/createReactQueryHooks.ts
- packages/server/test/react.test.tsx
- allows you to use `trpc.invalidateQuery([path, input])` in a type-safe way
> `invalidateQuery()`-helper

- examples/next-hello-world/pages/api/trpc/[trpc].ts
- examples/next-hello-world/pages/api/trpc/posts.ts
- examples/next-prisma-todomvc/pages/api/trpc/todoRouter.ts
- examples/next-ssg-chat/pages/api/trpc/[trpc].ts
- examples/playground/src/server.ts
- examples/standalone-server/src/server.ts
- packages/server/test/errors.test.ts
- packages/server/test/express.test.tsx
- packages/server/test/index.test.tsx
- packages/server/test/react.test.tsx
- packages/server/test/subscriptions.test.tsx
- packages/server/test/validators.test.ts
- www/docs/react/nextjs.md
- www/docs/server/procedures.md
As zod v3 has just been released, a [new import syntax](https://github.com/trpc/trpc/pull/388#issuecomment-843209188) is now [recommended by the docs](https://github.com/colinhacks/zod#basic-usage).
> refactor(zod): update imports as v3 recommends

- README.md
- package.json
- packages/client/src/createTRPCClient.ts
- packages/react/src/ssg.ts
- packages/server/package.json
- packages/server/src/http.ts
- packages/server/src/transformer.ts
- packages/server/test/transformer.test.ts
- www/docs/server/data-transformers.md
- yarn.lock
As discussed [here](https://github.com/trpc/trpc/issues/378) this adds a new interface `CombinedDataTransformer` which allows to specify different transformers for server->client and client->server communication. `CombinedDataTransformer`can be used interchangeable with `DataTransformer`.
```ts
type DataTransformer = {
serialize(object: any): any;
deserialize(object: any): any;
};
type CombinedDataTransformer = {
input: DataTransformer;
output: DataTransformer;
};
```
```ts
import superjson from 'superjson';
import devalue from 'devalue';
export const transformer = {
input: superjson,
output: {
serialize: (object) => devalue(object),
deserialize: (object) => eval(`(${object})`),
},
};
// Add to `createTRPCCLient()`
export const client = createTRPCClient<AppRouter>({
// [...]
transformer: …
```
> add combined transformers

- packages/server/src/router.ts
- packages/server/test/errors.test.ts
just realised that we don't safe-guard from querying on built-in object properties. 
i.e. 
- `client.query('toString')` for example does _not_ return `NOT_FOUND` as it's part of the built-in stuff
- also, you can't use `toString` as a procedure key
- refactor router to create all objects with `Object.create(null)` instead of `null`
- refactor spread operators to `Object.assign(Object.create(null), x, y)` (via `safeObject`-fn)
did it TDD-style - both of these tests were failing as you can see in the commit history
> add guards for `Object.prototype`-props

- .github/workflows/subtree.yml
- .prettierrc
- examples/next-prisma-starter/.github/dependabot.yml
- examples/next-prisma-starter/.github/workflows/codeql-analysis.yml
- examples/next-prisma-starter/.github/workflows/main.yml
- examples/next-prisma-starter/README.md
- examples/next-prisma-starter/package.json
- package.json
- yarn.lock
mirror prisma example to new repo using git subtrees
https://github.com/trpc/trpc/tree/main/examples/next-prisma-starter is now mirrored downstream to https://github.com/trpc/examples-next-prisma-starter automatically
> `next-prisma-starter`: add ci + subtree mirror + fix linting

- examples/express-server/package.json
- examples/next-chat/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/standalone-server/package.json
- lerna.json
- packages/client/package.json
- packages/client/src/createTRPCClient.ts
- packages/client/src/internals/executeChain.ts
- packages/client/src/links/core.ts
- packages/next/package.json
- packages/react/package.json
- packages/react/src/createReactQueryHooks.tsx
- packages/server/package.json
- packages/server/src/router.ts
- packages/server/src/subscription.ts
- packages/server/test/links.test.ts
- allow you to add additonal context on requests
- useful to pass to to a `splitLink` and for instance route slow queries to `httpLink` rather than `httpBatchLink`
> add optional request context

- examples/next-prisma-starter/src/pages/_app.tsx
just stumbled upon
1. wrong example url for vercel (in other places throughout the docs it is correct)
~2. imo usually unnecessarily complex url for render.com~
> fix vercel url

- packages/server/src/http/requestHandler.ts
- packages/server/test/transformer.test.ts
Currently we are only serializing input in trpc/client if there actually is an input. But in trpc/server we deserialize the input even if it is `undefined`. In other words: we try to deserialize a value (`undefined`) which was not serialized at all. (SuperJSON for example throws an error then.)
In this PR I've added a test to capture this behavior and the fix in trpc/server.
> BUGFIX Transform undefined input

- www/src/pages/index.js
"it's" means "it is", and "its" indicates possession as intended in this sentence.
> docs: fix typo

- packages/server/src/http/internals/getHTTPStatusCode.ts
- packages/server/src/http/requestHandler.ts
- packages/server/src/router.ts
- packages/server/src/ws/wssHandler.ts
- packages/server/test/transformer.test.ts
https://github.com/trpc/trpc/blob/8e6ea59f07de33addc486ec6cc956deb40789109/packages/server/src/http/internals/getHTTPStatusCode.ts#L34
When using combined transformers, this line is calling `transformer.input.deserialize`, but it is parsing an error which is serialized with `transformer.output.serialize`.
> BUG: Combined transformers not transforming errors on server

- packages/react/src/createReactQueryHooks.tsx
- packages/server/test/react.test.tsx
Closes #621 
When writing tests I've encountered two different behavior depending on whether the `queryKey` changes or not and documented both of them in tests.
> Fix disabled query SSR and add tests

- packages/client/src/internals/httpRequest.ts
- packages/server/src/http/internals/getPostBody.ts
- packages/server/src/http/requestHandler.ts
- packages/server/test/_testHelpers.ts
- packages/server/test/rawFetch.test.tsx
- www/docs/further/further-reading.md
Before post bodies looked like
```
{
input: <<INPUT_DATA>>
}
```
Now, we just pass input data straight off without nesting it in `input`. Added backward-compatible code and test that can be deleted in next major.
---
The idea originated with having a body envelope was to be able to pass info about batching and the paths called, etc, but this is done through the query params
> flatten post requests' `input`

- packages/client/src/links/wsLink.ts
- packages/server/src/ws/wssHandler.ts
- packages/server/test/_testHelpers.ts
- packages/server/test/websockets.test.ts
fixes edge-case where `createContext()` takes longer than it takes to receive the first message from the client, leading to initial messages being lost
> fix: wss missing initial msgs if slow `createContext()`-fn

- packages/client/src/links/splitLink.ts
- packages/server/test/links.test.ts
I find `left`/`right` very unintuitive (`right` means `false`)
 todos:
> `splitLink`: `left`/`right` to `true`/`false`

- www/docs/server/middlewares.md
Hi there, thanks for this library! I'm checking it out and appreciate how it feels like a much more lightweight approach to my typical Prisma-Nexus-Apollo-GQL Codegen stack.
I was a little confused at the use of `httpError` in the middleware example and where it came from. This PR updates this deprecated call to the new error API and adds a tip referencing the error handling page.
Looks like the [test in question](https://github.com/trpc/trpc/blob/be9d168e0b994d28af32875b7ca3942ab956e3bf/packages/server/test/middleware.test.ts#L78-L80) still uses the deprecated API -- I didn't take a look at that. (I also think it would be great to contextualize the scope and current limitations of middlewares vis-a-vis their "typical" usage in frameworks like Koa, as mentioned in #586, since there's not …
> Replace deprecated `httpError` in Middleware example

- packages/server/src/internals/BaseHandlerOptions.ts
- packages/server/src/internals/errors.ts
- packages/server/test/_testHelpers.ts
- packages/server/test/errors.test.ts
Inherit stack trace from original error when throwing
Useless stack trace
```
TRPCError: CustomError.msg
at Object.getErrorFromUnknown ([redacted]/trpc/packages/server/src/internals/errors.ts:23:15)
at [redacted]/trpc/packages/server/src/http/requestHandler.ts:173:25
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Promise.all (index 0)
at Object.requestHandler ([redacted]/trpc/packages/server/src/http/requestHandler.ts:153:21)
at [redacted]/trpc/packages/server/src/adapters/standalone.ts:30:5
```
Useful stack trace
```
CustomError: CustomError.msg
at ProcedureWithoutInput.resolve [as resolver] ([redacted]/trpc/packages/server/test/errors.test.ts:296:17)
at ProcedureWithoutInput.call ([redacted]/trpc/packages/server/src/procedure.ts:106:31)
at Router.invoke …
```
> `@trpc/server` - inherit stack trace

- packages/react/src/createReactQueryHooks.tsx
- packages/server/test/react.test.tsx
I've encountered an issue with prefetching infinite queries where all page contents were replaced by the content of the first page while the number of pages remained the same. I narrowed it down to a `pageParam` being ignored when prefetching and fetching infinite queries.
The PR fixes the issue and adds tests.
> Fix prefetching infinite query

- packages/client/src/TRPCClientError.ts
- packages/server/src/TRPCError.ts
- packages/server/src/http/internals/getQueryInput.ts
- packages/server/src/internals/errors.ts
- packages/server/src/procedure.ts
- packages/server/src/ws/wssHandler.ts
- packages/server/test/errors.test.ts
- www/docs/server/error-formatting.md
- www/docs/server/error-handling.md
- rename `originalError` to `cause` to align with https://github.com/tc39/proposal-error-cause
- change `Error`-super call to `super(message, { cause })` for future compat
closes #879
> rename `originalError` to `cause` + deprecate `originalError`

- packages/client/src/internals/TRPCClient.ts
- packages/client/src/internals/httpRequest.ts
- packages/client/src/links/core.ts
- packages/server/test/headers.test.tsx
- packages/server/test/links.test.ts
- www/docs/nextjs/nextjs.md
Reverts #908 (never made it to a release)
Might be a better implementation to be able to make a `getFetch`-fn (see conversation here https://github.com/trpc/trpc/pull/908#issuecomment-916145019) but I don't have energy to implement it.
> Revert "add `fetchOptions` on client runtime"

- packages/server/src/internals/procedure.ts
- packages/server/src/router.ts
- packages/server/test/inference.test.ts
- packages/server/test/regression/issue-949-inferProcedureInput.test.ts
~Fixes #949~
Follow-up to #955
This simplifies Procedure down to one type:
- ~`CreateProcedureWithInput`, `CreateProcedureWithoutInput`, `CreateProcedureOptions` -> `CreateProcedureOptions` (a single union type)~
- `ProcedureWithInput`, `ProcedureWithoutInput`, `Procedure` -> `Procedure` (a single non-abstract class which _always_ has a `TInput`. The input just happens to be undefined if it was created without an input parser specified)
~Note: there is one downside to this approach which is that for procedures with no inputs, the `input` prop passed to the resolver is typed as `unknown`, where ideally it'd be `undefined` or `never`. IMHO that's a pretty ok tradeoff given how much this simplifies both `procedure.ts` and `router.ts`.~
> Simplify procedure types/overloads

- packages/react/src/createReactQueryHooks.tsx
- packages/server/test/regression/issue-990-initialData.test.tsx
Closes #990.
This is actually blocked by https://github.com/tannerlinsley/react-query/pull/2715 but this feature should automerge as soon as there's a new version of react-query fixing it.
> fix `initialData` being `TInput`

- packages/server/src/internals/middlewares.ts
- packages/server/src/internals/procedure.ts
- packages/server/test/middleware.test.ts
- www/docs/server/middlewares.md
@KATT
In many routers, the authentication step takes place in the procedure resolver instead of middleware because data needed to perform the authentication is located in the procedure input, which is currently not passed to middleware. It would be helpful to have access to procedure input in middleware so a set of procedures can be authenticated all at once by a single middleware.
To solve this, this PR adds `input` as a parameter to the middleware function. Because the middleware cannot infer the type of procedure input because they act on many procedures, the `input` is passed as `unknown`.
Please let me know if this makes sense / is useful for others!
Example usage:
```ts
const router = createRouter()
.middleware(({ ctx, input }) => {
checkUserAuth(ctx, input.userId); // throws if the …
```
> feat: pass procedure input to middleware

- packages/next/src/withTRPC.tsx
The `responseMeta()`-callback was not returning the correct headers
> fix `withTRPC()` response headers

- www/docs/server/merging-routers.md
It took me a few minutes to realize that the "createRouter" was a helper function, not a trpc function.
> docs: the "createRouter" function must be explicitly defined

- www/docs/server/express.md
`createContext` is defined but never used so either it should be used in the `createExpressMiddleware` (that's what I did) or should be removed.
> docs: use unused variable

- examples/next-prisma-starter-websockets/test/playwright.test.ts
- examples/next-prisma-todomvc/test/playwright.test.ts
- packages/server/src/adapters/express.ts
- packages/server/src/adapters/standalone.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> Replace deprecated String.prototype.substr()

- www/docs/react/react-intro.md
- added distinction between things that should be done in server-side vs client-side. It complicates the docs but in my opinion, is necessary.
- added a note about installing `@trpc/server` on the client. this prevents problems like #1463 to happen again.
> docs: update react introduction

- examples/next-prisma-starter/README.md
Fix a broken link in next-prisma-starter readme
> chore: update readme link in next-prisma-starter

- www/docs/main/example-apps.md
Right now it's pointing to wrong example.
> fix: url for next-prisma-starter-websockets

- README.md
- examples/next-prisma-starter-websockets/README.md
- examples/next-prisma-starter/README.md
- examples/next-prisma-todomvc/README.md
- www/docs/main/example-apps.md
- www/docs/nextjs/starter-projects.md
The syntax to use `create-next-app` with `yarn`, is `yarn create next-app` and not `yarn create-next-app` like it states in the docs.
Small typo but could definitely trip someone up if they weren't paying attention! 😄
> Correcting usage of yarn create next-app.

- package.json
- packages/next/src/withTRPC.tsx
- packages/react/src/createReactQueryHooks.tsx
- packages/react/src/internals/context.tsx
- packages/server/test/react.test.tsx
When server-side-rendering the status stays at `loading` even when the query fails.
Here's an awful hack because I'm unsure what else to do. Any other thing I can think of will lead to hydration warnings.. I could also dive into the `optimisticResults`-property of `react-query` to see if there's a way to trick it to become `error`.
- Adds a new `SSRState`-property
- Bypasses default options and defaults to `refetchOnMount: false` when hydrating SSR until it's been mounted on the client
How we do the SSR prepass to enable SSR:
1. Run through the app tree until there are no pending queries: https://github.com/trpc/trpc/blob/f27680fe9ccc444da6282f3e118ba82c3b0b2095/packages/next/src/withTRPC.tsx#L173-L192
2. In each query hook, we call `prefetchQuery` when doing the prepass in order to fetch …
> bug: SSR hydration with error doesn't set status `error`

- examples/standalone-server/tsconfig.json
- packages/server/src/adapters/next.ts
- yarn.lock
So, the problem with this one seems to be that the `adapters/next.ts` imports from `next` which in turn nowadays some `global.d.ts` which affects the whole build.
Giving us this output in `packages/server/dist/declarations/src/adapters/ws.d.ts:2:23 `:
```ts
/// <reference types="node" />
/// <reference types="./types/global" /> // <--------------- this is bad and is coming from node_modules/next
import http from 'http';
import ws from 'ws';
import { BaseHandlerOptions } from '../internals/BaseHandlerOptions';
import { AnyRouter } from '../router';
import { NodeHTTPCreateContextOption } from './node-http';
/**
* Web socket server handler
*/
export declare type WSSHandlerOptions<TRouter extends AnyRouter> =
BaseHandlerOptions<TRouter, http.IncomingMessage> & {
wss: ws.Server;
process?: …
```
> Dependabot/npm and yarn/next 12.1.0

- packages/server/test/_testHelpers.ts
- packages/server/test/websockets.test.ts
When running `yarn test` we generate the following warning due our wss clients not being closed before the server is closed. This is also causing some flakey tests.
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```
* `_testHelpers.ts` - Close all clients before closing websocket server after each test
* `websockets.test.ts` - Enabled flakey websocket subscription test
> Prevent @server test memory leaks due to improper teardown.

- www/docs/main/introduction.md
- www/src/css/custom.css
- www/src/pages/index.js
- www/src/pages/styles.module.css
Probably the easiest win in terms of docs readability. The fact that docusaurus doesn't apply a max-width on the main content column is bizarre. This makes the tRPC docs feel intimidating, like a wall of text. I think this helps dramatically.
Before
After
> Docs formatting

- packages/client/src/internals/httpRequest.ts
- packages/server/test/headers.test.tsx
- packages/server/test/websockets.test.ts
Closes: https://github.com/trpc/trpc/issues/1712
Added a transform to delete headers with `undefined` values before HTTP requests are sent by the `TRPCClient`.
```javascript
{ "x-defined": "xyz", "x-undefined": undefined } 
// is transformed to
{ "x-defined": "xyz" }
```
* Added headers transformer to `httpRequest` method
* Removed `undefined` typing from `HTTPHeaders` record
* Added test case for removing undefined headers 
* Updated @trpc/client imports to relative path in tests
 
> Remove undefined HTTP headers from TRPCClient

- README.md
- examples/fastify-server/package.json
- examples/fastify-server/src/client/index.ts
- examples/fastify-server/src/server/server.ts
- packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts
- packages/server/test/adapters/fastify.test.ts
- www/docs/further/awesome-trpc.mdx
- www/docs/main/example-apps.md
- www/docs/main/introduction.md
- www/docs/server/fastify.md
Fixes #1715, allows the use of the fastify adapter with or without the `fastify-plugin`.
With fp: the response body will be a string for all requests (as before). 
Without fp: the response body will not be modified by the adapter.
> fix: fastify adapter using fastify-plugin

- packages/react/src/createReactQueryHooks.tsx
- packages/server/src/internals/procedure.ts
- packages/server/src/router.ts
- packages/server/test/inference.test.ts
- packages/server/test/outputParser.test.ts
- packages/server/test/validators.test.ts
- www/docs/server/output-validation.md
- www/sidebars.js
I have a goal to try and auto-generate OpenAPI docs for a TRPC router (cc. https://github.com/trpc/trpc/issues/755). The feature in this PR will enable us to generate JSON schemas for request and response payloads. This output parser is **opt-in only** and should not introduce any breaking changes.
```
const appRouter = new trpc.router<Context>()
.query({
input: z.string(),
output: z.object({
input: z.string(),
}),
resolve: ({ input }) => {
return { input };
}
});
```
- Added a new optional `output` property.
- When `output` is provided, the `resolve` function will expect a return type inferred from the `output` parser.
- The response data will be validated against the `output` parser, unless `NODE_ENV` is `production`. 
- If the response data fails validation a `TRPCError …
> Add output response parser

- examples/next-prisma-starter-websockets/src/pages/index.tsx
I think that cause of #1691 is `fieldset` tag min-width is setted to [min-content](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width) by browser default.
So, I tried to resolve it to set min-width to 0.
> Fix Websockets example layout on mobile

- examples/next-prisma-starter-websockets/src/pages/_app.tsx
- examples/next-prisma-starter/src/pages/_app.tsx
- www/docs/nextjs/ssr.md
- www/docs/server/caching.md
Since `process.browser` is deprecated, the recommended workaround for determining if we are on the client or server on nextjs is `typeof window !== 'undefined'`: 
https://github.com/zeit/next.js/issues/5354#issuecomment-520305040
Thanks for quickly accepting this @KATT!  🙏
> `typeof window !== 'undefined'` to test for client

- packages/client/src/internals/TRPCClient.ts
- packages/client/src/links/transformerLink.ts
- packages/client/src/links/types.ts
- packages/client/src/links/wsLink.ts
- packages/server/src/adapters/next.ts
- packages/server/src/adapters/ws.ts
- packages/server/src/http/resolveHTTPResponse.ts
- packages/server/src/internals/transformTRPCResponse.ts
- packages/server/src/rpc/envelopes.ts
- packages/server/test/adapters/fastify.test.ts
- packages/server/test/adapters/next.test.ts
- packages/server/test/links.test.ts
- packages/server/test/rawFetch.test.tsx
- packages/server/test/responseMeta.test.ts
- packages/server/test/transformer.test.ts
- packages/server/test/websockets.test.ts
- www/docs/further/rpc.md
- www/docs/further/subscriptions.md
- www/docs/server/output-validation.md
Closes https://github.com/trpc/trpc/issues/1778
* Remove `"id": null` from HTTP response envelopes
* Remove `"type": "data"` from HTTP response envelopes
* Remove `"jsonrpc": "2.0"` from WS message envelopes
> Simplify tRPC request/response/message interfaces

- packages/server/src/adapters/ws.ts
- packages/server/test/websockets.test.ts
* Bug fix `"jsonrpc"` in websocket message envelopes
* Added test
@KATT - Glad you asked for a test (found a bug).
> Added websocket `"jsonrpc"` message envelope test

- www/docs/server/fastify.md
This adds a note to prevent people from encountering an error when tRPC batches too many queries, which generates long HTTP request URI queries, which Fastify will reject by default.
> docs: add note about fastify param length limit

- packages/server/src/internals/procedure.ts
- packages/server/src/types.ts
- packages/server/test/inference.test.ts
Closes #1817 
`resolve` is not throwing a TS error when returning an empty object. This is because TS is inferring the returned `{}` type from `resolve` as `TOutput` with higher priority than the supplied `output` type.
See inference priority reproduction: https://stackblitz.com/edit/typescript-qnjchh?file=index.ts
See real world issue reproduction: https://stackblitz.com/edit/typescript-5j9cvu?file=index.ts
Requires new patch release: `v9.22.1` @KATT?
> Bugfix `output` type inference priority

- examples/fastify-server/package.json
- examples/fastify-server/src/server/server.ts
- packages/server/package.json
- packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts
- packages/server/test/adapters/fastify.test.ts
- www/docs/server/fastify.md
- yarn.lock
`fastify-websocket` was renamed and is now published under `@fastify/websocket`. The new version doesn't contain any other changes, just a different name.
> Replace fastify-websocket with @fastify/websocket

- packages/client/src/internals/TRPCClient.ts
Updates the links in `TRPCClient` jsdoc from `http://localhost:/3000` to `https://trpc.io`.
> fix incorrect urls in jsdoc `@link`s in `TRPCClient`

- packages/server/src/adapters/node-http/types.ts
fix #1904
Remove use of `@types/qs`. Change `NodeHTTPRequest` to use `http.IncomingMessage`'s type for `method`.
> fix node-http type errors

- examples/next-prisma-starter/src/pages/post/[id].tsx
- www/docs/nextjs/ssg.md
See #1911 we get some hydration errors with the NextJS starter example.
This fixes the hydration by setting a locale in options. Was probably different between server and client.
> Fix hydration issue with Date.prototype.toLocaleDateString

- packages/server/src/internals/middlewares.ts
> use branded `string` type instead of `Symbol`

- packages/client/src/links/wsLink.ts
- packages/server/test/websockets.test.ts
Resolves https://github.com/trpc/trpc/discussions/1857.
A pretty niche bug originally reported by @jld-adriano.
* `const wsClient = createWSClient({ url: 'ws://bad-ws-url.com' })`
* `wsClient.close()`
* Will get stuck in infinite `tryReconnect()` loop. 
* Clear `connectTimeout` on `.close()` (added test)
> Websocket client stuck reconnecting after `.close()`

- packages/react/src/createReactQueryHooks.tsx
- packages/server/test/react.test.tsx
This will fix the issue specifically defined in the issue linked, but a thorough investigation to make sure typing is being done in a way that honors the patterns behind react-query would be a good idea. At the moment the infinite queries are actually broken (I have a PR there to resolve it), so those are probably less important to investigate until that PR is merged.
closes https://github.com/trpc/trpc/issues/1779
original PR: #1943
> Honor type when useQuery select fn is used

- packages/client/src/createTRPCClient.ts
- packages/server/src/router.ts
This is a follow-up of this [PR](https://github.com/trpc/trpc/pull/1958#issue-1261776224), on the right origin this time. 👍
> fix(types): export internals for types definitions generation

- www/docs/nextjs/ssr.md
Copying the ssr example as is results in 
`TRPCError: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"object\",\n    \"received\": \"undefined\",\n    \"path\": [],\n    \"message\": \"Required\"\n  }\n]\n    at Procedure.parseInput
`
As a newcomer it is helpful to add the `transformer` option in there like you do in other places in the documentation to avoid this issue
> chore: update ssr documentation to include transformers

- examples/next-prisma-starter-websockets/src/pages/index.tsx
- examples/next-prisma-todomvc/src/pages/[filter].tsx
- www/docs/further/subscriptions.md
- www/docs/main/example-apps.md
- www/docs/nextjs/ssg.md
- www/docs/nextjs/starter-projects.md
See: #1720
Other links that could be converted into template repo:
- https://github.com/trpc/trpc/tree/main/examples/standalone-server
- https://github.com/trpc/trpc/tree/main/examples/fastify-server
- https://github.com/trpc/trpc/tree/main/examples/express-server
> Replace example project links with template links

- www/docs/server/api-gateway.md
The new documentation for the API Gateway adapter includes an invalid import. Note that 9.25.0 actually includes a folder `adapters/api-gateway` but it seems like some left over that should have been cleaned before 9.25.0 was released.
Before people start using the adapter it could be worth considering if it should be called `aws-lambda` or `aws-api-gateway` instead. Prefixing with `aws` makes it clear where this adapter can be used. Note that the documentation consistency calls this an Amazon API Gateway adapter, but the code mainly calls it `lambda`. 
FYI @Lilja
> Correct import in API Gateway documentation

- packages/server/src/TRPCError.ts
Temp fix until we can change this in the next major.
Tired of getting this bug report which is resolved in the next branch.
- Fixes #1976
- Fixes #1588
> fix typescript warnings for typescript `>=4.6.0`

- www/docusaurus.config.js
- www/package.json
- www/src/pages/index.tsx
- www/tsconfig.json
- www/yarn.lock
This PR brings the following changes:
- Adds typescript into the docusaurus website and configures it.
- Migrates the landing page from `index.js` to `index.tsx`
- Upgrades `react-github-btn` to contain children as a prop in the type defs (see: https://github.com/ntkme/react-github-btn/commit/aae7f3db6f30139e9c70d11ef0412e7f1ee5ee18)
- Types the docusaurus configuration file so that autocomplete works.
- Removes imageUrl from the `Feature` component as that none of the features use the prop and it leads to typescript errors.
> feat(www): migrates docusaurs app to use typescript

- .github/workflows/codeql-analysis.yml
https://github.com/trpc/trpc/issues/1955
Migration strategy: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> Update codeql-action to version 2

- www/docs/main/awesome-trpc.mdx
I am the maintainer of the [@h4ad/serverless-adapter](https://github.com/H4ad/serverless-adapter) library which is a library for connecting APIs with serverless environments like AWS, Huawei and many others.
This PR adds my library to the resource list for anyone who wants to connect APIs built with tRPC with event sources like AWS SQS, AWS API Gateway or even with FunctionGraph on Huawei.
In theory my library removes the need for `@trpc/server/adapters/aws-lambda` but I don't know what plans you have for your internal integrations, what do you think?
> docs: added @h4ad/serverless-adapter to collection of resources

- examples/next-prisma-starter/src/server/routers/_app.ts
- examples/standalone-server/src/server.ts
- packages/client/src/createTRPCClient.ts
- packages/react/src/createReactQueryProxy.tsx
- packages/server/src/core/index.ts
- packages/server/src/core/router.ts
- packages/server/src/deprecated/interop.ts
- packages/server/test/___testHelpers.ts
- packages/server/test/children.test.ts
- packages/server/test/useQuery.test.tsx
- scripts/generateBigBoi.ts
Replace the `children` property/api with nested/recursive procedures:
```ts
const router = t.router({
procedures: {
foo: t.procedure.query(() => 'bar'),
child: t.router({
procedures: {
childQuery: t.procedure.query(() => 'asd'),
grandchild: t.router({
procedures: {
foo: t.procedure.query(() => 'grandchild' as const),
mut: t.procedure.mutation(() => 'mut'),
},
}),
},
}),
},
});
```
> replace children with nested routers

- www/docs/main/awesome-trpc.mdx
Added [create-t3-app](https://github.com/nexxeln/create-t3-app) to awesome-trpc section.
Should I put the GitHub repo link or is the landing page link fine?
> docs(awesome-trpc): add create-t3-app to awesome trpc

- www/src/pages/index.tsx
A tiny styling fix that is currently causing a side scroll on the index page of the site on mobile devices, as can be seen below. Although phones are obviously not the main demographic of a documentation website, it's an easy fix! I've changed the flex-direction to column for small devices, avoiding the side scroll. Keep up the good work! 🙌
**Before:**
**After:**
> Fixing docs responsiveness of features section

- www/docs/server/error-handling.md
> Fix typo in documentation

- www/docs/client/vanilla.md
Hey, great project you have there!
The TS imports should probably go without the `.ts` at the end. (ts2691)
Kind regards,
Niklas
> Fix incorrect imports in vanilla client setup docs

- examples/express-server/package.json
- examples/lambda-api-gateway/package.json
- examples/standalone-server/package.json
Changing the `package.json` files in examples.
Closes #2073
> Chores: Examples TypeScript as devDependency

- packages/client/src/createTRPCClientProxy.ts
If we don't export `FlattenRouter` TS does some weird stuff to get the return type of `createTRPCClient`. See [this](https://pastebin.com/AuwLRu66) for what it had produced in the `.d.ts` before.
> Fix createTRPCClient

- examples/.interop/next-prisma-starter-websockets/package.json
- examples/.interop/next-prisma-starter-websockets/src/pages/_app.tsx
- examples/.interop/next-prisma-starter-websockets/src/utils/trpc.ts
> reset `./interop/examples` according to `main`

- www/docs/client/cors.md
- www/sidebars.js
I feel like other people might be interested in having a simple example of setting the fetch's "credentials" option to "include" in the client's documentation.
> Doc page for sending cookies cross-origin by editing fetch's arguments

- package.json
When [corepack](https://nodejs.org/dist/latest-v16.x/docs/api/corepack.html) is enabled, using `packageManager` will transparently download and install the expected yarn version to run the project.
It will also display an error if we try to use another package manager (as I did):
> chore(deps): use packageManager field

- .tmp/v10-docs.md
I am new here, so I might be missing something, but the `Calling procedures` example seems to be referencing some `hello` query that doesn't exist.
> docs(v10): Replace `hello` with `greeting`

- www/docs/nextjs/ssr.md
This fixes a small typo: `getStaticSiteProps` -> `getStaticProps`
> docs(ssr): Fix typo for getStaticProps

- www/docusaurus.config.js
As per issue #2203 , adding support to docausurus config file, that will render pretty minimal shy announcement bar.
Now the default announce bar is, like I said, pretty shy, so I'd be up for customizing it a bit to make it a bit more fancy and dancy, but that's of course only if you think it'd be cool.
For this I can swizzle the component and customize it further.
Without customization it looks like so
Background and font color are cusotmizable, and for this PR are taken from tailwind config.
You can render `html` inside the announcement bar `content` property.
> Add docs announcement bar

- www/docs/main/quickstart.mdx
This PR adds some clarity to the package installation for the client side to address the confusion detailed in #2218.
> Adding package installation clarity to the client side docs.

- www/docs/main/quickstart.mdx
- www/docs/nextjs/introduction.md
- www/docs/reactjs/introduction.md
Update installation snippets since react-query have tagged v4 as stable and it is not currently compatible.
> docs: add version-tag to react-query in installation snippets

- www/docusaurus.config.js
- www/src/pages/index.tsx
- www/tailwind.config.js
This pull request changes the following:
- Syncs both docusaurus and tailwind to be on dark/light mode based on system preferences and disables manual docusaurus theme toggling that way both docusaurus and tailwind will always be on light/dark mode together.
- This allows the ability to use the `dark:` class name prefixes of tailwind and for them to work as expected again.
> fix(www): sync docusaurus and tailwind dark mode 

- www/docs/server/infer-types.md
Sorry, OCD was killing me about this..
so i fixed the indentation...
> fix(docs): double slash comment was misaligned

- www/docs/further/rpc.md
Removes a duplicate `a` in rpc.md.
> docs: Remove duplicate word in rpc.md

- www/package.json
- www/src/components/GithubStarCountButton.tsx
- www/yarn.lock
Discussed on Discord: https://discord.com/channels/867764511159091230/1001593966237585459
On some i18n systems the `react-animated-numbers` has a bug and renders the wrong number.
I cut an issue out for this: https://github.com/heyman333/react-animated-numbers/issues/34, but until they fixed that we should probably disable the includeComma flag since that seem to be the culprit both from debugging and from reading the internal source of react-animated-numbers.
---
_Note: I also removed the BrowserOnly stuff, didn't seem to do anything on my side and it is working as expected on my end without it (at least locally, we'll see when it deploys...)_
> docs: Fix Github Star on some i18n

- www/docs/reactjs/introduction.md
Previously, the docs just created the regular hooks, but later showed usage using the proxy.
> docs: update react intro

- .github/workflows/examples.yml
- examples/express-minimal/README.md
- examples/express-minimal/package.json
- examples/express-minimal/src/client.ts
- examples/express-minimal/src/router.ts
- examples/express-minimal/src/server.ts
- examples/express-minimal/tsconfig.json
Related discussion: #2325 
As pointed out in that discussion, there isn't really a minimal example that "follows the docs" (For usage with Next there is #2169). This implements just that:
`A simple router without any of the fancy functions exposed by a single express endpoint and consumed by the vanilla trpc client.`
> examples: Add a more minimal express example

- www/src/components/Features.tsx
- www/src/components/GithubStarCountButton.tsx
- www/src/css/custom.css
- www/src/pages/index.tsx
this commit brings the following changes:
- Adjusts some spacings between sections.
- Gives the sponsor section a title and a description with a link to sponsoring.
- Makes the sponsors smaller.
- Moves the Alex quote title outside of the blockquote.
- Changes the website primary colour to be that of the new logo.
- Changes the colour of the github star count button to be more minimal.
- Changes the colours of the feature section icons.
> feat(www): adjusts spacing and colors of landing page

- .github/labeler.yml
Closes #
- excluded `package.json` from labeler. PRs got littered with every single label cause of the version syncing when updating one package. this fixes that. see example run here: [juliusmarminge/trpc#1](https://github.com/juliusmarminge/trpc/pull/1). now only the relevant label is assigned
> fix labeler

- .github/pull_request_template.md
Closes #
Contribution guide link works fine in the [template itself](https://github.com/trpc/trpc/blob/main/.github/pull_request_template.md), But when creating a PR it leads to Github's root url
```
https://github.com/CONTRIBUTING.md => https://github.com/about/careers
```
> fix(PR-Template): Update Contributing guide link

- www/docs/reactjs/ssg-helpers.md
Here are three updates for the SSG helpers docs.
- Use a real example of filling the `ctx` field via `await createContext()`.
- Remove `await` when calling `createSSGHelpers`, as it is not async.
- Replace `fetchQuery` with `prefetchQuery` and add a comment to mention their use cases.
> Update SSG helpers docs

- package.json
- packages/react/package.json
- packages/react/src/ssg/index.ts
- packages/react/src/ssg/ssg.ts
- packages/react/src/ssg/ssgProxy.ts
- packages/server/package.json
- packages/server/test/react/ssg.test.ts
- rollup.config.ts
- www/docs/nextjs/ssg.md
- www/docs/reactjs/ssg-helpers.md
- yarn.lock
Closes #2450
cc @juliusmarminge
```ts
import { createProxySSGHelpers } from '@trpc/react/ssg'
const ssg = createProxySSGHelpers({
router: appRouter,
ctx: {},
})
await ssg.post.list.prefetch()
```
I also switched back to `rollup-plugin-typescript2` because the `@rollup/plugin-typescript` was erroring that there was an excessively deep type when there wasn't.
> add proxy ssg helpers

- www/docs/reactjs/useInfiniteQuery.md
Hello, I was reading the docs and found a slight problem.
According to the [React Query docs](https://react-query-v3.tanstack.com/guides/infinite-queries), react query knows if an infinite query is over if it receives undefined in getNextPageParam :
>A hasNextPage boolean is now available and is true if getNextPageParam returns a value other than ***undefined***
In the example in the docs the cursor instead returns `null`, causing React Query to repeat the results.
`let nextCursor: typeof cursor | null = null;`
` getNextPageParam: (lastPage) => lastPage.nextCursor,`
This confused me so I'm proposing this fix.
Change null to undefined in the useInfiniteQuery.md example
`let nextCursor: typeof cursor | undefined = undefined;`
> Documentation fix: useInfiniteQuery

- www/docs/nextjs/introduction.md
- Modifies code example for generating the Next.js custom App component
- Uses `function` instead of typed `const` which follows the example from the official [Next.js documentation](https://nextjs.org/docs/basic-features/typescript)
- Get rid of the `next/dist/shared/lib/utils` import which could look somewhat hacky / suspicious for new users.
> docs: Create Next.js custom App as function

- www/src/css/custom.css
Closes #2499 
"Disables" hover tooltips for Shiki Twoslash. Now only what we explicitly show is displayed.
> hide noisy shiki

- packages/server/src/adapters/ws.ts
- packages/server/src/core/errors.ts
- yarn.lock
We caught the following error on our production:
I believe those malformed requests come from some vulnerability scanners. In either case, such requests should not crash the instance. During the investigation I found this discussion: https://github.com/websockets/ws/issues/1354#issuecomment-774616962, and started to look into the way of handling the error. It seems there is no other way to inject this handler, so here is the PR. I have tested it already and it prevents the crash of the nodejs process.
> fix: Handle WebSocket errors to avoid Node.js crashes

- packages/server/src/http/resolveHTTPResponse.ts
Closes #
Fixes input-less mutation procedures.
> Fix parsing input-less mutation on resolveHTTPResponse

- .gitignore
- .tmp/v10-docs.md
- README.md
- www/.gitignore
- www/docs/main/awesome-trpc.mdx
- www/docs/main/example-apps.md
- www/docs/main/quickstart.mdx
- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/docs/nextjs/introduction.md
- www/docs/nextjs/ssg.md
- www/docs/nextjs/ssr.md
- www/docs/reactjs/introduction.md
- www/docs/server/express.md
- www/docs/server/fastify.md
- www/docs/server/fetch.md
- www/docs/server/output-validation.md
- www/docusaurus.config.js
- www/package.json
- www/src/css/custom.css
- www/src/pages/index.tsx
- www/vercel.json
- www/versioned_docs/version-9.x/main/quickstart.mdx
- www/versioned_docs/version-9.x/nextjs/introduction.md
- www/versioned_docs/version-9.x/nextjs/ssg.md
- www/versioned_docs/version-9.x/nextjs/ssr.md
- www/versioned_docs/version-9.x/reactjs/introduction.md
- www/versioned_docs/version-9.x/server/express.md
- www/versioned_docs/version-9.x/server/fastify.md
- www/versions.json
- yarn.lock
Prepare for releasing v9 alpha.
- Make all routes on www prefixed
- Only show announcement bar if v10 is selected + make it non-dismissable
- Redirect `/docs/*` -> `/docs/v9/*`
> fix v9 docs

- packages/client/src/createTRPCClientProxy.ts
I want this so I can build things with my own wrappers around the created proxy client.
Feature adds `export inferRouterProxyClient<TRouter>`
> Add `inferRouterProxyClient` type to `@trpc/client`

- www/versioned_docs/version-9.x/nextjs/introduction.md
Closes #
To learn trpc, I tried to create trpc with the next.js application. But I get the following error: ``` error - ./node_modules/@trpc/next/dist/trpc-next.esm.js:8:0
Module not found: cannot resolve 'react-query' ```. Only when I installed `react-query` did it starts working without any problems. I opened this PR because I thought this would be useful for other developers.
- [ x ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ x ] If necessary, I have added documentation related to the changes made.
- [ x ] I have added or updated the tests related to the changes made.
> chore: add react-query instead of @tanstack/react-query

- www/docs/reactjs/ssg-helpers.md
Updated the docs, section SSG Helpers -> 'createProxySSGHelpers' is not an async function, so I removed the async from the example in the docs.
> Update ssg-helper: remove await from createProxySSGHelpers

- www/src/components/Preview.tsx
This PR changes the following:
- Adds the `playsInline` attribute to the mp4 v10 previews so that it works on safari mobile.
> feat(www): adds playsInline to mp4 previews

- packages/client/src/createTRPCClientProxy.ts
> fix: rm unused `type`

- packages/server/src/core/index.ts
- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/middleware.ts
- packages/server/src/deprecated/interop.ts
Unblocks https://github.com/jlalmes/trpc-openapi/issues/73.
> @jlalmes - (`trpc-openapi`) I need to monkey-patch `z.void()` inputs to `z.object({})`, this was easy in v9 because I just overwrite the `parseInputFn`. However, in v10 the input parser exists inside the `middlewares` as an `ProcedureBuilderMiddleware` type, therefore my plan is the hot-swap the `inputMiddleware`.
> @KATT - happy to "tag" the middleware somehow to make it easy to detect. happy to expose the `createInputMiddleware` but it should be `@internal` and might break.
* Exposes `createInputMiddleware` (`@internal`)
* Tagged the input & output middlewares.
> feat: expose `createInputMiddleware`

- www/docs/server/context.md
Closes #
from
```
export const t = initTRPC.context<Context>.create();
```
to:
```
export const t = initTRPC.context<Context>().create();
```
> fix(docs) typo on initTRPC context call

- packages/client/src/internals/TRPCClient.ts
- packages/next/src/withTRPC.tsx
- packages/react/src/createReactQueryHooks.tsx
- packages/react/src/internals/context.tsx
Closes https://github.com/trpc/trpc/issues/2612
Wanted to get feedback before I commit to tests / documentation
Adds a global option to enable cancelling requests on unmount globally(defaults to false) with the option to override per request. I struggled to find a good place to put this so please let me know if you think theres somewhere else better.
```ts
// cancel at the global level
export const trpc = setupTRPC<AppRouter, SSRContext>({
config() {
return {
// ...
abortOnUnmount: true,
// ...
};
},
});
// cancel at the request level (overrides global config)
trpc.todos.get({ id: 1}, { trpc: { ssr: false, abortOnUnmount: false } })
```
> make react query cancellation configurable

- www/docs/client/aborting-procedures.md
- www/docs/nextjs/introduction.md
Closes [#2632](https://github.com/trpc/trpc/issues/2632)
Adds docs for `abortOnUnmount`
- need help with tests
- removes type annotations that were `any` and will raise a separate issue (https://github.com/trpc/trpc/issues/2648)
> adds docs for abortOnUnmount

- www/src/components/Button.tsx
- www/src/pages/index.tsx
- Tighten button more
- ~Apparently `<iframe`s steal focus whenever the URL change so I added the `sandbox` attribute that I didn't know existed~
- Hide sandbox on mobile
> fix: tighten button more + remove `iframe` autofocus

- examples/next-prisma-starter/src/utils/trpc.ts
- packages/client/src/createTRPCClientProxy.ts
- packages/react/src/createTRPCReact.tsx
- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/internals/utils.ts
- packages/server/src/core/procedure.ts
- packages/server/src/deprecated/router.ts
- packages/server/src/types.ts
- www/docs/nextjs/ssr.md
- www/versioned_docs/version-9.x/nextjs/ssr.md
Two main tweaks to improve performance. I must admit, I am not certain about how necessary the `{ _mutation: true }` vs `{ _type: "mutation" }` one is to improving the outcome. The main culprit seems to be `OmitNeverKeys`
All measurements done via my environment's
```sh
./build-and-link-trpc.bash && rm ./edge_worker/tsconfig.tsbuildinfo && pnpm -C edge_worker exec tsc --noEmit --generateTrace src
```
Also see https://github.com/trpc/trpc/pull/2687 where I played with interfaces
> perf: Remove OmitNeverKeys extra computations

- www/docs/main/awesome-trpc.mdx
This was done previously in #2509 but it was removed when the docs were updated to be versioned. Confirmed this example is for tRPC v10 and latest SvelteKit.
Add a link to a simple example of tRPC v10-alpha (w/ Fetch Adapter) + SvelteKit + Tailwind CSS to the Awesome tRPC Collection doc.
> tRPC v10 (w/ Fetch Adapter) + SvelteKit example

- www/docs/server/context.md
Added an export to the Context type so it can be properly imported in the "routers/_app.ts" file in the example code
> [docs/www] Small fix to context docs example code

- packages/next/src/withTRPC.tsx
Closes #2693
change to public import of `@trpc/client`
> fix createTRPCNext types

- www/docs/landing-intro/Step1.md
- www/src/components/Button.tsx
- www/src/components/QuickIntro.tsx
Add border & shadow around `QuickIntro`. Feels a bit better I think, esp on mobile to have it in a container so one knows where it starts and ends
> www: add border & shadow around `QuickIntro`

- examples/next-prisma-starter/README.md
Closes #
The command `yarn db-nuke` no longer exists in [`package.json`](https://github.com/trpc/trpc/blob/c88edc3b8453d949954e7b40300bfd58411e8873/examples/next-prisma-starter/package.json#L11) for the `next-prisma-starter` example even though it is listed in the `README`.  
It seems to have been changed to `yarn db-reset` so this PR fixes this to show the correct command in the README! 👍
> Fix changed `yarn db-reset` command in `next-prisma-starter` example `README`

- packages/client/src/TRPCClientError.ts
- packages/client/src/createTRPCClient.ts
- packages/client/src/createTRPCClientProxy.ts
- packages/client/src/internals/TRPCClient.ts
- packages/react/src/createTRPCReact.tsx
- packages/react/src/shared/hooks/createHooksInternal.tsx
- packages/react/src/shared/proxy/utilsProxy.ts
- packages/react/src/ssg/ssgProxy.ts
- packages/server/src/core/index.ts
- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/procedure.ts
- packages/server/src/core/router.ts
- packages/server/src/core/types.ts
- packages/server/src/deprecated/interop.ts
- packages/server/src/http/resolveHTTPResponse.ts
- packages/server/src/shared/index.ts
- packages/server/src/types.ts
- scripts/generateBigBoi.ts
- scripts/generateMergeRouters.ts
Remove the filtering for `queries`, `mutations`, and `subscriptions` from the v10 router. Interop routers now inject those properties like they do for `legacy`. This also makes it so we do not have to filter them out on the client.
Delete `OmitNeverKeys`. Instead of that, `Filter` for the properties we want. 
Before:
After:
TRACES FROM a `create-t3-app` WITH 50 ROUTERS FROM `generateBigBoi.ts`.
<details>
<summary>Code tested</summary>
<br>
```ts
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import styles from "./index.module.css";
const Home: NextPage = () => {
const { data } = trpc.r0.greeting.useQuery({ who: "from tRPC" });
const utils = trpc.useContext();
utils.r49.greeting.invalidate();
utils.r44.greeting3.setData('hello from …
```
> turbo types

- www/docs/migration/migrate-from-v9-to-v10.mdx
fixed a typo, where it was `update` instead of `updated`
> fix: typo for migration docs

- examples/next-prisma-starter/prisma/migrations/20220918091608_pagination/migration.sql
- examples/next-prisma-starter/prisma/migrations/20220918134120_revert/migration.sql
- examples/next-prisma-starter/prisma/schema.prisma
- examples/next-prisma-starter/src/pages/index.tsx
- examples/next-prisma-starter/src/server/routers/post.ts
- examples/next-prisma-starter/src/utils/trpc.ts
- www/vercel.json
Adds pagination and simplifies post submission on the `next-prisma-starter`
- https://nextjs.trpc.io/ is slow and has too many posts
- An infinite pagi example as part of the ref project doesn't hurt
> add pagination to next.js example

- www/docs/nextjs/introduction.md
Closes #
This change adds `import { httpBatchLink } from '@trpc/client';` to the "Usage with Next.js" example code.
> docs: fix missing import in Next.js docs

- examples/next-prisma-starter/src/utils/trpc.ts
Closes #
Updated the docs link used in the `examples/next-prisma-starter/src/utils/trpc.ts` file around why client headers were being passed through. The comments were linking to two `localhost` links, one for SSR and another specifically for headers that is a page that doesn't exist. 
Updated to the correct current docs link.
> Update tRPC docs link for SSR Headers in example

- www/README.md
Closes #
replace `yarn` with `pnpm` in the docs README commands
> fix(www): use pnpm in README commands

- www/docs/nextjs/ssg-helpers.md
- Replace `fetch` with `prefetch` and add a comment to mention their use cases.
We now use `prefetch` instead and also show a small explanation for the difference.
- Import statement for the context creation function
- Use a real example of filling the `ctx` field via `await createContext()`.
This makes sure to await the context creation when using the SSG helpers in `v10`.
I'm not sure if this is really needed regarding the implementation, but without it, there's a TypeScript error:
For reference, this is how my `createContext` function looks like:
```ts
import * as trpc from '@trpc/server'
import * as trpcNext from '@trpc/server/adapters/next'
import { prisma } from '../prisma/prisma'
/**
* Creates context for each incoming request.
* Will be available in all resolvers.
*
* @link …
```
> docs(ssg-helpers): Improve SSG helpers with `prefetch` vs. `fetch` and real context creation

- www/versioned_docs/version-9.x/client/header.md
Closes #
Fixed a small typo when I was going through the docs. So I thought I'd change it immediately. Changed the word customize to customized because of the setting of the sentence.
- [✅] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [✅] If necessary, I have added documentation related to the changes made.
- [✅] I have added or updated the tests related to the changes made.
> Changed 'customize' to 'customized'(Typo fix)

- www/docs/server/error-formatting.md
There's a dangling inline semicolon, which makes the statement invalid TS code.
See: [TS Playground](https://www.typescriptlang.org/play?#code/PTAEFMCdIe0gocAPADnALqAxjAdgZ00wF5QBLXM9AFQCUAFAYQDodd1l0AeRvDpdAD4AFAEpWkcAEMOwgN7xQEaHABicALYyOkeaHwALKSnAAaZbEigAvqNAKlSyegCukXPcWOlzX4eNmXt4AJjJSAFye3t6+zP4mzKHoUqZB0QBeMMEAoiqQ4WnRFnCsWeCgxJWgAOQAQgCCACIA+rTZAIoAqtkAytTVoABkg4XRUJasUi745RSEUrhY4DAAZqAAWlm5lqNFAPzFkJPT4MwrADba4Lhiu9GRuC7n56lFIKAwMCj4o9YA3Gl-l5rPBbPB4O8pM9QABzT7BRCoDDYPCEUAkciUGgMFhsfjcXjsTgicRYSQycDyLzjNSaK66OT6Iwmcw0qy2KKOZxuDwOaKxeKBIpJCKcooC5mnEWvIqgTI5PIFWWONmlYLlSqkOpNVodbp9AbDO5KVVYKYzTHzRbLNabBU7ZXeA6m82nC5XG6iY2OB5PF6jd4rMhIcDBIq-GVKIFR0GiIA)
Btw: Is there any explanation what exactly this error formatting is doing? A small sentence or a screenshot would be really nice, …
> docs(error-formatting): Fix invalid TS code (dangling semicolon)

- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/docs/nextjs/introduction.md
Closes #
- note that `queryClient` is no longer exposed through context
- note that `createTRPCNext` is v10-exclusive and cannot be used with interop
> docs: tweaks

- packages/next/package.json
- pnpm-lock.yaml
- rollup.config.ts
Closes https://discord.com/channels/867764511159091230/1025097593807712276/1025097593807712276
Make swc use `Object.assign` instead of the `_extends` helper for props that are spread. This makes it so we don't need any helpers.
> remove dependence on `@swc/helpers`

- packages/react/src/createTRPCReact.tsx
- packages/react/src/shared/hooks/createHooksInternal.tsx
- packages/react/src/shared/types.ts
- packages/server/test/react/useMutation.test.tsx
- packages/server/test/react/useQuery.test.tsx
Closes #2915
add `trpc` prop to hooks' return
- Gives us the ability to do stuff dynamically based on the path
> feat: add `trpc` prop to hooks' return

- packages/react/src/shared/proxy/utilsProxy.ts
- packages/server/test/react/useQuery.test.tsx
- packages/server/test/regression/issue-2942-useInfiniteQuery-setData.test.tsx
Closes #2942
- Not done, only added failing test
- ~~Maybe @sachinraja or @TkDodo could help understanding what's going on~~ nvm, i think i fixed it
- Extra context: one of the new tests in the repro (w/o input) works, the other one doesn't
- Might be that we have some types that are lying
- Can't find any docs for `setInfiniteQueryData` but there are some for [`setQueryData`](https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientsetquerydata)
> fix `setInfiniteData`

- www/docs/nextjs/introduction.md
Everywhere else in the docs has moved to this `publicProcedure` naming, this example in the Next.js intro seems to have been overlooked
> docs: consistent publicProcedure naming

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/types.ts
- packages/server/test/input.test.ts
alternative to #2958
- https://www-git-sachin-simplify-trpc.vercel.app/docs/v10/procedures#multiple-input-parsers, versus
- https://trpc.io/docs/v10/procedures#multiple-input-parsers
If I had to guess as to why this works, it's because TypeScript is being forced to evaluate the conditional type. I have no idea why those specific conditions were picked though.
> simplify type merging output

- .vscode/settings.json
Minor (visual) contrast fix for the title bar in VS Code.
| Before | After |
| --- | --- |
| ![before-active](https://user-images.githubusercontent.com/5488190/195444611-f066302b-344d-4163-a72c-5e1ae3b8534f.png) | ![after-active](https://user-images.githubusercontent.com/5488190/195444618-3659369c-83be-42d6-8cfa-fd3943583ddb.png) |
| Before | After |
| --- | --- |
| ![before-inactive](https://user-images.githubusercontent.com/5488190/195444632-06609cbf-ac06-4e90-9f52-647457d4e9fd.png) | ![after-inactive](https://user-images.githubusercontent.com/5488190/195444643-1bf6240a-afbd-4256-8848-3f156c1d4ebe.png) |
> chore: improve VS Code title bar contrast

- packages/server/src/internals.ts
Closes #2994
Cont. of #2995
Export `RootConfig`, so TypeScript does not complain about not being able to name an inferred type.
Similar to (and builds on top of) https://github.com/trpc/trpc/pull/1958.
Unsure if this can be captured in a test somehow, as it seems to rely on a more modern `moduleResolution`?
> fix(router): allow naming of inferred type

- packages/react/src/index.ts
Similar to #2999, this time for `@trpc/react`.
Under `"moduleResolution": "Node16"` (or `"NodeNext"`), compilation of TypeScript types for the router can fail with error
```
TS2742: The inferred type of 'trpc' cannot be named without a reference to './node_modules/@trpc/react/dist/createTRPCReact.js'. This is likely not portable. A type annotation is necessary.
```
https://stackblitz.com/edit/trpc-react-inferred-type-cannot-be-named?file=index.ts&view=editor
Export `CreateTRPCReact`.
> fix(react): allow naming of inferred type

- www/docs/nextjs/introduction.md
Closes https://github.com/trpc/trpc/issues/3023
`zod` has been added to the installation dependencies list used for the NextJS setup, so a user following the steps does not need to review the installation and add it manually.
> Add Zod to installation deps list in NextJs introduction

- .github/labeler.yml
Fix missed refactor from `@trpc/react` -> `@trpc/react-query`
Closes #
> Fix missed refactor

- packages/server/src/adapters/aws-lambda/index.ts
- packages/server/test/adapters/awsLambda.test.tsx
- packages/server/test/adapters/lambda.utils.ts
Hi @trpc team!
(previously filed as #3033)
I started using tRPC recently, and found it pretty magical. Just wanted you to know that what you're working on is very cool. While giving it a spin, something came up.
It turns out that request bodies of mutations (POST) may get base64-encoded by the API Gateway Lambda Proxy integration. When that happens, a TRPCClientError like this will be thrown:
```
TRPCClientError: Unexpected token e in JSON at position 0
{
message: 'Unexpected token e in JSON at position 0',
code: -32700,
data: {
code: 'PARSE_ERROR',
httpStatus: 400,
stack: 'TRPCError: Unexpected token e in JSON at position 0\n' +
'    at getRawProcedureInputOrThrow (/var/task/dist/index.js:34581:11)\n' +
'    at Object.resolveHTTPResponse (/var/task/dist/index.js:34661:22)\n' +
'    at …
```
> Fix: Detect and support APIGatewayProxyEvent isBase64Encoded

- examples/next-prisma-starter/render.yaml
The changes in this PR are related to the `next-prisma-starter` template. When I tried to deploy on Render, the healthcheck failed.
I changed the `healthCheckPath` property in the Render blueprint file to match the path defined in `routers/health.ts`.
This should make Render deploys succeed.
> fix(next-prisma-starter): render healthcheck path

- examples/next-prisma-starter-websockets/src/server/context.ts
- packages/server/src/core/initTRPC.ts
- packages/server/src/core/internals/config.ts
- packages/server/src/deprecated/router.ts
When using trpc v10 outside of a server environment, `process` may be undefined. We can pass `isServer: false` in the RuntimeConfig, but the default `isServer` value is created in the module scope regardless, so the `process.env` check will throw.
This simply changes `process.env.VAR` to `globalThis.process?.env?.VAR` where applicable to support non-server environments.
> fix: use optional chaining for `process.env`

- .github/pull_request_template.md
- www/docs/main/example-apps.md
Fix broken link to minimal example in the latest v10 docs. Also, fix a link to the `CONTRIBUTING.md` in the PR template since it looks outdated. (sorry if this is intentional.)
> fix(www): broken link to minimal example in the v10 docs

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/types.ts
- packages/server/test/input.test.ts
Closes #2980
Properly merge input parser properties.
Example:
```ts
const router = t.router({
proc: t.procedure
.input(
z.object({
id: z.string(),
}),
)
.input(
z.object({
id: z.string().optional(),
otherKey: z.number()
}),
)
.query(() => 'hi'),
});
const client = createTRPCProxyClient<typeof router>({
links: [],
});
// @ts-expect-error id is not optional
client.proc.query({ otherKey: 5 })
// must pass a string
client.proc.query({ id: 'foo', otherKey: 6 })
```
Types are intersected rather than overridden. I like this method better than `ErrorMessage` because it mirrors exactly what is happening internally. I think we'd also continue to struggle with proper merging if we don't end up using the type in this PR.
> merge input parsers

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
🎯 Changes
If a custom `reactQueryContext` then in the invocation of useMutation the useQueryClient didn't receive the custom reactQueryContext
✅ Checklist
> fix: pass ReactQueryContext to useQueryClient in useMutation

- www/docs/reactjs/useContext.mdx
didn't revert my cache test
updated output folder on vercel so this should hit
> fix: typo from testing www cache

- packages/next/src/createTRPCNext.tsx
- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/interop.ts
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/shared/proxy/decorationProxy.ts
- packages/react-query/src/shared/types.ts
- packages/tests/server/react/__reactHelpers.tsx
- packages/tests/server/react/useQuery.test.tsx
- www/docs/reactjs/suspense.md
Closes #1354
- Adds experimental `useSuspenseQuery()` 
- It is **feature-flagged** as the exact implementation might change & we're waiting to see how the `react-query` team on how they're planning to deal with it
- Live demo: https://github.com/KATT/useSuspense-next-prisma-starter
```tsx
const trpc = createTRPCReact<
AppRouter,
unknown,
'ExperimentalSuspense' // <------------- This is the magical feature flag
>();
```
The above will give you access to a new fresh hook:
```ts
const [data] = trpc.post.byId.useSuspenseQuery({ id: "1" })
//      ^? will be typeeeed and no loading state stuff
```
> add experimental `useSuspenseQuery()`

- CONTRIBUTING.md
Closes #
Just add the `pnpm build` command before you run `pnpm dev`. I had this problem when trying to run the project so I imagine it can be useful for other devs who are trying to contribute.
> contributing.md: add build command before running pnpm dev

- www/docs/main/awesome-trpc.mdx
Adds `trpc-koa-adpater` (https://github.com/BlairCurrey/trpc-koa-adapter) to list of  `🧩 Extensions & community add-ons` per @KATT 's suggestion in https://github.com/trpc/trpc/issues/3094
Re-opened per instructions in #3131
> docs: add trpc-koa-adapter

- examples/next-prisma-starter/playwright.config.ts
- examples/next-prisma-starter/playwright/smoke.test.ts
Fixes #3121
Fix e2e tests by removing `test.setTimeout` from the top of the file and adding timeout to playwright config file.
> Fix e2e tests in `next-prisma-starter`

- packages/server/src/internals.ts
Since https://github.com/trpc/trpc/pull/2031, I went back to trpc and noticed that my build is broken because `AnyRootConfig` needs to be exported in order to generate type definition files for my package.
As a reminder, this is necessary to avoid these errors:
```bash
src/config/trpc/index.ts:5:14 - error TS2742: The inferred type of 't' cannot be named without a reference to '../../../../../node_modules/@trpc/server/dist/core/internals/config.js'. This is likely not portable. A type annotation is necessary.
5 export const t = initTRPC.context<Context>().create();
~
Found 1 error in src/config/trpc/index.ts:5
```
> fix(types): export AnyRootConfig from internals

- .github/workflows/examples-old-nodes.yml
- .github/workflows/examples.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
Github is deprecating their `set_output` api and replacing it with environment files:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This suppresses these warnings:
Also fixed another warning I saw the other day
> ci: use new environment output api

- www/blog/2022-11-21-announcing-trpc-10.mdx
Closes #
The shoutout sentence didn't read right by doubling up!
> Fix Shoutout double up in V10 Blog Post

- packages/tests/server/adapters/next.test.ts
Related #3229 
Porting of adapter tests for v10.
Adapter test files in /adapters that should be portedr:
```│   ├── adapters
│   │   ├── __router.ts
│   │   ├── awsLambda.test.tsx
│   │   ├── express.test.tsx
│   │   ├── fastify.test.ts
│   │   ├── fetch.test.ts
│   │   ├── lambda.test.tsx
│   │   ├── lambda.utils.ts
│   │   └── next.test.ts
```
Ported:
> port: adapter tests ported to v10

- www/src/pages/index.tsx
Currently the StackBlitz iframe is broken, since it points to the `next` branch.
This PR updates the link to the `next-minimal` template used by the StackBlitz iframe.
> www: update next-minimal template iframe link

- packages/tests/server/headers.test.tsx
- packages/tests/server/rawFetch.test.tsx
- packages/tests/server/responseMeta.test.ts
Closes #
This PR ports `headers.test.tsx`, `rawFetch.test.tsx`, `responseMeta.test.tsx` to v10
> test: port headers, rawFetch, responseMeta

- www/docs/main/quickstart.mdx
Closes #
As discussed on [this tweet](https://twitter.com/tomlienard/status/1595856448608735239), this PR adds a note at the end of the Quickstart to use `superjson` if you need to support complex objects:
This is the best place I found to add this tip, but it might be worth adding it in other places too.
> docs: add tip about (de)serialization of complex objects using superjson

- www/docs/main/awesome-trpc.mdx
Closes #3190 
- Removed zART
- Added create-t3-turbo
- Moved ct3a from extensions to starting points
> docs: replace zART with create-t3-turbo and move ct3a to starting points

- packages/tests/server/validators.test.ts
Related #3229
Create tests validators.test.ts for v10.
> test: port `validators.test.ts` tests to v10

- packages/tests/server/inference.test.ts
- packages/tests/server/inferenceUtils.ts
- packages/tests/server/links.test.ts
- packages/tests/server/outputParser.test.ts
- packages/tests/server/react/withTRPC.test.tsx
Closes #
This PR ports  `inference.test.ts`, `links.test.ts`, `outputParser.test.ts`, `withTRPC.test.tsx` to v10
> test: port inference, links, outputParser, withTRPC to v10

- packages/server/src/shared/internal/serialize.ts
> hide never values in intellisense for jsonify

- www/src/pages/index.tsx
breaks some lint in another PR
> fix: rm `charset`

- packages/client/src/internals/TRPCClient.ts
- packages/tests/server/interop/regression/issue-3303-transformer.test.ts
Closes #3303
This changes so the `TRPCClient` uses the old behavior of not taking into account transformers (introduced in [10.2.0](https://github.com/trpc/trpc/releases/tag/v10.2.0)).
The `TRPCClient`'s types are not used outside of v9 stuff and are overridden by the proxy.
Technically, this is a tiny regression from `10.2.0` where some people using interop and _not_ using superjson might notice something, but it just really regressed to the behaviour the would've had a few days ago
> fix: `interop()` types not taking transformers into account

- packages/server/src/core/types.ts
- packages/tests/server/regression/serializable-inference.test.tsx
Regression from #3261 
Inferred types were serialized even when there wasn't a transformer defined
Same bug as found here: https://github.com/trpc/trpc/pull/3298#pullrequestreview-1200729879
> fix: type inference fails when not using a transformer

- www/docs/main/example-apps.mdx
* Path in the docs does not match path from the examples folder: https://github.com/trpc/trpc/tree/main/examples
* Here's the correct path: https://github.com/trpc/trpc/tree/main/examples/next-prisma-websockets-starter
I've just changed two words around so that the starter file for websockets has the correct path.
> Fix path to next-prisma-websockets-starter

- www/docs/server/router.md
`initTRPC` is not callable, as TS and the other examples show.
> fix(docs): change typo`initTRPC()` to `initTRPC`

- www/docs/reactjs/useInfiniteQuery.md
Ref: 
Hmm I see why I did that. The [docs](https://trpc.io/docs/useInfiniteQuery) say
>  Your procedure needs to accept a `cursor` input of `any` type
and while I see now `lastPage` isn't a reference to the cursor, maybe the markdown code syntax around "any" is confusing when `any` is itself a type that breaks everything.
_Originally posted by @givensuman in https://github.com/trpc/trpc/issues/3428#issuecomment-1358714783_
> fix(docs): clarify `cursor`-type in `useInfiniteQuery`

- README.md
This PR adds dark mode image for readme
https://user-images.githubusercontent.com/62795688/208726965-ae25fb93-68d0-42de-a89c-f71daa34f5e7.mp4
> readme: add dark mode image

- packages/server/src/core/internals/config.ts
- packages/tests/server/regression/issue-3453-meta-interface.test.ts
- packages/tests/server/responseMeta.test.ts
Closes #3453
We should be able to use `interface` to type `meta` & `context`
> feat(server): ability to have `context`  & `meta` as `interface`s

- .eslintrc
- .github/workflows/lint.yml
- examples/next-prisma-todomvc/src/pages/[filter].tsx
- packages/next/src/createTRPCNext.tsx
- packages/next/src/withTRPC.tsx
- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/internals/context.tsx
- packages/server/src/adapters/standalone.ts
- packages/server/src/http/resolveHTTPResponse.ts
- packages/server/src/internals/invert.ts
- packages/tests/server/adapters/fastify.test.ts
- packages/tests/server/errors.test.ts
- packages/tests/server/interop/adapters/fastify.test.ts
- packages/tests/server/interop/errors.test.ts
- packages/tests/server/interop/links.test.ts
- packages/tests/server/interop/middleware.test.ts
- packages/tests/server/interop/react/__testHelpers.tsx
- packages/tests/server/links.test.ts
- packages/tests/server/react/__testHelpers.tsx
- packages/tests/server/react/invalidateRouters.test.tsx
- packages/tests/server/react/useContext.test.tsx
- scripts/postversion.ts
- tsconfig.eslint.json
~Closes #~ [I was told to just go nuts 😄](https://discord.com/channels/867764511159091230/980118117676118067/1056705880726446130)
Enables [@typescript-eslint/recommended-requiring-type-checking](https://typescript-eslint.io/linting/configs/#recommended-requiring-type-checking), which is a set of recommended rules that also require [linting with type info](https://typescript-eslint.io/linting/typed-linting) (which was already set up).
Fixes `tsconfig.eslint.json` to properly include compiler options and path mappings so that lint rules have correct type info.
Rules with straightforward-to-fix issues have those issues fixed, with inline comments explaining the rule.
Marks rules that had a lot of non-straightforward-to-fix issues as todos. It'd be good to fix them eventually. But that's out …
> chore: enable typescript-eslint/recommended-requiring-type-checking

- packages/react-query/src/utils/inferReactQueryProcedure.ts
Bug fix which replaces an incorrect import from `@trpc/server/dist/shared` with `@trpc/server/shared`. This was causing my Typescript compiler to give the following error:
```
> tsc
../../node_modules/.pnpm/@trpc+react-query@10.7.0_x4ie6nhblo2vtx2aafrgzlfqy4/node_modules/@trpc/react-query/dist/utils/inferReactQueryProcedure.d.ts:3:49 - error TS2307: Cannot find module '@trpc/server/dist/shared' or its corresponding type declarations.
3 import { inferTransformedProcedureOutput } from '@trpc/server/dist/shared';
~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in ../../node_modules/.pnpm/@trpc+react-query@10.7.0_x4ie6nhblo2vtx2aafrgzlfqy4/node_modules/@trpc/react-query/dist/utils/inferReactQueryProcedure.d.ts:3
```
Unit tests still pass.
> fix(react-query): fix import from dist folder

- packages/client/src/internals/TRPCUntypedClient.ts
- packages/tests/server/createGenericClient.test.ts
Let's be unsafe but not unhinged
> chore(client): swap `any`-types to `unknown` on untyped client

- .wip/changes.md
- packages/react-query/src/ssg/index.ts
- packages/react-query/src/ssg/ssg.ts
- packages/tests/server/react/ssg.test.ts
continue on #3513
rename `createProxySSGHelpers` to `createSSGHelpers` - but keep an alias marked deprecated so there's no breaking changes
> chore: rename + alias ssg-helpers

- .prettierignore
- examples/next-minimal-starter/www/build/wat.js
~Closes #~ Mentioned by @juliusmarminge and @KATT that Prettier is formatting things it doesn't need to.
Adds web build directories to the `.prettierignore` file:
* `.next/` for Next.js
* `.docusaurus/` and `www/build/` for Docusaurus
> chore: add web build directories to .prettierignore

- packages/client/src/links/wsLink.ts
Closes #3539
Use the OPEN constant of the WebSocketImpl to prevent a type error in nodejs environments.
> fix(client): use constant of websocket impl

- www/docs/client/links/wsLink.md
Args for `wsLink` were incorrect on this docs page. It takes an object with the client as a key, not just the client itself. All other docs pages already have the correct args format.
> docs: fix wsLink args

- README.md
- www/src/components/sponsors/script.push.ts
- www/unversioned/_sponsors.mdx
Closes #
- After every `sync sponsor` commit, CI starts failing due to invalid formatting. This fixes that by adding the missing newline that prettier expects
> chore(sponsor-script): fix missing newline causing prettier errors

- www/docs/server/procedures.md
Closes #
Just a small fix for typos in "Define Procedures" page
> docs: fix typo in procedures page

- packages/react-query/src/shared/proxy/useQueriesProxy.ts
- packages/tests/server/react/useQueries.test.tsx
Previously, the `useQueries` hook ignored the query options parameter. I fixed the typo that caused it and added a test.
Edit: made [this](https://github.com/HatulaPro/showing-usequeries-bug) to better explain the issue.
> fix(react-query): `useQueries()` no longer ignoring query options

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/tests/server/react/mutationkey.test.tsx
Closes #3534
did in https://github.com/trpc/trpc/pull/3591 but figured it should prob be made here first
Keys will be similar to queryKeys, in that it's the array path inside a tuple, although since we don't have inputs / type here its just a single item in the tuple
we could also just have the path `['post', 'create']` (not nested `[['post', 'create']]`) but better to be consistent imo
this should unlock #3528 without any modifications to the getter - although maybe we want that to be named `getMutationKey`?
> feat: leverage mutationKey in mutations

- www/docs/server/procedures.md
change router to t.router(...) on line 215. Other examples import router, but in this example the t instance is instantiated in same file, line 213.
Closes #
fix typo
- [X ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [X ] If necessary, I have added documentation related to the changes made.
> #typo fix in code sample for multiple procedures

- www/docs/main/introduction.mdx
- www/versioned_docs/version-9.x/further/subscriptions.md
We’ve not received any bug reports in a year. I think it is pretty stable.
> chore: remove the word “beta” from subscriptions docs

- packages/server/src/core/internals/utils.ts
- packages/tests/server/input.test.ts
- packages/tests/server/validators.test.ts
> fix: do not leak `UnsetMarker` to query input

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/router.ts
- packages/server/src/subscription.ts
- packages/tests/server/callRouter.test.ts
Add `@deprecated` on some types that aren't intended to be used that I had forgotten about
> chore: add `@deprecated` on some internal types

- www/docs/reactjs/useMutation.md
Closes #3625 
`mutate()` from `useMutation()` does not return a promise. We don't need `async` in the example code.
> docs: fix typo in useMutation()

- CONTRIBUTING.md
Closes #
Trpc's contributing guide had incorrect link to tests directory. Fixed it.
- [✅ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
> docs: fixed incorrect link to trpc's tests directory in CONTRIBUTING.md file

- www/docs/client/aborting-procedures.md
This PR fixes a typo in the code block on the aborting-procedures page.
> docs: fix typo on the aborting-procedures page

- packages/client/src/createTRPCClientProxy.ts
- packages/client/src/internals/TRPCUntypedClient.ts
- packages/react-query/src/internals/context.tsx
- packages/tests/server/react/regression/issue-3461-reserved-properties.test.tsx
Closes #3530
Naming a procedure something that conflicts with a `TRPCUntypedClient` property is now a type error.
> protected intersection for vanilla client

- www/docs/nextjs/introduction.mdx
Closes  #3741
- removed an unused import in the usage with next.js in the backend sample
```diff
- import { TRPCError, initTRPC } from "@trpc/server";
+ import { initTRPC } from '@trpc/server';
// Avoid exporting the entire t-object
// since it's not very descriptive.
// For instance, the use of a t variable
// is common in i18n libraries.
const t = initTRPC.create();
// Base router and procedure helpers
export const router = t.router;
export const procedure = t.procedure;
```
> docs: remove unused import in the usage with next.js documentation

- www/src/css/custom.css
- Removes some default box shadows on some elements in the search modal.
- Changes the search modal colours to better suit the website colour palette.
- Makes the algolia logo a bit smaller.
> feat(www): creates better search modal design

- packages/server/src/shared/jsonify.ts
Closes #
Simplifies output type when not using a transformer to get prettier output
Pre:
After:
> fix: add `Simplify<T>` to serialized output

- examples/deno-deploy/src/index.ts
Fix the Deno test that has been failing since two days (due to a timeout). We use the `start-server-and-test` package and they released a [new version](https://github.com/bahmutov/start-server-and-test/releases/tag/v1.15.4) two days ago that fix a bug and expects to return a status code `200` in response to a `HEAD` request on `/`, to notify that the HTTP server is ready to be tested.
However, `/` always returns a `404` status code because the tRPC server listens on the `/trpc` endpoint. I've fixed this by returning an empty `Response` (which has a `200` status code) if the request method is `HEAD` (meaning when `start-server-and-test` checks if the HTTP server is ready to be tested)
> ci: fix deno test

- packages/server/src/internals.ts
Closes #
I'm continuing my patches about exposing enough internal types to be able to have a correct inference when generating declaration files (necessary when using TS project references).
It fixes these errors:
Past PRs: https://github.com/trpc/trpc/pulls?q=is%3Apr+author%3Ajgoux+is%3Aclosed
> fix: export more internals for dts files generation

- .prettierignore
Removes unnecessary matches from `packages/coverage`, as it's ignored in `.gitignore` and never committed anyway.
> chore: Ignore packages/coverage from prettier formatting

- www/docs/server/authorization.md
Changes to the [Authorization section in the v10 docs](https://trpc.io/docs/authorization). Namely:
In the docs, the type `Context` is declared in `server/context.ts`, without being exported. However it's then imported in the code snippet in `server/routers/_app.ts` that immediately follows, so for consistency and clarity I think the type declaration in `server/context.ts` needs to be exported. This PR does that.
> docs: Export type `Context` for use in `initTRPC`

- examples/.test/internal-types-export/src/server.ts
- packages/server/src/core/index.ts
- packages/server/src/internals.ts
Closes #
This extends work by @jgoux in #3774 by exposing more internal types to ensure declaration files can be generated. 
It fixes errors caused by the interaction of context and middleware ([stackblitz](https://stackblitz.com/edit/trpc-export-ts2742-jdz415?file=index.ts&view=editor)) and when routers are created within generic functions ([stackblitz](https://stackblitz.com/edit/trpc-export-ts2742-76uvre?file=index.ts&view=editor)).
> fix: export even more internals for dts files generation

- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/interop.ts
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/shared/hooks/createRootHooks.tsx
- packages/react-query/src/shared/index.ts
- packages/react-query/src/shared/proxy/decorationProxy.ts
- packages/server/src/adapters/ws.ts
- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/deprecated/internals/procedure.ts
- packages/server/src/error/TRPCError.ts
- packages/server/src/error/utils.ts
- packages/server/src/http/resolveHTTPResponse.ts
- packages/server/src/subscription.ts
Fix circular dependency warnings emitted during every build job.
```
@trpc/react-query:build: (!) Circular dependency
@trpc/react-query:build: src/shared/hooks/createHooksInternal.tsx -> src/shared/hooks/deprecated/createHooksInternal.tsx -> src/shared/hooks/createHooksInternal.tsx
@trpc/server:build: (!) Circular dependency
@trpc/server:build: src/error/TRPCError.ts -> } -> src/error/TRPCError.ts
```
There were no functional changes to the API or public exports.
> chore: break circular dependencies between internal files

- packages/client/package.json
- packages/next/package.json
- packages/react-query/package.json
t3-app started breaking cause 10.13 required nextjs 13.2.1 (don't check the gitblame xdddd)
reverting that to be `^13.0.0` and also fixes all the trcp versions to eachother
> chore: update peers

- examples/.test/internal-types-export/src/server.ts
- packages/server/src/core/index.ts
A follow up to work by @jgoux  in #3774 and myself in #3831. This PR fixes a `.d.ts` generation issue when exporting merged routers.
The fixture project for time inference testing has been updated and will fail if `Router` isn't exported.
> fix: export 'Router' for dts files generation

- examples/minimal-react/server/index.ts
- examples/minimal-react/server/package.json
- packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts
- packages/server/src/adapters/node-http/types.ts
- packages/tests/server/adapters/next.test.ts
- packages/tests/server/adapters/standalone.test.ts
- pnpm-lock.yaml
- www/docs/server/adapter/standalone.md
- www/sidebars.js
Closes #3881 
Since this adds support to `nodeHTTPRequestHandler` directly, the change is also upstream of 
the express, next, and standalone, adapters.
I've implemented and run this against the minimal example and it works, though if the approach is acceptable some updates to documentation will probably be in order.
> feat(server): add CORS support to nodeHTTPRequestHandler, add Standalone adapter documentation

- package.json
- pnpm-lock.yaml
Closes #3924
`workspace:*` would break:
- vercel deployments of the example projects
- subtree
- linting w/ manypkg
just overriding it seems like the easiest for now
> chore: use link protocol to make sure repo always use local trpc

- packages/next/package.json
I think we don't need to be strict to 13 [yet], do we? 
I have problems upgrading my app at work b/c trpc now forces me to update the whole universe
> fix(`@trpc/next`): set `next` peer dependency to `*`

- www/docs/further/subscriptions.md
I couldnt find any other references to resolve(). it seems it might be a v9 concept that was removed in v10? I'm not sure because I've only ever used v10
> remove reference to resolve()

- packages/next/src/withTRPC.tsx
- packages/tests/server/react/withTRPC.test.tsx
Closes #3936
`withTRPC` now doesn't attempt to hydrate the page if `pageProps` is missing from the given component - this lets random components, like indivdual pages, be wrapped by the HOC to get access to the context providers.
> feat(next): allow `withTRPC()`-HOC on individual pages

- examples/.interop/next-prisma-starter/package.json
- examples/.test/big-router-declaration/package.json
- examples/.test/ssg/package.json
- examples/minimal-react/client/package.json
- examples/next-big-router/package.json
- examples/next-edge-runtime/package.json
- examples/next-minimal-starter/package.json
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/next-prisma-websockets-starter/package.json
- package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/react-query/src/internals/context.tsx
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/shared/hooks/deprecated/createHooksInternal.tsx
- packages/react-query/src/shared/proxy/utilsProxy.ts
- packages/server/package.json
- packages/tests/package.json
- packages/tests/server/react/ensureQueryData.test.tsx
- pnpm-lock.yaml
- www/docs/reactjs/useContext.mdx
Closes https://github.com/trpc/trpc/issues/3933
- Added support for https://tanstack.com/query/v4/docs/react/reference/QueryClient#queryclientensurequerydata with a new `ensureData` context helper - https://trpc.io/docs/useContext#helpers
- Bumped `@tanstack/react-query` to `^4.18.0` as this is version where `ensureQueryData` was added
- Removed unnecessary `pnpm.overrides.overrides.@tanstack/react-query` which was initially set in https://github.com/trpc/trpc/pull/2852
- Moved `nextjs` and `react-query` `peerDep` to `^4.18.0`, however personally I'd rather change it to `4.x` instead. We've had plenty of reports about `peerDep` from various environments in Sentry SDK and after years of experimentation this seems to be the most reliable and flexible way, eg.
- …
> feat(react-query): Add support for QueryClient.ensureQueryData and ensureData helper

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
Closes https://github.com/trpc/trpc/issues/3957
Prints better error message with the main `_app.tsx` is missing `withTRPC` wrapper.
I'm open to wording suggestions.
> feat(react-query): Add user-friendly message when withTRPC is missing from App

- www/docs/server/merging-routers.md
Closes #
Link: https://www-git-router-pitfall-trpc.vercel.app/docs/merging-routers#defining-an-inline-sub-router
> docs: add pitfall section for merging routers

- www/docs/server/merging-routers.md
It's not working (cc @Nsttt, see #4007)
> docs: comment out inlining sub-routers

- examples/standalone-server/src/server.ts
- packages/server/src/adapters/standalone.ts
- packages/tests/server/___testHelpers.ts
- packages/tests/server/adapters/standalone.test.ts
- packages/tests/showcase/tinyrpc.test.ts
- www/docs/server/adapters/standalone.md
Closes https://github.com/trpc/trpc/issues/4004
Refactor `createHTTPServer` to return an instance of Node's `http.Server` directly, instead of through `.server` property with an additional `listen` method on top of it.
This way we'll be able to encourage users to use built-in API directly and allow for usecases like the one with custom host in #4004
> chore(server): (breaking) return an instance of `http.Server` from `createHTTPServer` in standalone adapter

- www/docs/landing-intro/Step3.md
Closes https://github.com/trpc/trpc/issues/4059
Landing page instructions are using a standalone server, which is listening on the root path `/`, and not `/trpc`.
> docs: Fix API endpoint url in Step 3 of landing page

- examples/.interop/next-prisma-starter/src/pages/_app.tsx
- examples/next-prisma-starter/src/utils/trpc.ts
- examples/next-prisma-todomvc/src/utils/trpc.ts
- examples/next-prisma-websockets-starter/src/utils/trpc.ts
- packages/react-query/src/internals/context.tsx
- packages/react-query/src/server/ssgProxy.ts
- packages/react-query/src/shared/proxy/utilsProxy.ts
- www/blog/2023-01-14-typescript-performance-lessons.md
- www/docs/nextjs/server-side-helpers.md
- www/docs/reactjs/useInfiniteQuery.md
- www/docs/reactjs/useMutation.md
- www/versioned_docs/version-9.x/main/quickstart.mdx
- www/versioned_docs/version-9.x/nextjs/introduction.md
- www/versioned_docs/version-9.x/nextjs/ssg-helpers.md
- www/versioned_docs/version-9.x/reactjs/invalidateQueries.md
- www/versioned_docs/version-9.x/reactjs/useInfiniteQuery.md
- www/versioned_docs/version-9.x/reactjs/useMutation.md
- www/versioned_docs/version-9.x/reactjs/useQuery.md
Closes #4165 
These are not a globbed find/replace, they are a find, look up closest doc in the v4 docs, then replace. Not too much risk of a broken link 😄 
> docs: fix broken react-query links and link to correct version

- www/docs/server/procedures.md
Changed import from `scale-ts` to `scale-codec` as shown in their [readme](https://github.com/paritytech/scale-ts#setup).
> docs: fix scale-ts import statement

- packages/client/src/internals/types.ts
- packages/client/src/links/httpBatchLink.ts
- packages/client/src/links/httpLink.ts
- packages/client/src/links/internals/httpUtils.ts
- packages/tests/server/headers.test.tsx
- www/docs/client/links/httpBatchLink.md
- www/docs/client/links/httpLink.md
Closes https://github.com/trpc/trpc/issues/4071
This PR adds support for using operations in as part of the `HTTPLinkOptions.headers` used by `httpLink` and `httpBatchLink`. 
The API changes are non-breaking:
```diff
export interface HTTPLinkOptions {
url: string;
/**
* Add ponyfill for fetch
*/
fetch?: typeof fetch;
/**
* Add ponyfill for AbortController
*/
AbortController?: typeof AbortController | null;
/**
* Headers to be set on outgoing requests or a callback that of said headers
* @link http://trpc.io/docs/v10/header
*/
headers?: 
| HTTPHeaders 
-   | (()                           => HTTPHeaders | Promise<HTTPHeaders>);
+   | ((opts: { ops: Operation[] }) => HTTPHeaders | Promise<HTTPHeaders>);
}
```
Questions:
- Are we okay returning a list of operations when using the `httpLink`? …
> feat: add operations in `httpLink`/`httpBatchLink` `headers`-callback function

- www/src/theme/CodeBlock/index.js
- www/src/theme/CodeBlock/styles.css
Closes #4019
Use the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) instead of `copy-text-to-clipboard`. Unfortunately this means we have to eject from twoslash's `CodeBlock` component ([which hasn't been updated in two years anyway](https://github.com/shikijs/twoslash/blob/f3a2683d1bd7fe64f424a808dcbdbc77b686c896/packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/index.js#L10)).
> docs: fix copying code in safari

- www/docs/reactjs/useContext.mdx
Follow-up to #4268 that removes the "unstable" info.
> docs(useContext): Remove unstable info

- packages/server/src/adapters/standalone.ts
Closes #4309
Adding the missing `hostname` argument to `listen` returned from the standalone adapter.
If there are docs or tests I need to add for this, just point me in the right direction. But this is pretty trivial. :)
> Added `hostname` to `listen` in standalone adaptor.

- package.json
This option makes it so the command only spits out the names of files which it's actually made changes to. In my experience the command is also a bit faster to run without locking on the terminal for every file :)
Closes #
> chore: Add --list-different to format:write command

- www/docs/server/validators.md
This pull request fixes a grammatical error in the statement about custom validator. The word "doing" was removed since it was redundant. This change improves the clarity and readability of the codebase, and should have no impact on the functionality of the code. 
The corrected statement would be: "We don't recommend making a custom validator unless you have a specific need, but it's important to understand that there's no magic here - it's just TypeScript!"
Closes #
> docs: Fix grammar error in statement about custom validator

- www/src/theme/CodeBlock/styles.css
This change sets the `display` property of the `code` element to `inline-block`, which makes the right padding of its child `div` (class="line") elements effective and improves user experience expecially on mobile devices.
Before this change, the right padding of the `div` (class="line") elements inside the `code` element was not effective because the `code` element had a default `display` property of `inline`, which does not allow for width or height. This made some lines of code look like they were cut off especially on mobile devices since the padding-right wasn't effective. By setting the `display` property of the `code` element to `inline-block`, the element now has a width and height, and its child `div` (class="line") elements' padding is effective.
I tested this change locally by …
> Fix: Set display to inline-block for code element

- packages/client/src/links/loggerLink.ts
Closes https://github.com/trpc/trpc/issues/4339
```
// `dom.iterable` types are explicitly required for extracting `FormData` values,
// as all implementations of `Symbol.iterable` are separated from the main `dom` types.
// Using triple-slash directive makes sure that it will be available,
// even if end-user `tsconfig.json` omits it in the `lib` array.
```
/claim #4339 (Feel free to skip the payout, I just wonder if it "just works" out of the box and how it works in the first place, never heard of Algora 🤔)
> fix(client): make sure that `dom.iterable` types are included for `FormData`

- www/docs/community/awesome-trpc.mdx
tRPC-SWR now has tRPC v10 support with all SWR api's
Closes #
Adds tRPC-SWR entry back into `awesome-trpc.mdx`. This was previously removed due to missing v10 support.
> docs: Add tRPC-SWR back to Library adapters

- .github/workflows/main.yml
- package.json
- pnpm-lock.yaml
- scripts/analyzeSizeChange.ts
- scripts/getRollupConfig.ts
❗️ This PR is **still a draft**, but was created as "ready for review" by mistake. Sorry for the spam to the people who were inadvertently subscribed to this ❗️
Related to https://github.com/trpc/trpc/pull/4347
- Adding `rollup-plugin-analyzer` as a rollup build step so we remain aware of the final size of the packages being distributed
- analysis duration is negligeable compared to the rest of the build
- adding artifact upload/download so that a PR can compare size differences in CI
> chore: add `rollup-plugin-analyzer` for monitoring bundle size

- packages/react-query/src/createTRPCReact.tsx
- packages/tests/server/regression/issue-4360-useInfiniteQuery-placeHolderData.test.tsx
Ensure that `useInfiniteQuery` and `useSuspenseInfiniteQuery` use explicit types rather than inferred generic types.
Closes #4360 
Bounty: /claim #4360
This problem looks to be the result of our relying on a default generic parameter (e.g.):
```ts
function myFunction<Generic = string>() {}
```
The problem is that the way the default parameter seems to be working is that TypeScript uses the default (i.e. `string`) _unless_ it can infer the type by some other means.
In this case, we set the default value of `TData` to `inferTransformedProcedureOutput<TProcedure>`, however, by returning a _different_ type from the `placeholderData`, TypeScript tries to help us out and _infer_ the type from what it returns. This inference supersedes the default parameter type …
> fix(`react-query`): fix `useInfiniteQuery` `placeholderData` types

- packages/client/src/links/httpBatchLink/httpBatchStreamLink.ts
- packages/client/src/links/httpBatchLink/streamingHttpUtils.test.ts
- packages/client/src/links/httpBatchLink/streamingHttpUtils.ts
- packages/client/src/links/internals/httpUtils.ts
Relates to https://github.com/trpc/trpc/pull/4347
Replace usage of AsyncGenerators and AsyncIterators on the client w/ regular async and callbacks. This should allow for better retro-compatibility (and potentially better performance, though this was never measured).
Without this PR, compatibility was late-2018 and up, with this PR, compatibility should be ~2017 and up (Safari 10.1, support for `fetch`).
> 🧙 Streaming client without async generator / iterator

- .github/workflows/examples-old-nodes.yml
- .github/workflows/examples.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/subtree.yml
- .tool-versions
- examples/.interop/next-prisma-starter/.github/workflows/main.yml
- examples/next-prisma-starter/.github/workflows/main.yml
- examples/next-prisma-starter/package.json
- examples/next-prisma-websockets-starter/.github/workflows/main.yml
- examples/next-prisma-websockets-starter/package.json
- package.json
- pnpm-lock.yaml
new lockfiles from #4437 breaks deployments e.g.
https://github.com/trpc/examples-next-prisma-starter
#4456  - Would like for renovate to stop updating pnpm and node automatically, it's a bit more involved than what it is capable of
> chore: revert pnpm updrade as it breaks some example projects

- examples/deno-deploy/README.md
- examples/deno-deploy/src/client.ts
- examples/deno-deploy/src/index.ts
- examples/deno-deploy/src/router.ts
Change npm specifiers to esm.sh for deno deploy example. Deploy does not currently support npm specifiers so the previous example would not run.
> chore: change npm specifiers to esm.sh for deno deploy

- packages/server/src/adapters/fastify/fastifyRequestHandler.ts
- packages/server/src/adapters/fetch/fetchRequestHandler.ts
- packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts
- packages/server/src/http/resolveHTTPResponse.ts
Closes #
Add `unstable_` prefix to `onHead` and `onChunk` callbacks used in `resolveHTTPResponse` from the adapters. Adapters are part of the public API, so while `httpBatchStreamLink` is considered unstable, these callbacks should be too.
> chore: add 'unstable_' prefix to 'onHead' and 'onChunk' adapter callbacks

- www/docs/client/react/suspense.md
- www/sidebars.js
`useSuspenseQuery` was incorrectly being referred to as just `useSuspense`
> docs: fix useSuspenseQuery naming

- .gitignore
- lerna.json
- `.gitignore` was for some reason preventing lerna from picking up the packages correctly. This change fixes it, but still preserves the behavior that code comments said it should enforce
- cleaned up the rest of `.gitignore` a bit, especially adding `/` which makes it obvious that we want to match only directories, and not files named like so
- `publishConfig` is deprecated and not valid according to lerna's json schema
- `packages` are redundant, as when `npmClient` is set to `pnpm`, it'll use `pnpm-workspace.yaml` instead
> fix(ci): fix lerna publish task

- packages/client/src/internals/types.ts
- packages/client/src/links/internals/parseJSONStream.ts
Closes https://github.com/trpc/trpc/issues/4504
- Create `WebReadableStreamEsque` type for "web api response body", with the minimal subset of properties actually used by tRPC. This should improve compatibility across client-side environments (incl. undici fetch, like in the issue mentioned above)
- apply this new type to `ResponseEsque` type and in `parseJSONStream` functions
> fix(`client`): add minimal `WebReadableStreamEsque` for compatibility across envs

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/internals/utils.ts
- packages/server/src/core/middleware.ts
- packages/server/src/core/procedure.ts
- packages/tests/server/regression/issue-4527-nested-middleware-root-context.test.ts
Closes #4527
Closes T-108
Merge the root context into the actual output of the middlewares only when necessary (function inputs like opts.ctx, used in t.middleware, t.use, t.procedure.query, t.procedure.mutation, t.procedure.subscription). This allows the proper order of overrides from root context -> middlewares instead of each middleware including the root context in it's `_ctx_out` type and preventing overriding the root context with nested middleware.
> fix(server): allow overriding root context in nested middleware

- packages/client/src/getFetch.ts
- packages/client/src/links/internals/httpUtils.ts
Closes https://github.com/trpc/trpc/issues/4589
This is a suggested fix to enable third party (like DataDog) to instrument fetch. We do this by avoiding to bind window or globalThis to fetch.
If we go this direction then why not just get rid of `resolveHTTPLinkOptions`?
> fix(client): enable instrumenting fetch

- packages/client/src/TRPCClientError.ts
- packages/client/src/links/httpLink.ts
- packages/client/src/links/internals/createHTTPBatchLink.ts
- packages/client/src/links/internals/httpUtils.ts
- packages/client/src/links/wsLink.ts
- packages/client/src/shared/transformResult.ts
- packages/tests/server/errors.test.ts
- packages/tests/server/interop/links.test.ts
- packages/tests/server/links.test.ts
- packages/tests/server/regression/issue-3359-http-status-413-payload-too-large.test.ts
Allows you to access:
- `error.meta?.response`
- `error.meta?.responseJSON`
In for instance links etc
> feat(`client`): add HTTP response object to `TRPCClientError.meta`

- examples/deno-deploy/src/index.ts
- www/docs/server/adapters/fetch.mdx
[`Deno.serve()` is now supported on Deno Deploy.
](https://twitter.com/lcasdev/status/1677673531809701889?s=20)
> refactor: use `Deno.serve()` in `deno-deploy` example

- examples/.experimental/next-app-dir/next.config.js
`Cannot get final name for export 'observable' of ....`
Fixes #4396
Revert the custom optimization configuration in webpack. Next.js provides support for [serverComponentsExternalPackages](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages) to address this issue./
For me, `config.optimization.concatenateModules = false` causes some other strange errors.
> fix: next-app-dir build fails

- www/src/components/Preview.tsx
- www/src/css/custom.css
- www/src/utils/handleSmoothScrollToSection.ts
Closes #4646
Remove smooth scroll behaviour from custom css.
I did write e2e test when I was fixing this bug locally, but don't think its good idea to have real browser running in a ci/cd just for this one test,
<details>
<summary>code</summary>
````ts
import { expect, test } from "@playwright/test";
test("should scroll to top on first visit navigation", async ({ page }) => {
await page.goto("http://localhost:3000/docs/quickstart");
await page.evaluate(() => window.scrollTo({ top: 400 }));
await page.waitForTimeout(500);
const conceptsLink = page
.getByLabel("Docs sidebar")
.getByRole("link", { name: "Concepts" });
await conceptsLink.click();
await page.waitForURL("**/docs/concepts");
await page.waitForTimeout(500);
const scrollTop = await page.evaluate(
() => …
```
> css: remove smooth scroll

- packages/client/src/createTRPCUntypedClient.ts
- packages/react-query/src/server/types.ts
- packages/react-query/src/ssg/ssg.ts
- packages/tests/server/react/ssgExternal.test.ts
Closes #
- allows passing an UntypedClient directly, and not just a proxy one, when creating server helpers
> feat(client): allow UntypedClient direclty in server helpers

- packages/tests/server/regression/issue-4645-inferProcedureOutput.test.ts
- packages/tests/tsconfig.json
Closes #4645
Add test for #4645 - we have the correct behavior. See inline
cc @ddydng: you might be looking for `inferTransformerProcedureOutputs` or `inferRouterOutputs` - see https://trpc.io/docs/client/vanilla/infer-types
> chore: add test for #4645

- packages/server/src/core/index.ts
- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/middleware.ts
- packages/tests/server/middlewares.test.ts
- www/docs/server/middlewares.md
Proposal/feat: `standaloneMiddleware`
```
const projectAccessMiddleware = standaloneMiddleware<{
ctx: { allowedProjects: string[] }; // defaults to 'object' if not defined
input: { projectId: string }; // defaults to 'unknown' if not defined
}>().create((opts) => {
if (!opts.ctx.allowedProjects.includes(opts.input.projectId)) {
throw new TRPCError({
code: 'FORBIDDEN',
message: 'Not allowed',
});
}
return opts.next();
});
```
Enables creation of middlewares that are not bound to any particular
tRPC instance; instead they can define a type of `Context`/`Input` that they
expect, and as long as the preceding middleware chain provides `Context` and `Input`
types that are assignable to the middleware's required context type,
the middleware can be used in the chain. The required context defaults …
> feat(`server`): add standalone middleware (experimental)

- www/docs/community/awesome-trpc.mdx
Adds `k6-trpc` adapter to community page.
> docs: add k6-trpc extension

- .changeset/twelve-rocks-look.md
- packages/server/src/http/resolveHTTPResponse.ts
This PR fixes an issue where context would be empty in `onError` and `errorFormatter` functions when calling the TRPC server with invalid JSON data.
We encountered this error while testing by calling an endpoint like `http://localhost:3001/trpc/brands.getDefault?input=QUERY`. Because "QUERY" is not a valid JSON, the default `getJsonContentTypeInputs` (i.e. `getInputs`) function would throw. Since context currently only gets generated *after* the input is parsed, it wouldn't be created correctly.
> We use context to communicate through the application the configuration parameters. One of the configurations is the production/development stage which we use to determine whether error should be transformed. Because of the bug, the transformer wouldn't work as expected and essentially leaked …
> fix(`@trpc/server`): rearrange the order of context generation in `resolveHTTPResponse` method

- .github/workflows/main.yml
all PRs are failing cause v4 cannot be found. did renovate fuck up?
looks like it's in beta: https://github.com/codecov/codecov-action/releases
> fix: codecov v4 doesn't exist?

- packages/react-query/src/shared/proxy/useQueriesProxy.ts
- packages/tests/server/react/useQueries.test.tsx
> fix(`react-query`): `useQueries` does not pass context data

- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/internals/getQueryKey.ts
- packages/react-query/src/internals/useQueries.ts
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/shared/hooks/types.ts
- packages/react-query/src/shared/polymorphism/mutationLike.ts
- packages/react-query/src/shared/polymorphism/queryLike.ts
- packages/react-query/src/shared/polymorphism/routerLike.ts
- packages/react-query/src/shared/proxy/useQueriesProxy.ts
- packages/react-query/src/utils/inferReactQueryProcedure.ts
- packages/server/src/core/procedure.ts
- packages/server/src/core/types.ts
- packages/tests/package.json
- packages/tests/server/input.test.ts
- packages/tests/server/react/errors.test.tsx
- packages/tests/server/react/formData.test.tsx
- packages/tests/server/react/invalidateQueries.test.tsx
- packages/tests/server/react/polymorphism.common.tsx
- packages/tests/server/react/polymorphism.factory.tsx
- packages/tests/server/react/polymorphism.subtyped-factory.tsx
- packages/tests/server/react/polymorphism.test.tsx
- packages/tests/server/regression/issue-4645-inferProcedureOutput.test.ts
- packages/tests/server/routerMeta.test.ts
If we can remove TPath from the types, then the polymorphism work mostly becomes redundant, since this was the key thing which makes query types structurally incompatible. It's not clear if we actually need TPath encoded into the types 
> Drop TPath from type system, fix polymorphism types

- packages/server/src/adapters/node-http/content-type/json/getPostBody.ts
- packages/tests/server/adapters/__router.ts
- packages/tests/server/adapters/express.test.tsx
Closes #4886
Issue #4886 describes the bug. I could see no reason to hang up the underlying TCP socket in this case so I just made a PR.
Wrote a failing test first to verify the bug, then changed the implementation.
> fix(`server`): don't destroy underlying tcp socket when maxBodySize exceeded

- packages/server/src/adapters/node-http/content-type/form-data/index.ts
Closes #4867
- exports the error class so that it can be used for error handling
> fix(form-data): export `MaxPartSizeExceededError` for error handling

- www/docs/client/nextjs/introduction.mdx
Closes #null
Fixed typo in client/nextjs/introduction
> fix(docs): typo in client/nextjs/introduction

- .github/workflows/lint.yml
lint ci task is slow as hell since we're doing sooo much stuff in a single runner and is slowed down by turbo concurrency limit
trying to split it up into multiple runners to speed it up a bit
> chore: split up lint ci

- packages/server/src/adapters/node-http/content-type/form-data/index.ts
- packages/server/src/adapters/node-http/content-type/form-data/memoryUploadHandler.ts
- packages/server/src/adapters/node-http/content-type/form-data/uploadHandler.ts
- packages/tests/server/react/formData.test.tsx
…dler
Sending a FormData object with a mix of files and text fields was not possible when using `experimental_createFileUploadHandler`, because the handling of all fields was baked into the `UploadHandler` business logic, and logic for handling non-file fields was only implemented for the memory upload handler. Ergo, the file upload handler just ignored all fields that were not files.
This PR does a few things:
1. Moves the logic for handling non-file fields to `parseMultipartFormData`, and only file fields are passed to the upload handler. Now non-file fields are handled identically regardless of upload handler type.
2. Like with other body parsers, adds `maxBodySize` parameter to the function `parseMultipartFormData` that defaults to Infinity. Throws when combined size of all fields and …
> feat(server): allow a mix of text and files with fileUploadHandler

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/middleware.ts
- packages/tests/server/middlewares.test.ts
- packages/tests/server/regression/issue-4947-merged-middleware-inputs.test.ts
- www/docs/server/middlewares.md
Closes #4947
There was a problem in the current implementation of `experimental_standaloneMiddleware`
where the `input` type was not merged properly in the middleware chain.
Example:
```
const t = initTRPC.create();
const schemaA = z.object({ valueA: z.string() });
const schemaB = z.object({ valueB: z.string() });
const mw1 = experimental_standaloneMiddleware<{
input: z.infer<typeof schemaA>;
}>().create((opts) => {
return opts.next();
});
const mw2 = experimental_standaloneMiddleware<{
input: z.infer<typeof schemaB>;
}>().create((opts) => {
return opts.next();
});
const combinedInputThatSatisfiesBothMiddlewares = z.object({
valueA: z.string(),
valueB: z.string(),
})
t.procedure
.input(combinedInputThatSatisfiesBothMiddlewares)
.use(mw1)
.use(mw2) // <-- error: input only has { valueA: …
```
> fix(server): merge _input_out when using standalone middlewares

- www/docusaurus.preferredTheme.js
Closes #Have_no_issue_created
Localstorage do not have setAttribute method. Change it to .setItem as intended.
> fix: localstorage do not have setAttribute method

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/middleware.ts
- packages/tests/server/regression/issue-4947-merged-middleware-inputs.test.ts
…wares
Closes #4972
The previous fix fixed _input_out which resolved the incorrect types on the server side when defining the procedure, but still had incorrect _input_in types, which clients use.
Similar fix as before: do a merge of the _input_in types similarly as with _input_out.
> fix(server + client): incorrect inferred input type when using standalone middleware

- packages/server/src/shared/internal/serialize.ts
- packages/tests/server/regression/issue-4985-serialize-type.test.ts
…utputs
Closes #4985
Fixes some issues with inferring Record types as procedure outputs. See linked issue.
> fix(server + client): fix some issues with inferring Record types as procedure outputs

- www/docs/client/react/setup.mdx
https://github.com/trpc/trpc/issues/5006
Closes [#5006](https://github.com/trpc/trpc/issues/5006)
update the installation instructions to be ^4.0.0-range of the RQ deps until v11 is out
> docs: keep RQ at v4 until trpc v11 is released

- packages/next/src/app-dir/links/nextHttp.ts
Use `fetch` from options when it's defined.
In the current implementation, `opts.fetch` it typed but never gets used.
> fix(next): omit "fetch" from options

- www/docs/client/nextjs/setup.mdx
Closes #5022 
update the installation instructions to be ^4.0.0-range of the RQ deps until v11 is out
> docs: keep RQ at v4 on nextjs setup until trpc v11 is released

- packages/client/src/internals/TRPCUntypedClient.ts
- packages/react-query/src/internals/getClientArgs.ts
- packages/react-query/src/server/ssgProxy.ts
- packages/server/src/core/index.ts
- packages/server/src/core/internals/builderTypes.ts
- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/internals/utils.ts
- packages/server/src/core/middleware.ts
- packages/server/src/core/procedure.ts
- packages/server/src/core/router.ts
- packages/server/src/transformer.ts
> chore(v11): remove some deprecated stuff

- packages/server/src/core/internals/utils.ts
- packages/server/src/shared/internal/serialize.ts
- packages/server/src/types.ts
- packages/tests/server/regression/issue-5034-input-with-index-signature.test.ts
Closes #5034
When dealing with objects that have an index signature and known properties, such as:
```
{
[x: string]: unknown;
foo: string
}
```
If you use `Omit`, `Pick` or `keyof` in any capacity, the resulting iteration loses type information because the key collapses to just `string | number` due to how union types work:
```
type Foo = keyof { [x: string]: unknown, foo: string } // string | number. 
// string | 'foo' collapses to just ---> string
// number is included because objects can be accessed with number keys as well
```
This is intended behavior in TypeScript, see e.g. [this TS issue](https://github.com/microsoft/TypeScript/issues/45367) and linked related issues of the same issue.
This means to support use cases with such types, we need to carefully construct our key …
> fix(client+server): avoid losing type information w/ index signatures

- www/docs/client/react/infer-types.md
Fix type inference example to reference the createMyRouter function defined earlier in the file (rather than the nonexistent createRouter).
Closes #
> [Docs] infer-types.md: fix typo in name of router factory function

- examples/next-prisma-starter/tailwind.config.ts
Since we have a components dir in src/ let's make sure Tailwind can find it.
Closes #5032 
Addressed issue where components added to the src/components directory weren't being considered by Tailwind when optimizing resulting in missing style/classes on components (but not the main pages).
> #5032 Fix tailwind.config.ts for examples/next-prisma-starter

- packages/server/src/core/internals/utils.ts
- packages/server/src/shared/internal/serialize.ts
- packages/server/src/types.ts
- packages/tests/package.json
- packages/tests/server/regression/issue-5034-input-with-index-signature.test.ts
- packages/tests/server/regression/issue-5037-context-inference.test.ts
- tsconfig.build.json
Closes #5037
There were two bug reports about 10.43.3, the cause of which can be traced back to PR #5017 (which fixed another inference bug... seeing a pattern here)
I _think_ in both bug reports the cause has something to do with using generics to construct either tRPC instances or tRPC middlewares using a type parameter that is not constrained to `object`, which causes TS to infer incompatible types for middleware builders after `Overwrite` was changed to only do the key-wise merge on types that extend `object`.
This PR basically reverts the changes in #5017 and replaces it with a check to see whether `TWith` (the type that overwrites the target type) extends a JS primitive, and if so, wholly replaces it. This achieves the intended end result of #5017 while (hopefully) fixing the issues …
> fix(server): fix regression introduced by #5017

- packages/server/src/shared/internal/serialize.ts
- packages/tests/server/regression/issue-4985-serialize-type.test.ts
Closes #
apparently our earlier regression tests did not catch a regression to record serialization, because the tests were constructed using .output() instead of inferring the return type of the query/mutation.
> fix(client+server): fix output serialization of records (again)

- packages/server/src/core/internals/procedureBuilder.ts
- packages/server/src/core/internals/utils.ts
- packages/server/src/core/middleware.ts
- packages/tests/server/regression/issue-5056-input-parser-standalone-mw-inference.test.ts
…rocedure inputs
Closes #5056
E.g.
```
.input(z.object({ foo: string })
.use(middlewareThatRequiresOptionalFoo)
.query(({ input }) => ...)
```
input.foo should still be string, not an optional string.
> fix(server): middleware input requirements shouldn't widen procedure inputs

- packages/server/src/adapters/fetch/fetchRequestHandler.ts
- packages/tests/server/adapters/fetch.test.ts
Extends [PR 4893](https://github.com/trpc/trpc/pull/4893)
This was discussed in private, but just for the reference what is it all about:
Having a trailing slash in endpoint path caused 404's.
Now it doesn't =)
Closes #4893
> fix(server): fetch adapter endpoint path with trailing slash causes 404

- packages/server/src/shared/internal/serialize.ts
- packages/tests/server/regression/issue-5075-complex-zod-serialized-inference.test.ts
> fix(client+server): non-records inferred as records when serializing as json

- packages/server/src/http/types.ts
- packages/tests/server/responseMeta.test.ts
- Changes type of `ResponseMeta['headers']` from `Record<string, string>` to `HTTPHeaders`
- This allows for multiple headers setting. My use case: setting cookies with it.
> fix(server): Response meta headers type

- packages/server/src/shared/internal/serialize.ts
Followup to #5077 ; prevents false positives from IsRecord
> fix(server): constrain the IsRecord utility type to objects

- examples/next-prisma-starter/src/server/routers/post.ts
Since TypeScript introduced the `satisfies` keyword, it's now recommended to use it instead of `Prisma.validator`
From the Prisma Docs:
> If you have a use case for Prisma.validator, be sure to check out this [blog post](https://www.prisma.io/blog/satisfies-operator-ur8ys8ccq7zb) about improving your Prisma workflows with the new TypeScript satisfies keyword. It's likely that you can solve your use case natively using satisfies instead of using Prisma.validator.
https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety/prisma-validator
Before using `Prisma.validator`:
```typescript
const defaultPostSelect = Prisma.validator<Prisma.PostSelect>()({
id: true,
title: true,
text: true,
createdAt: true,
updatedAt: true,
});
```
After using `satisfies` keyword …
> chore(examples): using TypeScript `satisfies` keyword instead of `Prisma.validator`

- packages/client/src/internals/retryDelay.ts
- packages/client/src/links/wsLink.ts
- packages/tests/server/websockets.test.ts
Closes #5028 
Closes #5055
Adds `lazy` option on `WSClient`
`wsLink.ts` is spaghetti 🍝
> feat(client): add `lazy` option on `WSClient`

- www/package.json
Closes #
In dev when updating docs, starting dev docusaurus takes a long time and often crashes to OOM. Bumping the node process max heap size to 16 gigs prevents this and also seems to make starting the dev docs server a lot faster. Obviously not ideal but does the job.
oh lawd he comin
> fix(devenv): increase docusaurus node process memory limit

- packages/client/src/links/wsLink.ts
- packages/tests/server/websockets.test.ts
Closes #5118 
Mark the connection as `"connecting"` when we're attempting to reconnect. 
The root of the issue is https://github.com/trpc/trpc/blob/next/packages/client/src/links/wsLink.ts#L312
Subscriptions aren't automatically restored because the connection is marked as closed.
Adding tests soon
> fix(client): mark ws connection as connecting

- packages/client/src/TRPCClientError.ts
- packages/client/src/links/loggerLink.ts
- packages/client/src/shared/transformResult.ts
- packages/next/src/app-dir/links/nextCache.ts
- packages/next/src/app-dir/links/nextHttp.ts
- packages/next/src/withTRPC.tsx
- packages/server/src/adapters/next.ts
- packages/server/src/core/initTRPC.ts
- packages/server/src/core/internals/config.ts
- packages/server/src/error/utils.ts
- packages/server/src/http/getHTTPStatusCode.ts
- packages/tests/server/adapters/fastify.test.ts
- packages/tests/server/adapters/fetch.test.ts
- packages/tests/server/errors.test.ts
- packages/tests/server/index.test.ts
- packages/tests/server/links.test.ts
- packages/tests/server/react/overrides.test.tsx
- packages/tests/server/react/trpc-options.test.tsx
- packages/tests/vitest.config.ts
- tsconfig.build.json
Closes #5175
Enables the `noPropertyAccessFromIndexSignature` compiler option. Minor updates to files / lines impacted by enabling this option.
> chore: enable noPropertyAccessFromIndexSignature compiler option

- .wip/changes.md
- packages/next/package.json
- packages/react-query/package.json
Closes #
React has released v18.2.0 for about 2 years now.
This upgrade is also [blocking](https://github.com/trpc/trpc/pull/3343) replacing obsolete `react-ssr-prepass` library with a native React streaming function.
It seems like nothing did break, but I'm not sure if there were actually tests made against react v16 - as devDependencies in respective packages were listing v18.2.0 for some time now.
> chore(deps): update react to v18

- packages/next/src/createTRPCNext.tsx
- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/internals/useQueries.ts
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/shared/index.ts
- packages/react-query/src/shared/proxy/useQueriesProxy.ts
- packages/tests/server/react/useSuspenseQueries.test.tsx
- www/docs/client/react/suspense.md
Closes #4454 
Works just like `useQueries` but supports Suspense. Like `useSuspenseQuery` returns a `[data, queries]` tuple of the results for easier renaming and iteration over the results.
Essentially a thin wrapper around the [`useSuspenseQueries`](https://tanstack.com/query/latest/docs/react/reference/useSuspenseQueries) hook added in TanStack Query v5.
```ts
const appRouter = t.router({
foo: t.procedure.query(() => 'foo' as const),
bar: t.procedure.query(() => 'bar' as const),
});
const [posts, postQueries] = client.useSuspenseQueries((t) => [t.foo(), t.bar() ]);
// ^? ["foo", "bar"]
```
> feat(react-query): Add `trpc.useSuspenseQueries()`

- examples/.experimental/next-formdata/src/server/trpc.ts
- examples/.test/ssg/src/server/trpc.ts
- examples/next-edge-runtime/src/server/trpc.ts
- examples/next-minimal-starter/src/server/trpc.ts
- examples/next-prisma-starter/src/server/trpc.ts
- examples/next-prisma-websockets-starter/src/server/trpc.ts
- examples/soa/server-lib/index.ts
- www/docs/migration/migrate-from-v9-to-v10.mdx
- www/docs/server/authorization.md
- www/docs/server/context.md
- www/docs/server/merging-routers.md
- www/docs/server/metadata.md
- www/docs/server/middlewares.md
- www/docs/server/routers.md
- www/docs/server/server-side-calls.md
Closes #
- I don't see the point of defining a `const isAuthed = t.middleware(() => ...)` over defining it inline, I think inline is cleaner and should be the recommended pattern
- Using `t.middleware` is rarely needed.
> chore(www): drop `t.middleware()` as a recommendation in the docs

- packages/tests/server/validators.test.ts
References #1963
Adds example on how to access `Context` inside a custom input parser
> chore(tests): add recipe on how to access context in input parsers

- packages/server/src/core/router.ts
- packages/tests/server/createCaller.test.ts
This will allow making some nicer RSC-like-clients:
```ts
const createCaller = t.createCallerFactory(appRouter);
// ...
const trpc = async () => createCaller(await createContext());
async function MyComponent() {
const posts = await (await trpc()).post.all();
// ...
}
```
```ts
const createCaller = t.createCallerFactory(appRouter);
// ...
const trpc = createCaller(createContext)
async function MyComponent() {
const posts = await trpc.post.all();
// ...
}
```
> feat: allow passing a function to `createCaller`

- packages/client/src/links/internals/httpUtils.ts
- packages/client/src/links/types.ts
- packages/tests/server/headers.test.tsx
Allows returning a Headers object from `httpLinkOptions.headers`, mostly useful in Next.js when forwarding headers to CCs during SSR:
```ts
httpBatchLink({
url: "...",
headers: () => {
const headers = new Headers(await props.headersPromise);
// comes from a headers() call in parent SS ^^
headers.set("foo", "bar");
return headers;
},
}),
```
Small and minor change so that `Object.fromEntries()` can be skipped in user-land
> HeadersInitEsque

- packages/core/src/http/index.ts
- packages/core/src/index.ts
- packages/core/src/observable/index.ts
- packages/core/src/rpc/index.ts
just converts `export * from 'x'` to export everything but named from all public entrypoints (they which are specified in rollup config) (in core package only)
> chore: named-exports in core package

- packages/server/src/adapters/ws.ts
- pnpm-lock.yaml
Closes #5268
This fix removes the need for magic values and references OPEN value from WebSocket in place of relying on instance value.
It fixes when using subscriptions when running trpc from bun.
As discussed here https://github.com/trpc/trpc/issues/5268
> fix(ws): use websocket OPEN reference (next)

- www/docs/server/adapters/fetch.mdx
It fixes the runtimes-specific setup docs for Astro.
Astro API Route handlers must be written in caps. "all" -> "ALL"
I got this message:
[router] No API Route handler exists for the method "GET" for the route /trpc/trpc. Found handlers: "prerender", "all"
One of the exported handlers is "all" (lowercase), did you mean to export 'ALL'?
> docs: Astro API Route handler in fetch.mdx

- www/docs/server/adapters/express.md
Added the necessary import statement for 'express' in adapters/express.md
Closes #5372
- docs(server): add missing 'express' import in setup example
- Updated the code snippet in the server setup documentation to include the necessary 'express' module import statement. The absence of this import could lead to confusion for users following the example. With this addition, the documentation now accurately reflects the correct dependencies and ensures a smooth setup process for tRPC with Express.
> fix: add missing 'express' import in adapters/express.md

- www/docs/server/data-transformers.md
No code changes, this PR updates the data transformer docs to include an example of using the data transformer with the TRPC React Query wrapper '@trpc/react-query'. It was not intuitive to use with React Query as the `CreateTRPCReact()` differs from `CreateTRPCNext()/createTRPCClient()` as it doesn't accept a transformer.
> docs: add react query data transformer example

- packages/tests/package.json
- packages/tests/server/validators.test.ts
- pnpm-lock.yaml
- www/docs/server/validators.md
- www/package.json
Closes #5384
Removes `@effect/schema`
- #5384 failed because it had breaking changes
- It took me more than 5min to understand what changed and this isn't an officially supported validator
- It hasn't reached `1.x` yet so I'd consider it unstable. 
Deleting it for now. Would be fine with someone reverts this PR and upgrades it
> chore: rm `@effect/schema` from docs and code

- packages/server/src/unstable-core-do-not-import/error/formatter.ts
- packages/server/src/unstable-core-do-not-import/http/resolveHTTPResponse.ts
- packages/server/src/unstable-core-do-not-import/initTRPC.ts
- www/docs/server/error-formatting.md
- Unnecessary fn that is only used once in `resolveHTTPResponse`
- `initTRPC` simplification
> chore(server): some cleanup

- .eslintrc.js
- packages/server/src/adapters/fetch/fetchRequestHandler.ts
- packages/server/src/adapters/standalone.ts
- packages/server/src/http/toURL.ts
- packages/server/src/http/toUrl.ts
Might close #5405
Parse url in a safer way
> fix(server): parse url safer in fetch adapter

- CONTRIBUTING.md
- packages/server/src/unstable-core-do-not-import/initTRPC.test.ts
- packages/server/src/unstable-core-do-not-import/router.mergeRouters.test.ts
- packages/server/src/unstable-core-do-not-import/router.test.ts
Ref #4465
- Unit tests should sit next to the units
- Integration tests should live in `packages/tests`
- _We should probably add a `@trpc/test-lib` as well for utils_
> chore: move some tests to be contextual

- www/docs/migration/migrate-from-v10-to-v11.mdx
Closes #
This PR fixes a typo in the docs – located in the v10 to v11 migration [page](https://trpc.io/docs/migrate-from-v10-to-v11#transformers-are-moved-to-links-breaking).
> docs: remove typo in v11 migration docs

- packages/react-query/src/internals/useHookResult.ts
Might close #5429
Skip using `useRef`, use `useMemo()` instead
Not sure how _"Cannot assign to read-only property 'path'"_ can happen, but this should make it impossible since it'll return a new obj every time instead
> fix(react-query): no ref in `useHookResult()`

- packages/react-query/src/internals/useHookResult.ts
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/shared/hooks/types.ts
Ref #5429
Simplifies `useHookResult()`
> chore(react-query): simplify `useHookResult()`

- .github/workflows/release-tmp.yml
- packages/next/src/withTRPC.tsx
Closes #
Accidentally did some breaking changes in #5426 to do when you combine `getServerSideProps` and `getInitialProps` which worked prior
Noticed when upgrading at work.
This is a complete hack but hopefully our pages-router-stuff won't be long-lived.
> fix(next): fix unintentional breaking change from prepass PR

- packages/server/src/unstable-core-do-not-import/parser.ts
- packages/tests/package.json
- packages/tests/server/outputParser.test.ts
- packages/tests/server/validators.test.ts
- pnpm-lock.yaml
- www/docs/main/quickstart.mdx
- www/docs/server/validators.md
- www/package.json
`@decs/typeschema` was restructured (decs/typeschema#32) and now we recommend using `@typeschema/valibot` for Valibot support on tRPC
This PR replaces the package on docs and tests
> docs: replace @decs/typeschema with @typeschema/valibot

- www/docs/server/merging-routers.md
Updates `merging-routers.md` to correct a minor spelling mistake: 
> `neested2` -> `nested2`
> docs: minor spelling mistake update in merging-routers.md

- www/versioned_docs/version-9.x/reactjs/invalidateQueries.md
Updates the code example in `invalidateQueries.md` to use `trpc.useUtils` to call `utils.invalidateQueries`, rather than the old `trpc.useContext`.
> docs: update invalidateQueries.md to use useUtils rather than useContext

- .vscode/settings.json
- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/internals/getClientArgs.ts
- packages/react-query/src/internals/getQueryKey.test.ts
- packages/react-query/src/internals/getQueryKey.ts
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/utils/createUtilityFunctions.ts
- packages/tests/server/react/__testHelpers.tsx
- packages/tests/server/react/useInfiniteQuery.test.tsx
- www/docs/client/react/useInfiniteQuery.md
- www/docs/migration/migrate-from-v10-to-v11.mdx
Pass direction from useInfiniteQuery function context (https://tanstack.com/query/v5/docs/framework/react/guides/query-functions#queryfunctioncontext) to procedure input in addition to page param.
This is useful for bi-directional infinite queries so you know in which direction to fetch.
Closes https://github.com/trpc/trpc/issues/5514
> feat(react-query): Pass useInfiniteQuery direction to procedure input

- packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts
- packages/server/src/adapters/ws.ts
- packages/tests/server/adapters/fastify.test.ts
Closes #5530
I've moved connection event handler creation into a separate function to allow for it being used directly inside of the `@fastify/websocket` connection callback.
Also, I deliberately left prefix handling in `applyWSSHandler`, so we can leave routing to fastify itself.
For future consideration - might be worth using something in line of the following to stay compatible with future versions of `@fastify/websocket` (if my changes get approved) alongside with backwards compatibility:
```ts
fastify.get(prefix ?? '/', { websocket: true }, (connection, req) => {
onConnection('socket' in connection ? connection.socket : connection, req.raw);
});
```
There's a chance they might end up just exposing the raw `WebSocket` object on their end from the handler, but this isn't guaranteed to …
> fix(server): use the recommended connection handler from @fastify/websocket to avoid triggering stream backpressure (#5530)

- examples/.experimental/next-app-dir/package.json
- examples/.experimental/next-formdata/package.json
- examples/.test/diagnostics-big-router/package.json
- examples/.test/ssg-infinite-serialization/package.json
- examples/.test/ssg/package.json
- examples/minimal-react/client/package.json
- examples/next-big-router/package.json
- examples/next-edge-runtime/package.json
- examples/next-minimal-starter/package.json
- examples/next-minimal-starter/src/pages/index.tsx
- examples/next-prisma-starter/package.json
- examples/next-prisma-todomvc/package.json
- examples/next-prisma-websockets-starter/package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/react-query/src/createTRPCReact.tsx
- packages/react-query/src/internals/getQueryKey.ts
- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/server/package.json
- packages/tests/package.json
- packages/tests/server/___testHelpers.ts
- packages/tests/server/react/useQuery.test.tsx
- packages/tests/server/react/useSuspenseQuery.test.tsx
- pnpm-lock.yaml
- www/docs/client/react/disabling-queries.md
- www/sidebars.js
- www/vercel.json
Closes #5524
This pull request is heavily inspired by RTK query skipToken. 
https://redux-toolkit.js.org/rtk-query/usage/conditional-fetching#overview
We are introducing skipToken to react query wrapper which allows typesafe disabling of queries.
Problem, whenever we want to disable query based on missing parameters:
Solution:
This pr is backward compatible, enabled option still works
> feat: add typesafe react-query disabling via skipToken

- packages/server/src/adapters/aws-lambda/index.ts
- packages/server/src/adapters/aws-lambda/utils.ts
- packages/server/src/adapters/fastify/fastifyRequestHandler.ts
- packages/server/src/adapters/fetch/fetchRequestHandler.ts
> fix: pass-through all options to `resolveHTTPResponse`

- examples/next-prisma-websockets-starter/src/server/prodServer.ts
Closes #4810 
It seems next v13.4.3 added a breaking change that causes sockets to be closed when not handled by HMR. As a result, websocket connections fail to upgrade. I've applied a fix from the following thread to address this issue for now:
https://github.com/vercel/next.js/issues/50461#issuecomment-1686773347
> fix: custom websocket server not upgrading due to next 13.4.3+

- packages/next/src/app-dir/server.ts
- packages/server/src/unstable-core-do-not-import/procedure.ts
- packages/server/src/unstable-core-do-not-import/procedureBuilder.ts
Closes #
- Adds ability to automatically rethrow built-in Next.js errors in `experimental_createServerActionHandler()` 
- adds an `onError`-callback
- adds support for `experimental_caller` in server actions (I think!?)
- makes `createContext` in server actions optional if you have no context defined
> feat(next app dir): rethrow built-in Next errors

- examples/.experimental/next-app-dir/src/app/posts/_data.ts
- packages/server/src/adapters/next-app-dir/nextAppDirCaller.ts
- packages/server/src/adapters/next-app-dir/redirect.ts
cause next's way of throwing causes the compiler to lie to us and easy to cause typemismatch on frontend
This way we get the proper returntype on the client, namely `undefined`
The main difference is that you have to **return** the redirect since it doesn't throw inside the action.
> return redirect

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
Closes #5609
We missed using `optsRef`
> fix(react-query): use `optsRef` in `useSubscription`

- packages/server/package.json
- pnpm-lock.yaml
Removes an unused dependency.
The `aws-lambda` package is a poorly-named CLI tool, and not actually types for AWS Lambda events. 
https://www.npmjs.com/package/aws-lambda
This PR removes the unused dev dependency. I've confirmed the types used by the server are still valid:
> chore(deps): Remove unused dependency aws-lambda

- .github/workflows/main.yml
it just obfuscates what's going on for me
> chore: remove `name:` from jobs in ci

- packages/server/src/adapters/aws-lambda/content-type/json/index.ts
- packages/server/src/adapters/content-handlers/selectContentHandlerOrUnsupportedMediaType.ts
- packages/server/src/adapters/fastify/content-type/json/index.ts
- packages/server/src/adapters/fetch/content-type/json/index.ts
- packages/server/src/adapters/node-http/content-type/form-data/index.ts
- packages/server/src/adapters/node-http/content-type/json/index.ts
- packages/server/src/adapters/node-http/content-type/octet/index.ts
- packages/server/src/unstable-core-do-not-import/http/contentType.ts
- packages/tests/server/adapters/standalone.test.ts
Closes #5653
- improves error by providing the received content type to the error
- uses `Headers` (Node18+) whose `.get()` is case-insensitive
> chore: better error for mismatched content-type

- www/docs/community/awesome-trpc.mdx
Hi, 
I wrote [trpc-mqtt](https://github.com/imxeno/trpc-rabbitmq) a while ago, an MQTT adapter. It is based on [trpc-rabbitmq](https://github.com/imxeno/trpc-rabbitmq).
I have been using it in production for the past year with great success. A few people seem to have stumbled upon it an starred my repo. I'd like to add my package to the docs, as well as its inspiration.
Thank you for the great work :)
Cheers,
Erwan
- add trpc-rabbitmq & trpc-mqtt to the awesome-trpc list
> feat: add trpc-rabbitmq & trpc-mqtt to the awesome-trpc list

- packages/server/src/@trpc/server/index.ts
- packages/server/src/unstable-core-do-not-import/initTRPC.ts
Closes #5666
This change exports the `TRPCBuilder` class from `@trpc/server` package.
I don't know what the reasoning is specfically for keeping the entire `TRPCBuilder` class private, but given that exposing instances of that class to the user is required in order to use it, keeping the class private seems like it might have been to coerce users into using the `initTRPC....` functions instead of instantiating the class directly.
For this reason, I exported only the type of the class so that the type could be used to explicitly define context and/or meta types in JavaScript land...
```js
import { initTRPC } from '@trpc/server';
/** @type {import("@trpc/server").TRPCBuilder<{ ctx: MyContext }>} */
const init = initTRPC.context();
const t = init.create();
// Define procedures on `t` like …
```
> Export `TRPCBuilder` class from `@trpc/server` package

- packages/server/src/adapters/node-http/incomingMessageToRequest.test.ts
- packages/server/src/adapters/node-http/incomingMessageToRequest.ts
Closes #5725
Fixes a bug where node-http server would truncate POST bodies.
> fix(server): handle large POST bodies in node-http

- www/docs/community/awesome-trpc.mdx
This is partly an awesome-trpc PR, partly a request for feedback on a new library I just published (/evaluation of whether it is indeed "awesome"). It takes an tRPC router and turns it into a CLI:
- procedures are mapped to commands
- inputs like `z.object({foo: z.string()})` are mapped to `--foo bar` type flags
- flags are parsed according to their target type (supporting numbers, string, booleans etc.)
- `t.procedure.meta({description: 'Add two numbers'})` is used to add to command help text
- `z.whatever().describe('...')` is used to add to flag help text
More docs and usage examples on https://github.com/mmkal/trpc-cli
> Add trpc-cli to awesome-trpc

- www/docs/server/adapters/nextjs.md
Closes #N/A
Make the example code clearer on how to use tRPC in Next.js App Router Route Handlers.
The existing example code is already correct, however it could cause some confusion, since it uses the `const x = y => z` syntax (which is not immediately clear that the function returns `z` especially for JavaScript beginners).
In the Next.js Discord server, there has been [at least one help question](https://nextjs-forum.com/post/1238455667056971856) where the user tries to do this
```tsx
import { fetchRequestHandler } from "@trpc/server/adapters/fetch";
import { appRouter } from "@/server";
function handler(req: Request) {
fetchRequestHandler({
endpoint: "/api/trpc",
req,
router: appRouter,
createContext: () => ({}),
});
}
export { handler as GET, handler as POST };
```
and it doesn't …
> docs: Clarify how to use tRPC in Next.js Route Handlers

- .github/workflows/release-tmp.yml
- packages/server/src/adapters/next-app-dir/nextAppDirCaller.ts
- packages/server/src/adapters/next-app-dir/rethrowNextErrors.ts
The helpers we imported from the internal dist path are removed in Next.js 15 RC making the current action stuff incompatible.
This little workaround should fix this. We can clean it up once 15 goes stable and we can use that as a peer dependency for these new stuff I think
> chore: support next15 in actions

- .eslintrc.js
Closes #
- Allows `T` / `$`  as a valid generic argument without a suffix
- Also allows e.g. `T1` / `T2` / `T3`
> chore: loosen some generic types

- www/docs/client/react/createTRPCQueryUtils.md
The documentation around `createTRPCQueryUtils` is wrong. You need to pass a client created from `createClient`. If you try to pass the `CreateTRPCReactBase`, you'll get type errors.
> Fix createTRPCQueryUtils.md documentation

- examples/next-sse-chat/src/server/routers/channel.ts
- examples/next-sse-chat/src/server/routers/post.ts
- packages/client/src/links/httpSubscriptionLink.ts
- packages/server/src/@trpc/server/index.ts
- packages/server/src/adapters/ws.ts
- packages/server/src/unstable-core-do-not-import/procedureBuilder.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.test.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/tests/server/httpSubscriptionLink.test.ts
- packages/tests/server/react/useSubscription.test.tsx
- www/docs/client/links/httpSubscriptionLink.md
> feat: add `sse()`

- examples/next-sse-chat/.env.example
- examples/next-sse-chat/src/app/channels/[channelId]/hooks.ts
- examples/next-sse-chat/src/app/page.tsx
- examples/next-sse-chat/src/server/routers/channel.ts
- packages/client/src/links/httpSubscriptionLink.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.test.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/tests/server/httpSubscriptionLink.test.ts
- www/docs/client/links/httpSubscriptionLink.md
- www/docs/community/awesome-trpc.mdx
I caused a bug where  `id` in `sse({})`  wasn't propagated. Fixed it and added tests that the right thing is actually propagated
> fix(sse): `sse()`-id not propagated

- www/docs/client/react/suspense.md
`useSuspenseInfiniteQuery` returns an `InfiniteData` structure, which has the both the `pages` and `pageParams` attributes. This updates the example to suggest what a user likely expects `pages` to be.
> Correct example return type for pages

- www/docs/community/awesome-trpc.mdx
Add Start UI [web] to the list of Bootstrapers in awesome-trpc
Start UI [web] repository: https://github.com/bearstudio/start-ui-web
Start UI [web] documentation: https://docs.web.start-ui.com/ (for our tRPC usage, you can check it out [here](https://docs.web.start-ui.com/technologies#trpc) and [here](https://docs.web.start-ui.com/tutorials/create-your-first-crud#step-2-create-the-backend-router))
Start UI [web] demo: https://demo.start-ui.com/app
I'm not sure what I need to say to make this bootstrapper part of the awesome tRPC list, I'll be really happy to talk about it if there's anything missing 🙂
These PR add a new bootstraper (Start UI [web]) in the boostrapers section in Awesome TRPC.
- ~[ ] If necessary, I have added documentation related to the changes made.~
- ~[ ] I have added …
> doc(awesome-trpc): add Start UI [web] in bootstrappers section

- packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts
Closes #5857
Do strict false check since some libs don't implement `res.write()` correctly
> fix(server): strict `false`-check when calling `.write()`

- packages/server/src/unstable-core-do-not-import/http/resolveResponse.ts
Closes #
This currently makes it so that forwarding e.g. ping options don't work
> fix(server): forward `sseSubscription`-options to `sseStreamProducer`

- packages/client/src/links/internals/httpUtils.ts
Closes #5893
> ## 🎯 Changes
> `AbortSignal.throwIfAborted()` is NOT available on React Native and causes all tRPC procedures to fail on React Native. Since there is no good widely maintained polyfill for `AbortController / AbortSignal`, we could just use a straighforward implementation instead of using `throwIfAborted` directly (+ lightweight polyfill for `AbortError`)
> 
> This error was introduced with `11.0.0-rc.455` tag here:
> 
> https://github.com/trpc/trpc/pull/5865/files#diff-d2f09745539c905e09fb5b0eabdfddcca87cb2496a3bc9ddcd585c89e4620e8eR163
> 
> Alternative approach to this PR is bring back the deleted `AbortControllerInstanceEsque` polyfill and add our implementations there.
> fix(client): add fallback if `.throwIfAborted()` is not available

- examples/next-prisma-starter/src/server/prisma.ts
- examples/next-prisma-websockets-starter/src/server/prisma.ts
- packages/server/src/adapters/ws.ts
- packages/tests/server/createClient.test.ts
- packages/tests/server/react/regression/issue-1645-setErrorStatusSSR.test.tsx
- packages/tests/server/react/withTRPC.test.tsx
- packages/tests/server/regression/issue-4130-ssr-different-transformers.test.tsx
- www/docs/client/links/httpSubscriptionLink.md
Closes #5889
Use `globalThis` instead of `global`
> patch: use `globalThis.` over `global.`

- packages/client/src/links/httpSubscriptionLink.ts
- packages/tests/server/httpSubscriptionLink.test.ts
Closes #5900
Change de-serializer from `input` to `output`:
> https://github.com/trpc/trpc/blob/755f28799f40eb7fb56d065b6793af10271d407c/packages/client/src/links/httpSubscriptionLink.ts#L98
> fix: `httpSubscriptionLink` deserialization by using output deserializer

- packages/client/src/links/httpSubscriptionLink.ts
- packages/client/src/links/internals/urlWithConnectionParams.ts
- www/docs/client/links/httpSubscriptionLink.md
Closes #
Add ability for `eventSourceOptions` to be a callback
Useful when polyfilling `EventSource` with a more "rich" version
**📚  Docs:** https://www-git-07-17-eventsource-options-trpc.vercel.app/docs/client/links/httpSubscriptionLink#authorization-by-polyfilling-eventsourc
> feat(client): allow `eventSourceOptions` to be a callback

- examples/next-sse-chat/src/server/routers/post.ts
- packages/client/src/links/httpSubscriptionLink.ts
- packages/server/src/@trpc/server/index.ts
- packages/server/src/adapters/ws.ts
- packages/server/src/unstable-core-do-not-import.ts
- packages/server/src/unstable-core-do-not-import/procedureBuilder.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.test.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/server/src/unstable-core-do-not-import/stream/tracked.ts
- packages/tests/server/httpSubscriptionLink.test.ts
- packages/tests/server/websockets.test.ts
- www/docs/client/links/httpSubscriptionLink.md
- www/docs/further/websockets.md
> `sse({id, data})` -> `tracked(id, data)`

- www/docs/server/authorization.md
Fix `Cannot find name 'Context'.ts(2304)` in the provided example at `Option 2: Authorize using middleware`, which makes use of `Context` but does not import it.
> Fix missing import in example of authorization.md

- packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts
- packages/server/src/adapters/ws.ts
- www/docs/server/adapters/fastify.md
Follow-up of #5715.
Changes in #5715 added heartbeat logic to the basic websocket handler. This PR enables that same option in the Fastify plugin.
> feat(server): websocket keep alive for fastify

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
this change keeps the same as `useQuery`, 
https://github.com/trpc/trpc/blob/a7c0ee0456e6dbcf8269c65047bdb0cc86dd4fbf/packages/react-query/src/shared/hooks/createHooksInternal.tsx#L134-L141
> fix(react-query): get queryClient from trpc context

- www/docs/client/react/server-components.mdx
Closes #
Renamed the tRPC caller for Server Components to server.tsx to avoid having two client.tsx files in the tRPC folder. This helps keep the folder structure cleaner and reduces confusion for anyone reading the documentation.
- [✅ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
> docs/www: Renamed the tRPC caller for Server Components to server.tsx

- packages/client/src/internals/types.ts
- packages/next/src/app-dir/links/nextCache.ts
- packages/next/src/app-dir/server.ts
- packages/react-query/src/server/ssgProxy.ts
- packages/server/src/adapters/next-app-dir/nextAppDirCaller.ts
- packages/server/src/adapters/ws.ts
- packages/server/src/unstable-core-do-not-import/http/resolveResponse.ts
- packages/server/src/unstable-core-do-not-import/middleware.ts
- packages/server/src/unstable-core-do-not-import/procedure.ts
- packages/server/src/unstable-core-do-not-import/procedureBuilder.ts
- packages/server/src/unstable-core-do-not-import/router.ts
- packages/tests/server/callRouter.test.ts
- packages/tests/server/caller.test.ts
- packages/tests/server/getRawInput.test.ts
- packages/tests/server/httpSubscriptionLink.test.ts
- packages/tests/server/react/useSubscription.test.tsx
- packages/tests/server/websockets.test.ts
- www/docs/client/links/httpSubscriptionLink.md
- www/docs/further/websockets.md
Closes #
Example: 
https://github.com/trpc/trpc/blob/ddfcac1ebf345ebab289e34909e3a2fb12386745/www/docs/client/links/httpSubscriptionLink.md?plain=1#L71-L80
easier to test subscriptions
https://github.com/trpc/trpc/blob/2c044414468e145684a93fbf3f479d371dff65b8/packages/tests/server/websockets.test.ts#L1517-L1570
> feat/fix(server): pass the request's `AbortSignal` to procedures

- packages/react-query/src/internals/context.tsx
- packages/tests/server/react/createQueryUtils.test.ts
- packages/tests/server/react/useUtils.test.tsx
Closes #6028
Fixes types of `trpc`-prop in `.fetch()`
> fix(react-query): fix types of utility fns

- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/tests/server/httpSubscriptionLink.test.ts
Closes #
Fixes so we don't do cancellation errors on aborted requests
> fix(sse): no `onError`-calls on aborted requests

- packages/server/src/observable/observable.ts
- packages/server/src/unstable-core-do-not-import/types.ts
- packages/tests/server/websockets.test.ts
The `ReadableStreamDefaultController.error()` causes **any** future interactions with the associated stream to error.
Thus, if the underlying observable receives an error, it would have caused any `.next()` call on the iterator to throw instantly. In case of multiple emits, this would cause the error to propagate out of order.
In addition, this would have caused the `stopped` package in the ws adapter not to be sent. `await iterator.return?.()` would have thrown.
I'm not sure when this was introduced, but it seems to have been a somewhat recent regression.
> fix(server): ensure order of observable subscription errors

- www/docs/client/react/server-components.mdx
In this section of doc https://trpc.io/docs/client/react/server-components#leveraging-suspense 
there is bug / typo
Closes #
Bug 
```
const [data] = trpc.hello.useSuspenseQuery();
return <div>{greeting.data.greeting}</div>; 
```
greeting   is not defined  in the file 
changed to  
```
const [data] = trpc.hello.useSuspenseQuery();
return <div>{data.greeting}</div>; 
```
> doc  typo  in  RSC section

- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/asyncIterable.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/createDeferred.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/promiseTimer.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/withPing.ts
- packages/server/src/unstable-core-do-not-import/utils.ts
Some code refactoring to improve quality.
The `sseStreamProducer` is simplified and improved for readability. Used patterns are extracted into more general-purpose utils.
**However…** I do believe we have to move those patterns towards `resolveResponse()`, as we ought to merge the cancel conditions with the signal for `proc({..., signal})`. Otherwise (as it is right now), there will be dangling listeners on the user code (until the next `yield`). I just noticed this after making the changes o.O @KATT
> refactor(server/sse): split async iterable utils from `sseStreamProducer` 

- packages/react-query/src/rsc.tsx
The notes for the `createHydrationHelpers` function contain misspellings. This pull request addresses and corrects those errors.
> chore: Fix misspelling in the rsc.tsx file

- packages/react-query/src/internals/context.tsx
- packages/react-query/src/shared/proxy/utilsProxy.ts
- packages/react-query/src/shared/types.ts
- packages/tests/server/react/queryOptions.test.tsx
> fix: `useSuspenseQuery` for queryoptoins api

- examples/next-formdata/src/pages/api/trpc/[trpc].ts
- packages/server/src/adapters/express.ts
- packages/server/src/adapters/next.ts
- packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts
- packages/server/src/adapters/standalone.ts
- packages/tests/server/adapters/next.test.ts
Fixes a little hiccup introduced in #6098
> fix: next `createNextApiHandler` should return an async function

- packages/client/src/internals/signals.ts
- packages/server/src/unstable-core-do-not-import/http/resolveResponse.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.test.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/asyncIterable.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/promiseTimer.ts
- packages/server/src/unstable-core-do-not-import/utils.ts
Closes #6126
Added `AbortController` to internal `subscription` processing to avoid dangling generators in userland.
Consider userland like this:
```ts 
procedure.subscription(async function* (opts) {
// listen for new events
for await (const [data] of on(ee, 'add', { signal: opts.signal })) {
const post = data as Post;
yield post;
}
})
```
Before the changes, this would have had a dangling event listener (for just the very next event) **after** `opts.emitAndEndImmediately` or `opts.maxDurationMs` triggered. With the changes, the `opts.signal` triggers with these cancel conditions, so the event listener will be cleaned up properly.
> fix(sse): combine abort signal with internal one

- packages/server/src/unstable-core-do-not-import/http/getHTTPStatusCode.ts
- packages/server/src/unstable-core-do-not-import/rpc/codes.ts
- packages/server/src/unstable-core-do-not-import/types.ts
This PR target and will close #6137 
- Export `JSONRPC2_TO_HTTP_CODE`
- Add & export `HTTP_CODE_TO_JSONRPC2`
- Export `getStatusCodeFromKey`
- Add & export `getStatusKeyFromCode`
- Move the `Invert` type helper at `unstable-core-do-not-import/types.ts` and rename it to `InvertKeyValue`
I've not updated any documentation to my current changes, and I'm unsure if I should...
But we have a good documentation section about [error-handling](https://trpc.io/docs/server/error-handling) and it would make sense to mention it somewhere like there...
> PS: this is my first contribution to `[trpc](https://github.com/trpc/trpc)`, if I've missed something or did something wrong please let me know 🥹
> feat(server): expose more http helpers

- packages/server/src/unstable-core-do-not-import/utils.ts
Simple improvement as proposed by @KATT https://github.com/trpc/trpc/pull/6128#pullrequestreview-2379887271
> fix(server/util): dangling event listener in `AbortSignal.any` ponyfill

- packages/client/src/links/httpSubscriptionLink.ts
- packages/client/src/links/internals/urlWithConnectionParams.ts
- packages/tests/server/httpSubscriptionLink.test.ts
- www/docs/client/links/httpSubscriptionLink.md
Closes #6148
A new feature to supply the operation that initialises an EventSource in httpSubscriptionLink.
> feat(client): supply operation to the `httpSubscriptionLink`'s `eventSourceOptions`

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/tests/server/react/useSuspenseQuery.test.tsx
> fix(react-query): `useSuspenseQuery` does not forward trpc options

- www/docs/server/websockets.md
The [WebSockets](https://trpc.io/docs/server/websockets) documentation page for v11.x includes a malformed example. Specifically, the [`tracked()`](https://trpc.io/docs/server/websockets#automatic-tracking-of-id-using-tracked-recommended) part places the `StaticEventEmitterIteratorOptions` object in the `for of` statement instead of the `on` call expression, which obviously causes a syntax error.
> docs: fix syntax error in example websocket documentation page

- packages/client/package.json
- packages/next/package.json
- packages/react-query/package.json
- packages/server/package.json
- packages/server/src/unstable-core-do-not-import/http/resolveResponse.ts
- packages/server/src/unstable-core-do-not-import/stream/jsonl.test.ts
- packages/server/src/unstable-core-do-not-import/stream/jsonl.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.test.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/__tests__/serverResource.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/asyncIterable.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/createServer.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/timerResource.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/withPing.ts
- packages/server/src/unstable-core-do-not-import/stream/utils/withRefCount.ts
- scripts/entrypoints.ts
- tsconfig.build.json
Closes #
Introduced bugs in some edge cases in #6206 that were show-cased when reducing timeout for iterations in the tests
- Reintroduce deferreds in jsonl consumer
- Add `using` a bit more in tests, for fun
Hide whitespace when reviewing
> fix(server): `unstable_httpBatchStreamLink` hiccups

- packages/react-query/src/shared/proxy/utilsProxy.ts
Sorry, the last PR was from the wrong base branch and targeted at the wrong upstream branch.
Currently the query parameter of the predicate function inside the invalidate function of the react-query utils is typed in the following way:
```ts
Query<
inferProcedureInput<TProcedure>,
TRPCClientError<TRoot>,
inferProcedureInput<TProcedure>,
...
>
```
That's incorrect, because the Query type requires the result data type in the third parameter:
```ts
declare class Query<TQueryFnData = unknown, TError = DefaultError, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey> extends
```
That's why we have to update the typing to use the output as a third parameter:
```ts
Query<
inferProcedureInput<TProcedure>,
TRPCClientError<TRoot>,
inferTransformedProcedureOutput<TRoot, TProcedure>
...
> …
```
> Bugfix: Adjust invalidate typings of utils proxy of react-query

- www/docs/migration/migrate-from-v10-to-v11.mdx
I fixed a misdescription in the section about bumping the TypeScript version. 
The version was miswritten as "5.6.2" in the description.
> [docs] correct a mistake in the migration description

- www/src/css/custom.css
Adding the display none property to the code block with the class .shiki.min-light when the dark theme is active
Closes #6342
Fixing theme code block, custom.css:299 
Adding
``` css
[data-theme='dark'] .shiki.min-light {
display: none;
}
```
> style(src/css/custom.css): Adding display none property

- examples/minimal/package.json
- examples/minimal/src/client/index.ts
- examples/minimal/src/server/trpc.ts
- examples/minimal/src/shared/transformer.ts
- examples/next-minimal-starter/package.json
- examples/next-minimal-starter/src/server/trpc.ts
- examples/next-minimal-starter/src/utils/transformer.ts
- examples/next-minimal-starter/src/utils/trpc.ts
- pnpm-lock.yaml
StackBlitz is currently showing `any` as types on all outputs since it doesn't support latest version of TypeScript
This issue exists as we're using the generic arguments of `AsyncIterable` that were added in 5.7: https://github.com/trpc/trpc/blob/3ca3dded131ec590dc373cb61c027561175473b1/packages/server/src/unstable-core-do-not-import/clientish/serialize.ts#L29
The fix adds a transformer as that ends up being a code path that isn't using this. Kinda a hack but 🤷
> chore: fix stackblitz output types

- packages/server/src/unstable-core-do-not-import/stream/sse.test.ts
- packages/server/src/unstable-core-do-not-import/stream/sse.ts
This makes it closer to the HTTP wire format and compatible with Cloudflare Workers.
Closes #6360
- Updated SSE to encode as bytes to play well with the Cloudflare Workerd runtime
- Updated SSE tests to handle binary chunks while maintaining human-readable output. Added TextDecoder to convert Uint8Array chunks to strings without changing existing test behavior or assertions.
I have tested also things continue to work as is outside of Cloudflare when running the server w/ `createHTTPServer` .
> fix(server): encode the SSE messages as bytes instead

- packages/server/src/adapters/node-http/incomingMessageToRequest.ts
PR https://github.com/trpc/trpc/pull/6343 didn't account for when the socket object exists but lacks the `once` and `off` methods. 
This behavior has been observed in certain runtime environments, such as AWS Lambda, where the socket object provided in the request does not fully implement the expected Node.js Socket interface.
This is the object that gets returned where socket is defined but `off` and `once` properties are not:
```ts
socket: {
encrypted: true,
readable: true,
remoteAddress: '...',
address: [ ... ],
end: {},
destroy: {}
},
```
Verified now working using `pkg-pr-new` node package
> fix(server): handle missing socket.off and socket.once methods

- packages/server/src/adapters/express.ts
Closes #
It's a feature? of a bug fix?
The current way does not allow mounting the express middleware in many subpaths. If i were doing `app.use('/super/nested/path', createExpressMiddleware(...))` it would break, trpc would claim that `/super/nested/path/router.procedure` doesn't exist.
this way we just dont remove the forward `/` but we remove all which is before the `router.procedure` name.
- [] If necessary, I have added documentation related to the changes made.
- [] I have added or updated the tests related to the changes made.
> feat: allow middleware to be mounted anywhere

- packages/react-query/src/shared/hooks/createHooksInternal.tsx
- packages/react-query/src/shared/hooks/types.ts
Closes #
The the type of `result.data` can be `undefined`
> fix(react-query): type of `result.data` on subscriptions

- packages/server/src/unstable-core-do-not-import/router.test.ts
- packages/server/src/unstable-core-do-not-import/router.ts
Closes #6469
Fix race condition when loading lazy routers in parallel
> fix(server): parallel load calls of lazy router

- packages/server/src/@trpc/server/index.ts
- packages/server/src/adapters/ws.ts
Closes #
Fix exports of `callProcedure()`
> chore(server): fix exports of `callProcedure`

- packages/react-query/src/index.ts
- www/docs/migration/migrate-from-v10-to-v11.mdx
This partially reverts commit e5c0c1a8220fea9e49a6ba2fa1562abb86f4d6ee / #6382
It's just an annoying change for anyone upgrading and we're moving away from `@trpc/react-query` anyway
> Revert "fix(react-query): skip `export *` from `@trpc/client`"

- www/docs/server/procedures.md
just fixed copy pasta in docs. who am i shuold be query not a mutatoin.
> docs: (procedures.md) use query instead of mutation for whoami
